### PR TITLE
WIP: Added Initial Primitive types

### LINKED ISSUE #220: Add numeric ID to Primitives
**Is your feature request or enhancement related to a problem? What specifically could be better? Please describe.**
In the old AI, each primitive is represented by a numeric ID as part of an enum. This ID is sent over radio in order  
**Describe the solution you'd like**
Port over the enum from the old AI, and add a function that returns an enum for each primitive.
I will put up a WIP PR from my radio branch for reference (edit: #221).
@garethellis0 has suggested the visitor pattern for this instead, see discussion in #221, also see @MathewMacDougall's comment below

**Describe alternatives you've considered**
Might consider a mapping from enums to strings, but requires more discussion.

**Additional context**

### PR DESCRIPTION
**Pull request by henryymliu**
### Description
Basic addition of primitive types/IDs for primary use by the radio. *This PR is only meant for discussion purposes*, and is obviously a very rough implementation; whoever takes this task on next will fully implement what we decide on + testing. I am currently using this in my MRF branch.

@MathewMacDougall @garethellis0 thoughts?

### Testing Done
None yet :P hence WIP

### Resolved Issues
Resolves #220 

### Review Checklist
*(Please check every item to indicate your code complies with it (by changing `[ ]`->`[x]`). This will hopefully save both you and the reviewer(s) a lot of time!)*
***It is the reviewers responsibility to also make sure every item here has been covered***
- [ ] **Start of document comments**: each `.cpp` and `.h` file should have a comment at the start of it. See files in the `thunderbots/software/geom` folder for examples.
- [x] **Function comments**: All function definitions (usually in the `.h` file) should have a javadoc style comment at the start of them. For examples, see the classes defined in `thunderbots/software/geom` 
- [x] **Remove all commented out code**
- [x] **Remove extra print statements**: for example, those just used for testing
- [ ] **Resolve all TODO's**: All `TODO` (or similar) statements should either be completed or associated with a github issue
- [ ] **Justify drops in code coverage**: If this PR results in a non-trivial drop in code coverage (a bot should post a coverage diagram as a comment), please justify why we can't test the code that's not covered.

***Feel free to make additions of things that we should be checking to this file if you think there's something missing!!!!***

### CODE REVIEW

**Comment by MathewMacDougall** [comment]
I like this overall. Does the firmware use basically the same enum (does it check the `primitive_id` bits against enum values? If so, it might make sense to include this enum in the `shared_util` folder. That way if the ids ever get changed or re-ordered they should stay in sync. However it also makes sense to keep the enum with the `Primitive` class since that's where I would expect to find it.

**Comment by garethellis0** [comment]
At a high level, I think this would be more appropriately done as a visitor, rather then as another function on Primitive. This is basically the issue we had to address with GrSim movement, and I think the solution we ended up with was pretty elegant. 

Sorry if the above is a little vague, Mat should have a PR up for the GrSim movement up in the next few days that should make things clear, or I can explain in person. The visitor design pattern that I'm referencing is described here: https://sourcemaking.com/design_patterns/visitor

**Comment by henryymliu** [comment]
@MathewMacDougall  yep, firmware uses the same integer values given by the enum

@garethellis0 that sounds good, I will update the ticket with this suggestion

**Comment by henryymliu** [comment]
After some discussion, this will be handled by the primitive visitor.

**Pull request closed without merging**
