### PR TITLE
move generic world view widget

### LINKED ISSUE #1305: Create a generic WorldView widget
### Description of the task

The Visualizer currently has a widget for drawing the world (field, robots, ball, etc). This widget should be broken out to be shareable, since it will be useful for the Simulator.

### Acceptance criteria

- [ ] Make the `WorldView` widget generic / shareable

### PR DESCRIPTION
**Pull request by LiCody**
### Description
- moved world view widget from visualizer widget folder to generic widget folder

### Testing Done
CI, visual inspection

### Resolved Issues
resolves #1305 

### Review Checklist

**_It is the reviewers responsibility to also make sure every item here has been covered_**

- [ ] **Function & Class comments**: All function definitions (usually in the `.h` file) should have a javadoc style comment at the start of them. For examples, see the functions defined in `thunderbots/software/geom`. Similarly, all classes should have an associated Javadoc comment explaining the purpose of the class.
- [ ] **Remove all commented out code**
- [ ] **Remove extra print statements**: for example, those just used for testing
- [ ] **Resolve all TODO's**: All `TODO` (or similar) statements should either be completed or associated with a github issue
- [ ] **Justify drops in code coverage**: If this PR results in a non-trivial drop in code coverage (a bot should post a coverage diagram as a comment), please justify why we can't test the code that's not covered.

### CODE REVIEW

**Review by jonathanlew — APPROVED** [review]
LGTM!

**Review by MathewMacDougall — APPROVED** [review]

**Comment by MathewMacDougall** [comment]
Sorry for the rush, thanks for getting this up quickly!

**Review by akhilveeraghanta — APPROVED** [review]
:fire:

**Review by EvanMorcom — APPROVED** [review]
LGTM 🔥 🚒 🧨

**Pull request merged**
