### PR TITLE
Renamed play type to refbox game state and fixed the combo box

### PR DESCRIPTION
**Pull request by jonathanlew**
### Description
Play type is confusing because it's not a play type. It actually represents refbox game state

### Testing Done
visual inspection

### Review Checklist

**_It is the reviewers responsibility to also make sure every item here has been covered_**

- [ ] **Function & Class comments**: All function definitions (usually in the `.h` file) should have a javadoc style comment at the start of them. For examples, see the functions defined in `thunderbots/software/geom`. Similarly, all classes should have an associated Javadoc comment explaining the purpose of the class.
- [ ] **Remove all commented out code**
- [ ] **Remove extra print statements**: for example, those just used for testing
- [ ] **Resolve all TODO's**: All `TODO` (or similar) statements should either be completed or associated with a github issue
- [ ] **Justify drops in code coverage**: If this PR results in a non-trivial drop in code coverage (a bot should post a coverage diagram as a comment), please justify why we can't test the code that's not covered.

### CODE REVIEW

**Comment by jonathanlew** [comment]
WIP: need to merge in #1546

**Review by garethellis0 — CHANGES_REQUESTED** [review]
I think we need to update some dynamic params in the `yml` files as well?

**Comment by jonathanlew** [comment]
> I think we need to update some dynamic params in the `yml` files as well?

fixed

**Comment by jonathanlew** [comment]
Ready for review

**Review by akhilveeraghanta — DISMISSED** [review]
lgtm 🗳️

**Review by MathewMacDougall — COMMENTED** [review]
Looks good, just have a merge conflict

**Review by LiCody — COMMENTED** [review]
lgtm pending merge conflict

**Review by akhilveeraghanta — APPROVED** [review]

**Comment by garethellis0** [comment]
> I think we need to update some dynamic params in the `yml` files as well?

Bumping this

**Comment by jonathanlew** [comment]
> > I think we need to update some dynamic params in the `yml` files as well?
> 
> Bumping this

Which ones? It was fixed in a different PR

**Review by garethellis0 — APPROVED** [review]
> > > I think we need to update some dynamic params in the `yml` files as well?
> > 
> > 
> > Bumping this
> 
> Which ones? It was fixed in a different PR

Whoops, looks like you're right! Thanks.

**Review by MathewMacDougall — APPROVED** [review]

**Pull request merged**
