### PR TITLE
Removed unneeded primitives

### PR DESCRIPTION
**Pull request by jonathanlew**
### Description
Removed Dribble and Pivot Primitives, Actions and Intents

### Testing Done
CI

### Resolved Issues
#1611

### Review Checklist

**_It is the reviewers responsibility to also make sure every item here has been covered_**

- [ ] **Function & Class comments**: All function definitions (usually in the `.h` file) should have a javadoc style comment at the start of them. For examples, see the functions defined in `thunderbots/software/geom`. Similarly, all classes should have an associated Javadoc comment explaining the purpose of the class.
- [ ] **Remove all commented out code**
- [ ] **Remove extra print statements**: for example, those just used for testing
- [ ] **Resolve all TODO's**: All `TODO` (or similar) statements should either be completed or associated with a github issue
- [ ] **Justify drops in code coverage**: If this PR results in a non-trivial drop in code coverage (a bot should post a coverage diagram as a comment), please justify why we can't test the code that's not covered.

### CODE REVIEW

**Review by MathewMacDougall — DISMISSED** [review]
Nice. I also don't think the Spin/Movespin primitives are used, but those can be removed in a separate PR (whatever you prefer).

**Review by garethellis0 — APPROVED** [review]
_nice_

LGTM :+1: :tada:

**Comment by jonathanlew** [comment]
> Nice. I also don't think the Spin/Movespin primitives are used, but those can be removed in a separate PR (whatever you prefer).

It's unclear whether we want a distinct MoveSpin primitive compared to Move, so I'll hold off it for now

**Review by MathewMacDougall — APPROVED** [review]

**Review by EvanMorcom — APPROVED** [review]
LGTM :fire:

I wouldn't worry about move spin

It's currently not supported and will work entirely in the new implementation if we decide to bring it back

**Pull request merged**
