### PR TITLE
Replace case conversion function in C writer

### LINKED ISSUE #1887: Change C writer to use shared function for case conversion
### Acceptance criteria

- [ ] Item A
- [ ] Item B
- [ ] Item C

### PR DESCRIPTION
**Pull request by jsn0716**
### Description

Replace usage of `to_camel_case` with `to_pascal_case` defined in `case_conversion.py`

### Testing Done
Passes existing unit tests

### Resolved Issues
resolves #1887 

### Review Checklist

**_It is the reviewers responsibility to also make sure every item here has been covered_**

- [x] **Function & Class comments**: All function definitions (usually in the `.h` file) should have a javadoc style comment at the start of them. For examples, see the functions defined in `thunderbots/software/geom`. Similarly, all classes should have an associated Javadoc comment explaining the purpose of the class.
- [x] **Remove all commented out code**
- [x] **Remove extra print statements**: for example, those just used for testing
- [x] **Resolve all TODO's**: All `TODO` (or similar) statements should either be completed or associated with a github issue
- [x] **Justify drops in code coverage**: If this PR results in a non-trivial drop in code coverage (a bot should post a coverage diagram as a comment), please justify why we can't test the code that's not covered.

### CODE REVIEW

**Review by jonathanlew — COMMENTED** [review]
I don't really understand the reason for this change

**Comment by jsn0716** [comment]
This is in regards to [this comment](https://github.com/UBC-Thunderbots/Software/pull/1884#discussion_r554441990), there's two functions doing the same thing so replacing one with the other

**Review by jonathanlew — COMMENTED** [review]
Isn't camel case different from pascal case? I guess upper camel case is pascal case?

**Comment by jsn0716** [comment]
> Isn't camel case different from pascal case? I guess upper camel case is pascal case?

Yeah upper camel case is pascal case - `case_conversion.py` defines both lower and upper, so had to differentiate it

**Review by akhilveeraghanta — APPROVED** [review]
lgtm!

**Review by jonathanlew — APPROVED** [review]

**Pull request merged**
