### PR TITLE
Integrated SensorFusion into Full System

### LINKED ISSUE #609: Remove filterAndPublishVisionData wrapper function once we move to a better simulator
Currently we have a wrapper function around the `filterAndPublishVisionData` function because grSim sends garbage packets that contain bad data from very far in the future. Once we are using a better simulator that doesn't do this, we can remove this wrapper function.

### Blocked By 
#768 #1135

### LINKED ISSUE #1135: Integrate New Sensor Fusion Into Backends to Complete the SensorFusion-Backend Architecture
### Description of the task
Integrate new SensorFusion (#1241), new Backends (Simulator #1279, GrSim #1281, Radio #1282, Wifi #1217), and new Visualizer(#1277) together to realize the vision of the SensorFusion-Backend Architecture as described in the design doc: https://docs.google.com/document/d/13BExBYrU6o96WMQGdhUzqdiBatNYfe-HLZJH3kaj3fo/edit?usp=sharing

Incomplete list of things to do:
* Connect observers and subjects
* Delete Subject<World>, Subject<RobotStatus> and associated code from Backends, NetworkClient (will resolve #609)
* Make AI get World from SensorFusion
* Modify BUILD files

### Acceptance criteria

- [ ] Fully integrate the architecture as described in the Design Doc
- [ ] Manual testing with the visualizer
- [ ] Testing using simulated tests

### Blocked By
#764 #1204 #1277 #1241 #1279 #1217 #1282
optional: #1281

### LINKED ISSUE #1313: Restructure input vs output folders in backend
### Description of the task
Currently, the backend folder is split between input and output, with the idea that input is data coming into the software stack and output is the data that's sent out from the software stack. This is not actually the case, however, with radio_output also serving the role of receiving data from the robots. 

Some ideas include:
* separating out input from radio_output
* restructuring input output folders in backend to some other division, such as ssl msgs vs robot communication
* removing the hierarchy

Some thoughts:
* the ProtoMulticastListener can listen to TbotsRobotMsgs so that can all fit in the input folder
* mrf can't be neatly separated on an input/output basis since the annunciator (receives robot msgs, so it's an input) is a part of radio_output

Additionally, robot_status.* should be moved to the radio folder since it will no longer be used outside of radio

### Acceptance criteria

- [ ] Fix the inconsistency
- [ ] Verify that nothing functional changes

### Blocked By
#1135

### PR DESCRIPTION
**Pull request by jonathanlew**
### Description
* Integrated SensorFusion into AI and Backend Observers
* Deleted NetworkClient
* Rearranged Backend folder
* Removed RobotStatus from all GUIs

### Testing Done
confirmed it works visually

### Resolved Issues
resolves #1135
resolves #1313
resolves #609

### Length Justification
YEET

### Review Checklist

**_It is the reviewers responsibility to also make sure every item here has been covered_**

- [ ] **Function & Class comments**: All function definitions (usually in the `.h` file) should have a javadoc style comment at the start of them. For examples, see the functions defined in `thunderbots/software/geom`. Similarly, all classes should have an associated Javadoc comment explaining the purpose of the class.
- [ ] **Remove all commented out code**
- [ ] **Remove extra print statements**: for example, those just used for testing
- [ ] **Resolve all TODO's**: All `TODO` (or similar) statements should either be completed or associated with a github issue
- [ ] **Justify drops in code coverage**: If this PR results in a non-trivial drop in code coverage (a bot should post a coverage diagram as a comment), please justify why we can't test the code that's not covered.

### CODE REVIEW

**Review by akhilveeraghanta — DISMISSED** [review]
LGTM 🔥 🔥

**Comment by garethellis0** [comment]
> Removed RobotStatus from all GUIs

Don't we want to see robot status in the GUI's? :thinking:

**Review by garethellis0 — CHANGES_REQUESTED** [review]
> Removed RobotStatus from all GUIs

Don't we want to see robot status in the GUI's? :thinking: 

I'd like to double check that everything is still working properly, as this is a pretty major change. What should I run to do so?

**Comment by jonathanlew** [comment]
> > Removed RobotStatus from all GUIs
> 
> Don't we want to see robot status in the GUI's? thinking
> 
> I'd like to double check that everything is still working properly, as this is a pretty major change. What should I run to do so?

So RobotStatus is being replaced by TbotsRobotMsg and the wifi backend doesn't output RobotStatus. The new firmware doesn't output TbotsRobotStatus yet either.

**Testing:** The old robots output RobotStatus, which get converted to TbotsRobotMsg in the RadioBackend, so just run full system main with backend=radio should work

**Comment by garethellis0** [comment]
> Testing: The old robots output RobotStatus, which get converted to TbotsRobotMsg in the RadioBackend, so just run full system main with backend=radio should work

Sorry, how should we test this if we don't have a radio dongle on hand? Run the simulator and the wifi backend?

**Comment by jonathanlew** [comment]
> > Testing: The old robots output RobotStatus, which get converted to TbotsRobotMsg in the RadioBackend, so just run full system main with backend=radio should work
> 
> Sorry, how should we test this if we don't have a radio dongle on hand? Run the simulator and the wifi backend?

Got a couple ideas:
1. We could mock some TbotsRobotMsgs and send them from the standalone simulator on the right multicast group
2. We could inject SensorMsgs with TbotsRobotMsgs into SensorFusion in a SimulatedTest

**Comment by akhilveeraghanta** [comment]
> > > Removed RobotStatus from all GUIs
> > 
> > 
> > Don't we want to see robot status in the GUI's? thinking
> > I'd like to double check that everything is still working properly, as this is a pretty major change. What should I run to do so?
> 
> So RobotStatus is being replaced by TbotsRobotMsg and the wifi backend doesn't output RobotStatus. The new firmware doesn't output TbotsRobotStatus yet either.
> 
> **Testing:** The old robots output RobotStatus, which get converted to TbotsRobotMsg in the RadioBackend, so just run full system main with backend=radio should work

`firmware_new` does currently send `TbotsRobotMsgs`, it only populates the timestamp, we could populate more stuff with mock data if needed

**Review by kelvinkoon — DISMISSED** [review]
LGTM pending testing concerns.

**Comment by MathewMacDougall** [comment]
StandaloneSim doesn't yet support sending status messages

**Comment by jonathanlew** [comment]
Note that standalone simulator is broken until https://github.com/UBC-Thunderbots/Software/pull/1575 is merged in

**Review by LiCody — DISMISSED** [review]
LGTM pending testing concerns

**Comment by MathewMacDougall** [comment]
@jonathanlew can you merge #1575 now?

**Comment by garethellis0** [comment]
Mat's indicated he's going to run MatCI :tm: on this, so holding off until then.

**Comment by MathewMacDougall** [comment]
MatCI :tm: results

**Status:** Failed :x: :cry:

**Test**
Ran a robot with radio to generate robot and dongle errors, tried to see if they showed up in the Visualizer as expected

**Results**
* Did not see robot errors in the Visualizer. The robot was sending "SD card uninitialized", which doesn't match any ERROR_CODE enums and so doesn't get put into the TbotsRobotStatus proto and so doesn't make it to the Visualizer
* Did not see dongle errors in the Visualizer. The radio dongle was sending "EStop missing/broken" which won't match the "ESTOP_BROKEN" ErrorCode enum, and so won't be put into proto similar to the above.
* Dongle message also don't work because the `convertRobotStatusToTbotsRobotMsg` function only deals with robot messages, not dongle messages

**Comment by jonathanlew** [comment]
@MathewMacDougall Requesting another MatCI:tm: I've added support for dongle messages

**Comment by MathewMacDougall** [comment]
MatCI :tm: results 2 - Electric Boogaloo

**Status:** Passed :tm:

**Test**
Ran a robot with radio to generate robot and dongle errors, tried to see if they showed up in the Visualizer as expected

**Results**
* Error showed up as expected and eventually was removed once the error was resolved
* Found and fixed a bug in the RobotStatusTable GUI code unrelated to this PR

**Comment by jonathanlew** [comment]
Made the fixes that @MathewMacDougall found

**Review by MathewMacDougall — APPROVED** [review]

**Comment by jonathanlew** [comment]
@garethellis0 @akhilveeraghanta @LiCody @kelvinkoon please re-review

**Review by akhilveeraghanta — APPROVED** [review]
LGTM 🔥

**Review by kelvinkoon — APPROVED** [review]
LGTM!

**Review by garethellis0 — APPROVED** [review]
LGTM :+1: :tada:

**Pull request merged**
