### PR TITLE
Geom: Integrate intersects

### LINKED ISSUE #1168: Geom: Port over rest of `intersects` functions from `util`
### Description of the task
Port over the remaining `intersects` functions from old `util` to `new_geom`

### PR DESCRIPTION
**Pull request by jsn0716**
### Description

Integrate the new `intersects` and remove the old ones from `util`.

### Testing Done
Unit tests

### Resolved Issues
Resolves #1168

### Review Checklist

**_It is the reviewers responsibility to also make sure every item here has been covered_**

- [x] **Function & Class comments**: All function definitions (usually in the `.h` file) should have a javadoc style comment at the start of them. For examples, see the functions defined in `thunderbots/software/geom`. Similarly, all classes should have an associated Javadoc comment explaining the purpose of the class.
- [x] **Remove all commented out code**
- [x] **Remove extra print statements**: for example, those just used for testing
- [x] **Resolve all TODO's**: All `TODO` (or similar) statements should either be completed or associated with a github issue
- [ ] **Justify drops in code coverage**: If this PR results in a non-trivial drop in code coverage (a bot should post a coverage diagram as a comment), please justify why we can't test the code that's not covered.

### CODE REVIEW

**Review by garethellis0 — DISMISSED** [review]
Nice, these PR's make me super happy. :smile: LGTM :+1: :tada:

**Review by MathewMacDougall — DISMISSED** [review]
:+1: fantastic

**Comment by jsn0716** [comment]
Had do resolve some merge conflicts, need reapproval

**Review by MathewMacDougall — APPROVED** [review]
LGTM :+1:

**Review by garethellis0 — APPROVED** [review]
LGTM :+1: :tada:

**Pull request merged**
