### PR TITLE
Remove unneeded dynamic parameters

### LINKED ISSUE #1292: Remove unneeded DynamicParameters
### Description of the task

In preparation for upgrades to the DynamicParameter system, unused / unnecessary parameters should be removed from the configs so there is less to manage. We also want to make an effort to keep as few parameters as possible.

### Acceptance criteria

- [ ] Remove any unused or unnecessary parameters

### PR DESCRIPTION
**Pull request by MathewMacDougall**
### Description

Removed ununsed or unnecessary DynamicParameters from the configs so there is a bit less to manage and port during upcoming upgrades to the `DynamicParameter` system.

Also removed the `findOpenTriangles` and related functions used for indirect chip, since they are superseded by `findOpenCircles`

### Testing Done

code builds and tests pass

### Resolved Issues

resolves #1292 

### Review Checklist

**_It is the reviewers responsibility to also make sure every item here has been covered_**

- [x] **Function & Class comments**: All function definitions (usually in the `.h` file) should have a javadoc style comment at the start of them. For examples, see the functions defined in `thunderbots/software/geom`. Similarly, all classes should have an associated Javadoc comment explaining the purpose of the class.
- [x] **Remove all commented out code**
- [x] **Remove extra print statements**: for example, those just used for testing
- [x] **Resolve all TODO's**: All `TODO` (or similar) statements should either be completed or associated with a github issue
- [x] **Justify drops in code coverage**: If this PR results in a non-trivial drop in code coverage (a bot should post a coverage diagram as a comment), please justify why we can't test the code that's not covered.

### CODE REVIEW

**Review by akhilveeraghanta — COMMENTED** [review]
Its nice to see 800 lines yeeted out of the repo :cl: :e-mail: :a:N

When we had these values as dynamic parameters it was obvious that these values are arbitrary and the defaults are just a "good" value to have them at.

Now that we have removed them, should we justify those choices? 

```
 double min_defender_seperation_deg = 13.0;
 double max_defender_seperation_deg = 3.0;
 double min_ball_dist               = 1.0;
 double max_ball_dist               = 3.0;
```

For example, is it expected that any values like this are determined experimentally? Or is there a way to resolve these values based on robot radius or other constants that already exist?

**Comment by MathewMacDougall** [comment]
> For example, is it expected that any values like this are determined experimentally? Or is there a way to resolve these values based on robot radius or other constants that already exist?

This is a good point. Generally these are experimentally determined, since there's no "real" justification for the values when they are DynamicParams. I can add comments indicating these values are experimentally determined, but can't add much more context than that because there isn't really any.

Ideally we remove a lot of these "magic numbers" entirely by improving our algorithms or basing them on more concrete values like you suggested, but that's out of scope for this PR.

**Review by akhilveeraghanta — APPROVED** [review]
LGTM :fire:

**Review by jonathanlew — APPROVED** [review]
Looks good! :+1: (just a note to include removing indirect chip in the description)

**Review by garethellis0 — APPROVED** [review]
Nice, this makes me real happy. LGTM :+1: :tada:

**Pull request merged**
