### PR TITLE
Add SIGINT handler to radio_communication

### PR DESCRIPTION
**Pull request by henryymliu**
### Description

Redo of #588, see that for more info

### Review Checklist

**_It is the reviewers responsibility to also make sure every item here has been covered_**

- [ ] **Start of document comments**: each `.cpp` and `.h` file should have a comment at the start of it. See files in the `thunderbots/software/geom` folder for examples.
- [ ] **Function comments**: All function definitions (usually in the `.h` file) should have a javadoc style comment at the start of them. For examples, see the classes defined in `thunderbots/software/geom`
- [ ] **Remove all commented out code**
- [ ] **Remove extra print statements**: for example, those just used for testing
- [ ] **Resolve all TODO's**: All `TODO` (or similar) statements should either be completed or associated with a github issue
- [ ] **Justify drops in code coverage**: If this PR results in a non-trivial drop in code coverage (a bot should post a coverage diagram as a comment), please justify why we can't test the code that's not covered.

### CODE REVIEW

**Comment by henryymliu** [comment]
@MathewMacDougall sorry, need a rereview
The changes to `cherry_pick_tactic.cpp` were only a result of clang_format, btw

**Comment by henryymliu** [comment]
@garethellis0 any idea what's up with the codecov/patch test? `cherry_pick_tactic.cpp` was only changed as a result of `fix_formatting`

**Review by MathewMacDougall — APPROVED** [review]
LGTM :+1:

**Comment by garethellis0** [comment]
Sorry about that, had some ci failures on master, which meant coverage was not uploaded for the commit you had branched off of originally, so it couldn't do a diff. Should be all good now, but def let me know if this pops up again

**Pull request merged**
