### PR TITLE
LICENSE Change to GNU Lesser

### LINKED ISSUE #774: Use GNU license instead of MIT
### Description of the task

Change the license on our repo from MIT to GNU. This is a stricter license that forces anyone who uses our code to also be open source.

### Acceptance criteria

- [ ] Change the repo license to GNU

### PR DESCRIPTION
**Pull request by Solaris5959**
Changed from MIT License to GNU Affero General Public License v3.0

### Description

Switched the repository's license (In file `LICENSE`) from MIT to GNU Lesser General Public License v3.0. New license should force any party who modifies the source code found on the UBC-Thunderbots repo to be open-source.

### Length Justification

This is a legal document where all lines are required to cover all bases.

### Resolved Issues

Resolves #774 

### Review Checklist

**_It is the reviewers responsibility to also make sure every item here has been covered_**

- [ ] **Function & Class comments**: All function definitions (usually in the `.h` file) should have a javadoc style comment at the start of them. For examples, see the functions defined in `thunderbots/software/geom`. Similarly, all classes should have an associated Javadoc comment explaining the purpose of the class.
- [ ] **Remove all commented out code**
- [ ] **Remove extra print statements**: for example, those just used for testing
- [ ] **Resolve all TODO's**: All `TODO` (or similar) statements should either be completed or associated with a github issue
- [ ] **Justify drops in code coverage**: If this PR results in a non-trivial drop in code coverage (a bot should post a coverage diagram as a comment), please justify why we can't test the code that's not covered.

### CODE REVIEW

**Review by MathewMacDougall — DISMISSED** [review]
:+1: LGTM

**Review by garethellis0 — CHANGES_REQUESTED** [review]
Why GNU Affero GPL v3.0 instead of GNU Lesser GPL v3.0? Seems like Affero is better suited to actual websites then source code?

**Comment by MathewMacDougall** [comment]
Originally didn't seem like GNU Lesser had the clause that users of the code must also open source. @Solaris5959 can you confirm GNU Lesser is good then?

**Comment by Solaris5959** [comment]
I read through some of the documentation on both and Lesser seems to hit more of the marks that we want (ie. forcing open source when anything is modified from the original code base). Affero, as Gareth mentioned, seems to primarily be used for web applications. Overall, they aren't that different but lesser seems to be slightly better in most aspects. @MathewMacDougall

**Review by garethellis0 — APPROVED** [review]
LGTM :+1: :tada:

**Review by MathewMacDougall — APPROVED** [review]
Awesome, thanks for checking @Solaris5959 . You're the team lawyer now.

**Pull request merged**
