### PR TITLE
Added Length Justification To PR Template

### PR DESCRIPTION
**Pull request by garethellis0**
### Description
See title.

### Testing Done
NA

### Resolved Issues
NA

### Review Checklist
*(Please check every item to indicate your code complies with it (by changing `[ ]`->`[x]`). This will hopefully save both you and the reviewer(s) a lot of time!)*
***It is the reviewers responsibility to also make sure every item here has been covered***
- [x] **Start of document comments**: each `.cpp` and `.h` file should have a comment at the start of it. See files in the `thunderbots/software/geom` folder for examples.
- [x] **Function comments**: All function definitions (usually in the `.h` file) should have a javadoc style comment at the start of them. For examples, see the classes defined in `thunderbots/software/geom` 
- [x] **Remove all commented out code**
- [x] **Remove extra print statements**: for example, those just used for testing
- [x] **Resolve all TODO's**: All `TODO` (or similar) statements should either be completed or associated with a github issue
- [x] **Justify drops in code coverage**: If this PR results in a non-trivial drop in code coverage (a bot should post a coverage diagram as a comment), please justify why we can't test the code that's not covered.

***Feel free to make additions of things that we should be checking to this file if you think there's something missing!!!!***

### CODE REVIEW

**Review by akhilveeraghanta — DISMISSED** [review]
LGTM, 500 lines is a nice manageable chunk

**Review by MathewMacDougall — CHANGES_REQUESTED** [review]
Kinda playing devil's advocate here. I do support this change though).

1. Do both additions and deletions count towards the 500 lines? If my diff is +450 lines and -100 lines do I need to justify?
2. Should this maybe be a header along with `Description`, `Testing`? I think that's both more obvious (so people don't mindlessly check the boxes) and I think it makes just as much sense there? If the changes are small enough people can just leave it blank or write `N/A`, like how we do if tests are not changed.

**Comment by garethellis0** [comment]
@MathewMacDougall - good points!
1) Clarified that it's `additions + deletions`
2) Created a separate section

**Review by MathewMacDougall — APPROVED** [review]
LGTM :+1:

**Comment by garethellis0** [comment]
@akhilveeraghanta - could you review and approve?

**Review by akhilveeraghanta — APPROVED** [review]
LGTM, thought I hit add review, just hit comment

**Pull request merged**
