### PR TITLE
Add Bazel Test Output

### PR DESCRIPTION
**Pull request by jonathanlew**
### Description
We want bazel to output the results of our gtests

### Review Checklist

**_It is the reviewers responsibility to also make sure every item here has been covered_**

- [x] **Function & Class comments**: All function definitions (usually in the `.h` file) should have a javadoc style comment at the start of them. For examples, see the functions defined in `thunderbots/software/geom`. Similarly, all classes should have an associated Javadoc comment explaining the purpose of the class.
- [x] **Remove all commented out code**
- [x] **Remove extra print statements**: for example, those just used for testing
- [x] **Resolve all TODO's**: All `TODO` (or similar) statements should either be completed or associated with a github issue
- [x] **Justify drops in code coverage**: If this PR results in a non-trivial drop in code coverage (a bot should post a coverage diagram as a comment), please justify why we can't test the code that's not covered.

### CODE REVIEW

**Review by akhilveeraghanta — DISMISSED** [review]
LGTM :)

**Comment by jonathanlew** [comment]
I may have destroyed CI with this change... @garethellis0 any ideas with bazel test output

**Comment by garethellis0** [comment]
Try `--test_output=errors`?

**Comment by MathewMacDougall** [comment]
> Try `--test_output=errors`?

I believe the idea here is to enable it globally for everyone so people don't need to remember and get stuck wondering why tests aren't printing to `stdout`

**Comment by jonathanlew** [comment]
> > Try `--test_output=errors`?
> 
> I believe the idea here is to enable it globally for everyone so people don't need to remember and get stuck wondering why tests aren't printing to `stdout`

can we enable `errors` for CI and `all` for local? I'm going to do an experiment with just errors on CI now

**Comment by MathewMacDougall** [comment]
I think to do `all` for local and just `errors` for CI, the best way to do it is to leave `all` in the `bazelrc`, and manually pass the `errors` flag to the tests in the ci script. Whatever's in the `bazelrc` will likely be everyone's local default since I don't expect people to be passing flags locally.

**Comment by jonathanlew** [comment]
Ready for re-review

**Review by MathewMacDougall — APPROVED** [review]
LGTM :+1:

**Review by akhilveeraghanta — APPROVED** [review]
LGTM

**Pull request merged**
