### PR TITLE
BugFix: Unsigned Negative Comparisons In For Loops

### LINKED ISSUE #934: Fix Unsigned Negative Comparisons In For Loops
### Description of the task
In #931, we found that #858 introduced unsigned negative comparisons in for loops. This caused a bug in drawNavigator. These issue is to fix any other similar bugs.

### Acceptance criteria

- [ ] Find such bugs
- [ ] Fix such bugs

### PR DESCRIPTION
**Pull request by jonathanlew**
### Description
Found 2 bugs that had Negative Comparisons In For Loops, and fixed them

### Testing Done
regression tests

### Resolved Issues
Resolves #934

### Review Checklist

**_It is the reviewers responsibility to also make sure every item here has been covered_**

- [x] **Function & Class comments**: All function definitions (usually in the `.h` file) should have a javadoc style comment at the start of them. For examples, see the functions defined in `thunderbots/software/geom`. Similarly, all classes should have an associated Javadoc comment explaining the purpose of the class.
- [x] **Remove all commented out code**
- [x] **Remove extra print statements**: for example, those just used for testing
- [x] **Resolve all TODO's**: All `TODO` (or similar) statements should either be completed or associated with a github issue
- [x] **Justify drops in code coverage**: If this PR results in a non-trivial drop in code coverage (a bot should post a coverage diagram as a comment), please justify why we can't test the code that's not covered.

### CODE REVIEW

**Review by scveloso — APPROVED** [review]
LGTM, sorry for missing these in #858

**Comment by garethellis0** [comment]
@scveloso - how'd CI pass in #858 if these were in? Shouldn't the compiler have thrown an error?

**Review by garethellis0 — APPROVED** [review]
LGTM :+1: :tada:

**Comment by scveloso** [comment]
> @scveloso - how'd CI pass in #858 if these were in? Shouldn't the compiler have thrown an error?

@garethellis0  I think this is a bug during runtime if size() is 0, then the -1 would make it UINT_MAX since we now do unsigned comparisons in for loops.

**Comment by garethellis0** [comment]
Whoops, you're totally right. Sorry, should've read that more carefully.

**Pull request merged**
