### PR TITLE
Add UI for parameter control

### PR DESCRIPTION
**Pull request by qgolsteyn**
### Description

This PR introduces the ability to control the ROS param server via the Corner Kick UI. It adds resizeable panes in the sidebar, more basic layout elements, and revamps the param fetching and updating logic to be more generalised, making this PR quite large.

### Testing Done

Manual testing

### Resolved Issues

Resolve #541 

### Length Justification

UI upgrades + param logic changes made this PR large

### Review Checklist

**_It is the reviewers responsibility to also make sure every item here has been covered_**

- [x] **Start of document comments**: each `.cpp` and `.h` file should have a comment at the start of it. See files in the `thunderbots/software/geom` folder for examples.
- [x] **Function comments**: All function definitions (usually in the `.h` file) should have a javadoc style comment at the start of them. For examples, see the classes defined in `thunderbots/software/geom`
- [x] **Remove all commented out code**
- [x] **Remove extra print statements**: for example, those just used for testing
- [x] **Resolve all TODO's**: All `TODO` (or similar) statements should either be completed or associated with a github issue
- [x] **Justify drops in code coverage**: If this PR results in a non-trivial drop in code coverage (a bot should post a coverage diagram as a comment), please justify why we can't test the code that's not covered.

### CODE REVIEW

**Comment by qgolsteyn** [comment]
image

**Comment by qgolsteyn** [comment]
Still missing refbox due to the lack of options

**Review by MathewMacDougall — APPROVED** [review]
Restarted CI to fix unrelated failures. Focusing on functional changes, and the code all looks reasonable. Tested everything I could (to the AI's current capability) for now, and it looks good! As we add some final AI control features (like listening to refbox) I'll re-test this and we can come back to it if necessary, mostly regarding "DEFAULT" values

**Comment by qgolsteyn** [comment]
Make an issue when this needs revisiting!

**Pull request merged**
