### PR TITLE
Initial move of Particle Filter code

### LINKED ISSUE #198: Implement Particle Filter
**Is your feature request or enhancement related to a problem? What specifically could be better? Please describe.**
In order to handle noise in the data we receive for the ball's location, we need a filter to find the "real" ball in the data.

**Describe the solution you'd like**
In our old code we used a Particle Filter. This filter should be ported into the new system. The code should not require too much modifying, but will need proper tests. The old particle filter code can be found in `software/geom/particle/`

**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by orayasrimokla**
### Description
*Transfer and implementation of the old particle filter to find the "real" ball in the received data*

### Testing Done
*WIP as the file has to be modified to fit the new parameter file ROS uses*

### Resolved Issues

Resolves #198 

### Review Checklist
*(Please check every item to indicate your code complies with it (by changing `[ ]`->`[x]`). This will hopefully save both you and the reviewer(s) a lot of time!)*
***It is the reviewers responsibility to also make sure every item here has been covered***
- [x] **Start of document comments**: each `.cpp` and `.h` file should have a comment at the start of it. See files in the `thunderbots/software/geom` folder for examples.
- [x] **Function comments**: All function definitions (usually in the `.h` file) should have a javadoc style comment at the start of them. For examples, see the classes defined in `thunderbots/software/geom` 
- [x] **Remove all commented out code**
- [x] **Remove extra print statements**: for example, those just used for testing
- [x] **Resolve all TODO's**: All `TODO` (or similar) statements should either be completed or associated with a github issue
- [x] **Justify drops in code coverage**: If this PR results in a non-trivial drop in code coverage (a bot should post a coverage diagram as a comment), please justify why we can't test the code that's not covered.

### CODE REVIEW

**Review by MathewMacDougall — COMMENTED** [review]
You almost got it. This should make things compile and then we can start changing the values to "proper" parameters

**Review by MathewMacDougall — CHANGES_REQUESTED** [review]
Two quick things to change:
1. Run the formatting script (formatting is failing in CI)
2. Can we put these files in `network_input/filter` since these files are specific to the Ball Filter and are not a generic Particle Filter.

**Review by MathewMacDougall — DISMISSED** [review]
LGTM :+1: :tada:

**Comment by garethellis0** [comment]
@MathewMacDougall - fair enough, but what exactly should we be reviewing for here then?

**Comment by MathewMacDougall** [comment]
@garethellis0 Nothing much actually, since this is mostly just moving code. Should just be able to be approved.

**Review by MathewMacDougall — APPROVED** [review]

**Pull request merged**
