### PR TITLE
Remove placeholder navigator

### PR DESCRIPTION
**Pull request by jonathanlew**
### Description
Remove placeholder navigator

### Testing Done
none needed

### Resolved Issues
#859

### Related Issues
#769

### Review Checklist

**_It is the reviewers responsibility to also make sure every item here has been covered_**

- [x] **Function & Class comments**: All function definitions (usually in the `.h` file) should have a javadoc style comment at the start of them. For examples, see the functions defined in `thunderbots/software/geom`. Similarly, all classes should have an associated Javadoc comment explaining the purpose of the class.
- [x] **Remove all commented out code**
- [x] **Remove extra print statements**: for example, those just used for testing
- [x] **Resolve all TODO's**: All `TODO` (or similar) statements should either be completed or associated with a github issue
- [x] **Justify drops in code coverage**: If this PR results in a non-trivial drop in code coverage (a bot should post a coverage diagram as a comment), please justify why we can't test the code that's not covered.

### CODE REVIEW

**Review by akhilveeraghanta — APPROVED** [review]
LGTM

**Review by garethellis0 — APPROVED** [review]
LGTM :+1: :tada:

**Comment by jonathanlew** [comment]
@MathewMacDougall codeowner review required?

**Comment by garethellis0** [comment]
Hmmm my review should have covered that. @MathewMacDougall please don't review, gonna try to fix this.

**Comment by garethellis0** [comment]
Fix for codeowners is here: https://github.com/UBC-Thunderbots/Software/pull/862, could we merge that and then use this PR to check it worked?

**Pull request merged**
