### PR TITLE
Use optional_pointer.value() instead of *optional_pointer

### LINKED ISSUE #1911: Use optional_pointer.value() instead of *optional_pointer
### Description of the task
As mentioned in https://github.com/UBC-Thunderbots/Software/pull/1896#discussion_r563346187, `optional_pointer.value()` makes an [additional check](https://en.cppreference.com/w/cpp/utility/optional/value) to throw an exception if the `optional_pointer` doesn't contain a value. We should make this replacement wherever we use std::optional. We should also replace `optional_pointer->` with `optional_pointer.value()`

### Acceptance criteria

- [ ] Use optional_pointer.value() instead of *optional_pointer, the easiest path is to look for variables that end in "_opt" and fix those. Don't forget to replace `->`

### PR DESCRIPTION
**Pull request by piramonpan**
### Description

    Change from using *optional_pointer and optional_pointer-> to using optional_pointer.value(). T

### Resolved Issues
resolved #1911 
resolved #2391 (comment)

### Review Checklist

**_It is the reviewers responsibility to also make sure every item here has been covered_**

- [x] **Function & Class comments**: All function definitions (usually in the `.h` file) should have a javadoc style comment at the start of them. For examples, see the functions defined in `thunderbots/software/geom`. Similarly, all classes should have an associated Javadoc comment explaining the purpose of the class.
- [x] **Remove all commented out code**
- [x] **Remove extra print statements**: for example, those just used for testing
- [x] **Resolve all TODO's**: All `TODO` (or similar) statements should either be completed or associated with a github issue
- [x] **Justify drops in code coverage**: If this PR results in a non-trivial drop in code coverage (a bot should post a coverage diagram as a comment), please justify why we can't test the code that's not covered.

### CODE REVIEW

**Review by jonathanlew — CHANGES_REQUESTED** [review]
Please merge in upstream/master (i.e. `git fetch upstream`, then `git merge upstream/master`). I think you're missing a couple [optional pointer]-> in software/ai/hl/stp/tactic/shadow_enemy/shadow_enemy_fsm.h and software/ai/passing/cost_function.cpp

**Review by JoshuaWu7 — DISMISSED** [review]
LGTM, nothing else to add except above comments

**Review by jonathanlew — APPROVED** [review]
LGTM!

**Review by Bvasilchikov — APPROVED** [review]
lgtm!

**Comment by jonathanlew** [comment]
Please fill out the description and resolved issue: https://github.com/UBC-Thunderbots/Software/pull/2391#issue-1097050471

**Pull request merged**
