### PR TITLE
Implement pseudo-class Matrix library and fix bugs

### PR DESCRIPTION
**Pull request by EvanMorcom**
### Description
Implement pseudo-class Matrix Library for firmware and fix existing bugs

### Testing Done
Unit tests for all functions

### Resolved Issues
NA
### Length Justification
NA
### Review Checklist
- [X] **Function & Class comments**: All function definitions (usually in the `.h` file) should have a javadoc style comment at the start of them. For examples, see the functions defined in `thunderbots/software/geom`. Similarly, all classes should have an associated Javadoc comment explaining the purpose of the class.
- [X] **Remove all commented out code**
- [X] **Remove extra print statements**: for example, those just used for testing
- [X] **Resolve all TODO's**: All `TODO` (or similar) statements should either be completed or associated with a github issue
- [X] **Justify drops in code coverage**: If this PR results in a non-trivial drop in code coverage (a bot should post a coverage diagram as a comment), please justify why we can't test the code that's not covered.

### CODE REVIEW

**Comment by akhilveeraghanta** [comment]
@EvanMorcom do you have time to have a quick call with @jonathanlew and I, we would like to catch up and see where this project stands as a whole

**Comment by EvanMorcom** [comment]
Yeah sure :+1:

**Comment by EvanMorcom** [comment]
This is kinda independent of anything else though, the matrix library didn't even work before.

This PR addressed all of the comments from the one that was closed last week.

**Comment by akhilveeraghanta** [comment]
@EvanMorcom @jonathanlew can you guys fill this out: https://www.when2meet.com/?10346519-qHueE

**Review by jonathanlew — COMMENTED** [review]
looks good, is this code being used anywhere?

**Review by jonathanlew — APPROVED** [review]
Approved, but would like to get a meeting with you, though @EvanMorcom, can we organize something through slack?

**Comment by EvanMorcom** [comment]
@jonathanlew @akhilveeraghanta Looks like we can meet tonight or anytime tomorrow. Lemme know what time (in Vancouver time) :+1:

**Comment by akhilveeraghanta** [comment]
@EvanMorcom  lets meet at 4pm tmrw vancouver time, here is the meeting link ([meet.google.com/osq-aqby-tzo](meet.google.com/osq-aqby-tzo))

tmr -> Sat Nov 21

**Review by akhilveeraghanta — APPROVED** [review]

**Pull request merged**
