### PR TITLE
Added "done" criteria to issue templates

### PR DESCRIPTION
**Pull request by MathewMacDougall**
### Description
This PR updates the issue templates to include a section that details what must be completed for an issue to be considered "done"

### Testing Done
*Outline any testing that was done for these changes. This could be unit tests, integration tests, etc.*
N/A

### Resolved Issues
*Link any issues that this PR resolved. Eg `resolves #1, #2, and #5` (note that they MUST be specified like this so Github can automatically close them then this PR merges)*
N/A

### Length Justification

N/A

### Review Checklist
*(Please check every item to indicate your code complies with it (by changing `[ ]`->`[x]`). This will hopefully save both you and the reviewer(s) a lot of time!)*
***It is the reviewers responsibility to also make sure every item here has been covered***
- [x] **Start of document comments**: each `.cpp` and `.h` file should have a comment at the start of it. See files in the `thunderbots/software/geom` folder for examples.
- [x] **Function comments**: All function definitions (usually in the `.h` file) should have a javadoc style comment at the start of them. For examples, see the classes defined in `thunderbots/software/geom` 
- [x] **Remove all commented out code**
- [x] **Remove extra print statements**: for example, those just used for testing
- [x] **Resolve all TODO's**: All `TODO` (or similar) statements should either be completed or associated with a github issue
- [x] **Justify drops in code coverage**: If this PR results in a non-trivial drop in code coverage (a bot should post a coverage diagram as a comment), please justify why we can't test the code that's not covered.

***Feel free to make additions of things that we should be checking to this file if you think there's something missing!!!!***

### CODE REVIEW

**Review by garethellis0 — DISMISSED** [review]
LGTM 👍 🎉

**Review by garethellis0 — DISMISSED** [review]
LGTM 👍 🎉

**Comment by qgolsteyn** [comment]
Sorry @garethellis0 didn't want to get you to review stuff so many times... but you'll have to do it again

**Review by qgolsteyn — DISMISSED** [review]
LGTM :+1:

**Comment by qgolsteyn** [comment]
Mathew is sitting beside me and also approves

**Comment by garethellis0** [comment]
Mathew approves his own PR? I damn well hope he does.

**Review by garethellis0 — COMMENTED** [review]
- What's the difference between a feature request and a ticket? Could we get rid of the feature request? Actually, can we get rid of the bug report as well? Seems like a ticket can encompass both?

**Comment by MathewMacDougall** [comment]
The high-level idea would be that feature requests are for "new" work or features, eg. a new path planning algorithm or a new datastructure. "ticket" would cover most tickets that are general work, enhancements, or maintenance. Bug reports are for bugs/incorrect behavior that needs to be fixed.

I think the idea of the different prompts would be to help get more targeted information from people. That being said, it's only useful if people use the templates correctly. I'm not super opposed to just simplifying this to a single template. @qgolsteyn ?

**Comment by MathewMacDougall** [comment]
Removed  Bug Report and Feature Request templates. Let's try wrap this up tonight.

**Review by qgolsteyn — APPROVED** [review]
LGTM :+1:

**Review by garethellis0 — APPROVED** [review]
LGTM :+1: :tada:

**Pull request merged**
