### PR TITLE
Add Dribble Action

### PR DESCRIPTION
**Pull request by henryymliu**
### Description

Removed `final_speed` from all instances of dribble, added DribbleAction (almost the same as MoveAction) with unit test.
Also changed firmware to actually use the dribbler rpm value passed in.

### Testing Done

Field tested, ran unit tests.

### Length Justification

N/A

### Review Checklist

**_It is the reviewers responsibility to also make sure every item here has been covered_**

- [x] **Start of document comments**: each `.cpp` and `.h` file should have a comment at the start of it. See files in the `thunderbots/software/geom` folder for examples.
- [x] **Function comments**: All function definitions (usually in the `.h` file) should have a javadoc style comment at the start of them. For examples, see the classes defined in `thunderbots/software/geom`
- [x] **Remove all commented out code**
- [x] **Remove extra print statements**: for example, those just used for testing
- [x] **Resolve all TODO's**: All `TODO` (or similar) statements should either be completed or associated with a github issue
- [x] **Justify drops in code coverage**: If this PR results in a non-trivial drop in code coverage (a bot should post a coverage diagram as a comment), please justify why we can't test the code that's not covered.

### CODE REVIEW

**Review by garethellis0 — COMMENTED** [review]
This all looks pretty good to me, my only question is what was the logic behind removing the final speed?

**Comment by henryymliu** [comment]
`final_speed` is not used in the firmware, and there isn't enough space in `params` to fit it. In fact, the current AI primitive implementation has five elements in `params` because of final_speed, which is not correct (this is probably due to an erroneous spec).

**Review by garethellis0 — APPROVED** [review]
Well then, in that case this LGTM :+1: :tada:

**Comment by garethellis0** [comment]
(may want to wait for @MathewMacDougall to review though)

**Review by MathewMacDougall — APPROVED** [review]
LGTM :+1:

**Pull request merged**
