### PR TITLE
FSM diagram generator

### LINKED ISSUE #1927: Add script to visualize Tactic FSMs
### Description of the task
There is a [plantuml integration example](https://boost-ext.github.io/sml/examples.html#plant-uml-integration) that we should adapt into a script/genrule to automatically generate Tactic FSMs. The existing code isn't the prettiest, so we should see what we can do to make it look nicer

### Acceptance criteria

- [ ] nice looking plantuml diagrams
- [ ] automatic generation

### PR DESCRIPTION
**Pull request by williamckha**
### Description

Added Python script for generating FSM diagrams. The script has to be manually run: from `Software` directory run `./src/software/ai/fsm_diagram_generator.py`

The script searches for FSM header files and parses through their transition table, creating a [Mermaid text definition for a state diagram](https://mermaid.js.org/syntax/stateDiagram.html) which is outputted to `docs/fsm-diagrams.md`. GitHub automatically renders Mermaid diagrams in its Markdown viewer (make sure to display rich diff when looking at changed files).

The [PlantUML data dumping example](https://boost-ext.github.io/sml/examples.html#plant-uml-integration) doesn't produce pretty results due to guards/actions being anonymized lamdas + the code is quite terse, so this script might be a simpler hack

### Resolved Issues

Resolves #1927

### Review Checklist

**_It is the reviewers responsibility to also make sure every item here has been covered_**

- [x] **Function & Class comments**: All function definitions (usually in the `.h` file) should have a javadoc style comment at the start of them. For examples, see the functions defined in `thunderbots/software/geom`. Similarly, all classes should have an associated Javadoc comment explaining the purpose of the class.
- [x] **Remove all commented out code**
- [x] **Remove extra print statements**: for example, those just used for testing
- [x] **Resolve all TODO's**: All `TODO` (or similar) statements should either be completed or associated with a github issue

### CODE REVIEW

**Review by itsarune — APPROVED** [review]
awesome!

**Review by itsarune — CHANGES_REQUESTED** [review]
actually, on second look, could you integrate this into the BUILD file so that we can invoke it with the tbots test runner

**Review by nimazareian — COMMENTED** [review]
This is super cool! Great job figuring it out. I know that I will definitely be looking back on the generated diagrams.
(in the future) It would be cool to have this integrated with GH Actions to automatically run every time someone changes one of the FSMs.
An idea that we'd also discussed previously is to add these diagrams to a new widget in Thunderscope, and visualize the state transitions in real time (e.g. if in `PlaySelectionFSM` we're at the `Halt` state, then we would highlight that in a different color, then if we transition to the `Stop` state, the diagram automatically updates to highlight the `Stop` state. This would basically be a more powerful version of the existing `PlayInfoWidget`. Though this is a nice to have and not a high priority. But it's something to consider.

**Comment by williamckha** [comment]
Tried using `py_binary` in the BUILD file but running into some issues since bazel bundles up the script in a temp dir and runs it from there, so the script can't find the Software directory and scrape through the repo's files. I agree that we should probably integrate this with our CI so that we don't need to invoke the script manually. I've added a new workflow which will generate new diagrams and open a PR whenever it detects changes to FSMs (hopefully it works)

> An idea that we'd also discussed previously is to add these diagrams to a new widget in Thunderscope...

This would be a neat feature!

**Review by nimazareian — APPROVED** [review]
🔥

**Review by germchow — APPROVED** [review]
Diagrams look great

**Review by itsarune — APPROVED** [review]
I tried some things out locally, but to get it to work with bazel would require writing a genrule, which is more work than is necessary here

nice work!

**Pull request merged**
