### PR TITLE
WIP: Inject Enemy Capability Parameters

### LINKED ISSUE #1139: Dependency Inject Enemy Capability Parameters
### Description of the task

See #960 for more details

The `EnemyCapabilityConfig` parameters should be changed to use dependency injection, by passing in the `EnemyCapabilityConfig` objects to places that need it. (tip: `grep` or search for usages of `EnemyCapabilityConfig` to find where the data config needs to go). Replace and remove the singleton usages of the parameters (they look like `Util::DynamicParameters::etc`)

### Acceptance criteria

- [ ] Inject the EnemyCapabilityConfig parameters into all places needed

### PR DESCRIPTION
**Pull request by HaomiaoZ**
### Description

Inject Enemy Capability Config as parameters to the constructor of `DefensePlay` and `EnemyFreekickPlay`

### Testing Done

Bazel build has error currently. There are no tests associated with those two plays.

### Resolved Issues

resolves #1139 

### Length Justification

The length is shorter than 500 lines

### Review Checklist

**_It is the reviewers responsibility to also make sure every item here has been covered_**

- [x] **Function & Class comments**: All function definitions (usually in the `.h` file) should have a javadoc style comment at the start of them. For examples, see the functions defined in `thunderbots/software/geom`. Similarly, all classes should have an associated Javadoc comment explaining the purpose of the class.
- [x] **Remove all commented out code**
- [x] **Remove extra print statements**: for example, those just used for testing
- [x] **Resolve all TODO's**: All `TODO` (or similar) statements should either be completed or associated with a github issue
- [x] **Justify drops in code coverage**: If this PR results in a non-trivial drop in code coverage (a bot should post a coverage diagram as a comment), please justify why we can't test the code that's not covered.

### CODE REVIEW

**Comment by HaomiaoZ** [comment]
@akhilveeraghanta @MathewMacDougall 
I added the parameters for `EnemyCapabilityConfig` to the constructor of `DefensePlay` and `EnemyFreekickPlay`. Please let me know whether I understand and doing the dependency injection correctly. 

If I am doing this right, then there is a problem with `PlayFactory` since I change the default constructor to take parameters, and in `PlayFactory`, the play does not take any argument in the template. I was wondering what would be a good way to solve this.

errorplayfactory

**Comment by garethellis0** [comment]
Oh man, Mat and I were just talking about this issue the other day....... we might need to pass the entire AI configuration (or maybe a sub-config of that, not sure off the top of my head) into the constructor for the `PlayFactory`, so that the `PlayFactory` can pass the requisite configs into each play as needed. @akhilveeraghanta @MathewMacDougall - would still like to hear your thoughts on this.

**Comment by akhilveeraghanta** [comment]
I think we would have to pass in the top level `PlayConfig` to all plays, the only thing we know is the type of the play which isn't enough to get the right config.

Just a thought (not sure how feasible) what if we implemented a `getConfigFromString()` function which is also generated, should be easy (I think) because we know which configs map to which `getTestConfig()` function. It would be a mapping from the play's name string to its repsective `getBlankPlayConfig` function.

So during registration we could do  `...getPlayConfig()->getConfigFromString(T.getName())` to get the most specific config we would want, to avoid passing in `PlayConfig` to all plays

Edit: `T.getName()` won't work but if we make `getName() static` I think we can do `T::getName()`

**Comment by garethellis0** [comment]
> only thing we know is the type of the play which isn't enough to get the right config.

why not? Can't we just say that `ShootOrPassPlay` gets the `PlayConfig.ShootOrPassPlayConfig`? We'd need to define the mapping manually in the factory, but it's not too bad I think?

>  Just a thought (not sure how feasible) what if we implemented a getConfigFromString() function which is also generated, should be easy (I think) because we know which configs map to which getTestConfig() function. It would be a mapping from the play's name string to its repsective getBlankPlayConfig function.

I'd really really really like to avoid doing mappings from strings. As things stand now, everything is compile-time enforced, which is a really nice property to have.

**Comment by akhilveeraghanta** [comment]
was thinking string mapping because we could auto-generate and avoid storing a manual mapping but that can get real gross real fast

And yeah manually mapping would solve it, but that means every time we add a play we have to update the factory, which defeats the purpose of the "auto registering" play factory, but realistically not all plays have configs, so that makes the most sense.

**Comment by garethellis0** [comment]
Yeah, I mean we still need to so some manual work in making sure the strings match up and all that, I'd rather have our manual work compile-time checked.

**Comment by MathewMacDougall** [comment]
Yea I would prefer manual mapping in the factory to strings, but Akhil makes a good point that you lose a bit of the niceness of auto-registering plays.

However looking ahead to where we may want the concept of playbooks, we may lose that benefit anyway. I think we realistically add / remove plays so infrequently it's not a huge deal.

So for now I'd agree with passing the `PlayConfig` or similar config to the `PlayFactory` and having the factory responsible for giving the right play-specific config

**Comment by HaomiaoZ** [comment]
Based on the comments, I guess the action now is to do a manual mapping in the factory by passing  `PlayConfig` to `PlayFactory`. I am not too sure what do you guys mean by manual mapping, could someone explain that?

**Comment by MathewMacDougall** [comment]
@HaomiaoZ So the factory stuff is trickier than we thought, and I'd like to think about it more. I also realized this work will likely conflict with #1143 , so in the meantime would you mind putting this on hold and working on something else?

#819 would be a good candidate so we can start testing more strategy now that simulation is also in theory close to done.

**Comment by HaomiaoZ** [comment]
sure I can work on #819

**Comment by MathewMacDougall** [comment]
Great, sorry for the switching. Can you close this PR for now then?

**Comment by HaomiaoZ** [comment]
For sure, I will close the PR. No worries.

**Pull request closed without merging**
