### PR TITLE
Thunderloop Safety Updates V2

### PR DESCRIPTION
**Pull request by itsarune**
### Description

Thunderloop Safety Updates V2

- Fixes endless motor reset problem (that I may nor may not have created)
- Resets motor when the faults disables drive
- Limits drive motors to 2.5 A (doesn't seem to impact drive motors during basic field testing)

### Testing Done

some field testing done
- observed no endless resets
- motor reset timeout threshold testing still pending

### Review Checklist

**_It is the reviewers responsibility to also make sure every item here has been covered_**

- [ ] **Function & Class comments**: All function definitions (usually in the `.h` file) should have a javadoc style comment at the start of them. For examples, see the functions defined in `thunderbots/software/geom`. Similarly, all classes should have an associated Javadoc comment explaining the purpose of the class.
- [ ] **Remove all commented out code**
- [ ] **Remove extra print statements**: for example, those just used for testing
- [ ] **Resolve all TODO's**: All `TODO` (or similar) statements should either be completed or associated with a github issue

### CODE REVIEW

**Comment by PhilD71** [comment]
Have you tested with example play on a Robot? Henry was saying yesterday that he was having issues specifically when running example play or field tests, not in Robot Diagnostics

**Comment by itsarune** [comment]
Yes on Saturday we ran passing and example play on aimbot with this. I think killit too.

**Review by nimazareian — DISMISSED** [review]
The changes look okay to me, though I do lack a bit of context and it should definitely be tested on the robots. 
Curious why the motors were resetting a bunch with the previous version of thunderloop?

**Review by LiCody — COMMENTED** [review]
so endless resetting was due to a logic error and now it will properly crash if it resets? LGTM pending testing

**Review by PhilD71 — DISMISSED** [review]
Been using new thunderloop in the mezz today to test and it works great

**Comment by itsarune** [comment]
@nimazareian in previous thunderloop, I cleared the RESET flag for only the motors that had the RESET flag in their cached faults. Problem was that I cleared the cache before driving the signal to clear the RESET signal.

This version of thunderloop will clear RESET for all motors regardless of whether the RESET fault was previously cached.

**Comment by nimazareian** [comment]
> @nimazareian in previous thunderloop, I cleared the RESET flag for only the motors that had the RESET flag in their cached faults. Problem was that I cleared the cache before driving the signal to clear the RESET signal.
> 
> This version of thunderloop will clear RESET for all motors regardless of whether the RESET fault was previously cached.

Interesting. so it wasnt clearing the RESET register? (the cache was erased before being used to clear it?!)

Also the PR looks good, just pending CI. We should try to get this in and onto all working robots so it's tested further!

**Comment by Bvasilchikov** [comment]
@nimazareian 

The problem was the same check for a motor reset was called twice. During `poll()`, if there's a reset, then that will make `hasMotorReset()` return true, which then calls` setup()` which clears the cache the before the another call to `hasMotorReset()`, which now fails and so the reset isn't written out to the register.

**Review by Bvasilchikov — DISMISSED** [review]
lgtm!

**Comment by itsarune** [comment]
pre-commit.ci run

**Review by nimazareian — APPROVED** [review]

**Review by williamckha — APPROVED** [review]

**Pull request merged**
