### PR TITLE
[Thunderscope] Replace sliders with text/number boxes in parameter tree

### LINKED ISSUE #2987: [Thunderscope] Replace sliders with text/number boxes in parameter tree
### Description of the task

[Dynamic parameters](https://github.com/UBC-Thunderbots/Software/blob/master/docs/software-architecture-and-design.md#dynamic-parameters) let us change values in our code at runtime so that we can tweak our strategy/gameplay very quickly without having to recompile the code. We interact with our dynamic parameters through Thunderscope using the [`ParameterTree` widget](https://pyqtgraph.readthedocs.io/en/latest/api_reference/parametertree/index.html). 

Currently, integer and double parameters in our tree have their type set to "slider". The slider is finicky to use and setting values with the slider is imprecise. We want to use a text/number box instead of a slider so that we can directly type in the parameter value.

### Acceptance criteria

- [x] Change the parameter type from "slider" to "int" and "float" in the [`__create_int_parameter_writable`](https://github.com/UBC-Thunderbots/Software/blob/448661a55e28d885788d0a73332db1c68ec37375/src/software/thunderscope/common/proto_parameter_tree_util.py#L30) and [`__create_double_parameter_writable`](https://github.com/UBC-Thunderbots/Software/blob/448661a55e28d885788d0a73332db1c68ec37375/src/software/thunderscope/common/proto_parameter_tree_util.py#L60) helper functions
- [x] Update the function docstrings
- [x] Run Thunderscope and make sure numeric parameters in the tree work as expected (can set value, input is clamped to limits, etc.)

### PR DESCRIPTION
**Pull request by Andrewyx**
### Description

Changed the sliders within Thunderscope into text boxes. Allows for exact int or float inputs.

### Testing Done

Ran Thunderscope, works without issue and changes appear.

### Resolved Issues

Resolves #2987

### Review Checklist

**_It is the reviewers responsibility to also make sure every item here has been covered_**

- [x] **Function & Class comments**: All function definitions (usually in the `.h` file) should have a javadoc style comment at the start of them. For examples, see the functions defined in `thunderbots/software/geom`. Similarly, all classes should have an associated Javadoc comment explaining the purpose of the class.
- [x] **Remove all commented out code**
- [x] **Remove extra print statements**: for example, those just used for testing
- [x] **Resolve all TODO's**: All `TODO` (or similar) statements should either be completed or associated with a github issue

### CODE REVIEW

**Review by williamckha — APPROVED** [review]
LGTM

**Comment by williamckha** [comment]
Also could you rename this PR to something more descriptive? I'd just copy the issue name

**Review by raymond212 — APPROVED** [review]
LGTM 👍

**Review by nimazareian — APPROVED** [review]
💯

**Comment by RandoNandoz** [comment]
Nice commit! :)

**Pull request merged**
