### PR TITLE
Added Proper Exception Handling For SSL Backend Setup

### PR DESCRIPTION
**Pull request by garethellis0**
### Description
Added proper exception handling so that when stuff happens in the process of setting up the network connection to receive vision packets, we get a clean error message instead of just not handling the exception.

Before:
```
terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::system::system_error> >'
  what():  bind: Address already in use
[1]    10848 abort (core dumped)  rosrun thunderbots backend_input
```

After:
```
An error occured while setting up the SSL Vision Client: 
Throw location unknown (consider using BOOST_THROW_EXCEPTION)
Dynamic exception type: boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::system::system_error> >
std::exception::what: bind: Address already in use
```

(not a _huge_ improvement, but at least we're properly catching the exception now)

### Testing Done
Caused an exception by running two instances of the `backend_input` node. The first binds to the port, so that the second one can't, resulting in an exception about not being able to bind the to port. Exception handling produced expected error message.

### Resolved Issues
NA

### Review Checklist
*(Please check every item to indicate your code complies with it (by changing `[ ]`->`[x]`). This will hopefully save both you and the reviewer(s) a lot of time!)*
***It is the reviewers responsibility to also make sure every item here has been covered***
- [x] **Start of document comments**: each `.cpp` and `.h` file should have a comment at the start of it. See files in the `thunderbots/software/geom` folder for examples.
- [x] **Function comments**: All function definitions (usually in the `.h` file) should have a javadoc style comment at the start of them. For examples, see the classes defined in `thunderbots/software/geom` 
- [x] **Remove all commented out code**
- [x] **Remove extra print statements**: for example, those just used for testing
- [x] **Resolve all TODO's**: All `TODO` (or similar) statements should either be completed or associated with a github issue

***Feel free to make additions of things that we should be checking to this file if you think there's something missing!!!!***

### CODE REVIEW

**Comment by garethellis0** [comment]
@akhilveeraghanta - you ran into this originally. What should we have in the exception handling to make it more clear what went wrong?

(Note that boost just throws a generic exception, we can't tell by it's type that it's a "could not bind to address" exception)

**Review by MathewMacDougall — COMMENTED** [review]
LGTM and seems like a reasonable change to make debugging easier and clear up confusion.

Regarding your point about making this more specific/clear this is a socket issue, could we just handle the exception at a lower level? I'm assuming the following line in `src/thunderbots/software/backend_input/networking/ssl_vision_client.cpp` would throw the exception:
`socket_.bind(listen_endpoint);` (line 9)

If we try/catch here then we can be sure the exception was thrown to a failed bind and accordingly give a more descriptive message.

**Comment by garethellis0** [comment]
I thought about that, but I wasn't sure what type of exception we would throw up. Also, because boost just uses a generic exception type, even if we try-catch around one line, we can't guarantee that the issue was the port being in use, so the best we could do would be "there was an issue binding to the port when trying to connect to the SSL vision server" (or something similar), which I don't think is that much more descriptive then what's in there now.

**Comment by MathewMacDougall** [comment]
Fair enough. We could always suggest the port-binding in the message, a la ""there was an issue binding to the port when trying to connect to the SSL vision server. This may be due to another instance of backend_input running and using the port already"

**Comment by garethellis0** [comment]
Hmm, yeah, I thought about that, but if we catch it at the top level, then we don't really know that, so we would have to try-catch in `ssl_vision_client.cpp`, but then what exception would we pass up to top level? (Not a rhetorical question, open to any suggestions)

**Comment by MathewMacDougall** [comment]
I know we don't know the cause for sure, but I think listing potential likely causes in the message wouldn't hurt.

If we had a try-catch in `ssl_vision_client.cpp`, I think it makes the most sense to LOG/WARN about the potential cause of the socket failure there, and then throw the same exception again as it's the most descriptive of the problem. In this scenario the exception handling would just be to print a more descriptive message before passing up the exception to halt the system.

**Comment by garethellis0** [comment]
Sure, that makes sense. Do we have some logging mechanism in place (preferably ROS-agnostic)?

**Comment by garethellis0** [comment]
How does this sound; I'll put the try-catch in `ssl_vision_client.cpp` with a descriptive comment and link to the issue to fill in later?

**Comment by MathewMacDougall** [comment]
Sounds good. ROS-agnostic logging is in progress but isn't done yet (that's on me).

**Comment by garethellis0** [comment]
@MathewMacDougall - done, ready for re-review

**Review by MathewMacDougall — APPROVED** [review]
LGTM :+1:

**Comment by MathewMacDougall** [comment]
@EvanMorcom @akhilveeraghanta @henrymliu we'll need at least 1 more review

**Review by MathewMacDougall — APPROVED** [review]

**Review by EvanMorcom — APPROVED** [review]
LGTM :+1:

**Pull request merged**
