### PR TITLE
Removed AppVeyor Badge From README

### PR DESCRIPTION
**Pull request by garethellis0**
### Description
Just removing this until we actually get the Appveyor server up and running again.

### Review Checklist

**_It is the reviewers responsibility to also make sure every item here has been covered_**

- [ ] **Function & Class comments**: All function definitions (usually in the `.h` file) should have a javadoc style comment at the start of them. For examples, see the functions defined in `thunderbots/software/geom`. Similarly, all classes should have an associated Javadoc comment explaining the purpose of the class.
- [ ] **Remove all commented out code**
- [ ] **Remove extra print statements**: for example, those just used for testing
- [ ] **Resolve all TODO's**: All `TODO` (or similar) statements should either be completed or associated with a github issue
- [ ] **Justify drops in code coverage**: If this PR results in a non-trivial drop in code coverage (a bot should post a coverage diagram as a comment), please justify why we can't test the code that's not covered.

### CODE REVIEW

**Review by jonathanlew — COMMENTED** [review]
I'd rather it be commented out with a TODO and an issue, but I'm not sure others will agree with me

**Comment by garethellis0** [comment]
I'm fine with either, will wait until we get some more :eyes: here

**Review by kelvinkoon — CHANGES_REQUESTED** [review]
2nd'ing commenting it out with TODO. It could be easy to forget (especially since you and Mat set it up and who knows when we'll have access to the EDC again).

**Review by MathewMacDougall — COMMENTED** [review]
Fine with either solution (removing or commenting out)

**Comment by akhilveeraghanta** [comment]
ditto, fine either way

**Comment by EvanMorcom** [comment]
I'm going to break the stalemate and go for commenting out with a TODO

**Review by EvanMorcom — CHANGES_REQUESTED** [review]
👍 I'm voting for commenting out and adding an issue

**Comment by garethellis0** [comment]
Sounds good, created https://github.com/UBC-Thunderbots/Software/issues/1478 and just commented out the badge with a reference to this issue.

**Review by kelvinkoon — APPROVED** [review]
LGTM! :tada:

**Review by MathewMacDougall — APPROVED** [review]

**Review by jonathanlew — APPROVED** [review]
:badger:

**Review by EvanMorcom — APPROVED** [review]

**Pull request merged**
