### PR TITLE
Changed folder name from design_patterns to generic_factory, but also edited the files so that they called from generic_factory

### LINKED ISSUE #2241: Rename design_patterns folder to generic_factory
### Description of the task
there is only a generic_factory in that folder so the folder name should reflect that

### Acceptance criteria

- [ ] as titled

### PR DESCRIPTION
**Pull request by SpeedyPetey**
### Description
Changed folder name from design_patterns to generic_factory as my ticket requested.
Also in the files themselves, I changed from design_patterns to generic_factory as my original pull request was failing. 

### Testing Done
It runs on my terminal

### Resolved Issues
Resolves #2241

### Length Justification
N/A

### Review Checklist

**_It is the reviewers responsibility to also make sure every item here has been covered_**

- [x] **Function & Class comments**: All function definitions (usually in the `.h` file) should have a javadoc style comment at the start of them. For examples, see the functions defined in `thunderbots/software/geom`. Similarly, all classes should have an associated Javadoc comment explaining the purpose of the class.
- [x] **Remove all commented out code**
- [x] **Remove extra print statements**: for example, those just used for testing
- [x] **Resolve all TODO's**: All `TODO` (or similar) statements should either be completed or associated with a github issue
- [x] **Justify drops in code coverage**: If this PR results in a non-trivial drop in code coverage (a bot should post a coverage diagram as a comment), please justify why we can't test the code that's not covered.

### CODE REVIEW

**Review by jonathanlew — COMMENTED** [review]
Remember to run fix_formatting

**Comment by akhilveeraghanta** [comment]
almost good to go! looks like you need to just merge from upstream/master

see here: https://thunderbots.slack.com/archives/C0AP20J3T/p1633795535055500

**Review by jonathanlew — APPROVED** [review]
LGTM!

**Comment by SpeedyPetey** [comment]
fixed, just read over the docs and was told to leave a comment

**Review by akhilveeraghanta — APPROVED** [review]
:fire: lgtm!

**Pull request merged**
