### PR TITLE
Changed the usages of passing/evaluation.h and related files to passi…

### PR DESCRIPTION
**Pull request by hardik-ddod**
…ng/cost_function.h

### Description

The passing/evaluation.cpp file is really just a giant cost function used by gradient descent for optimizing passes. As such we should rename it to something like passing/cost_function.cpp.

### Testing Done

Tested that changing the file name doesn't break anything by running the previous tests after the file names and usages were updated.

### Review Checklist

- [x] Rename `passing/evaluation.cpp` to `passing/cost_function.cpp` and rename all associated tests / usages / comments to match

**_It is the reviewers responsibility to also make sure every item here has been covered_**

- [ ] **Function & Class comments**: All function definitions (usually in the `.h` file) should have a javadoc style comment at the start of them. For examples, see the functions defined in `thunderbots/software/geom`. Similarly, all classes should have an associated Javadoc comment explaining the purpose of the class.
- [ ] **Remove all commented out code**
- [ ] **Remove extra print statements**: for example, those just used for testing
- [ ] **Resolve all TODO's**: All `TODO` (or similar) statements should either be completed or associated with a github issue
- [ ] **Justify drops in code coverage**: If this PR results in a non-trivial drop in code coverage (a bot should post a coverage diagram as a comment), please justify why we can't test the code that's not covered.

### CODE REVIEW

**Comment by jonathanlew** [comment]
I'm not sure if you were told otherwise but I think this PR should be based on master and target master

Also please link the resolved issue

**Comment by MathewMacDougall** [comment]
Yep sorry we might not have been super clear about git workflow at the start of the year.

**Comment by garethellis0** [comment]
@hardik-ddod - looks like there's been some confusion here. Feel free to DM folks on slack (or better yet, ask in #software) if you have questions about how to move forward.

**Comment by jonathanlew** [comment]
> @hardik-ddod - looks like there's been some confusion here. Feel free to DM folks on slack (or better yet, ask in #software) if you have questions about how to move forward.

Feel free to dm me

**Comment by henryymliu** [comment]
@jonathanlew @hardik-ddod this will clash with https://github.com/UBC-Thunderbots/Software/pull/867, I think it's preferable to wait for mine to merge in first before reopening this. Thoughts?

**Comment by hardik-ddod** [comment]
@jonathanlew  Should be done by tonight!

**Comment by henryymliu** [comment]
I am aware this PR is closed, just leaving a heads up before the new one is opened.

**Comment by jonathanlew** [comment]
Sounds good! It'd be best to put this comment on the new PR, so I wanted to keep track of where the new one was at

**Pull request closed without merging**
