### PR TITLE
Configure MRF Dongle Config (channel) from roslaunch cmdline

### PR DESCRIPTION
**Pull request by henryymliu**
### Description

Allowed dongle config to be configured from the command line, used when changing channels. Because of how dongle was structured out, I found it easiest if the arg was published to the param server and then retrieved within the `MRFDongle` class, not sure if this is fine with you guys.

Usage: `roslaunch thunderbots ai_mrf.launch mrf_config:=0` (0 is the default)
### Testing Done

Tested with physical robot, via robot status.

### Review Checklist

**_It is the reviewers responsibility to also make sure every item here has been covered_**

- [x] **Start of document comments**: each `.cpp` and `.h` file should have a comment at the start of it. See files in the `thunderbots/software/geom` folder for examples.
- [x] **Function comments**: All function definitions (usually in the `.h` file) should have a javadoc style comment at the start of them. For examples, see the classes defined in `thunderbots/software/geom`
- [x] **Remove all commented out code**
- [x] **Remove extra print statements**: for example, those just used for testing
- [x] **Resolve all TODO's**: All `TODO` (or similar) statements should either be completed or associated with a github issue
- [x] **Justify drops in code coverage**: If this PR results in a non-trivial drop in code coverage (a bot should post a coverage diagram as a comment), please justify why we can't test the code that's not covered.

### CODE REVIEW

**Review by garethellis0 — COMMENTED** [review]
Hmm, what was the reasoning behind not just getting the command line parameter and passing it through the `MRFBackend` and `MRFDongle` constructors?

**Comment by henryymliu** [comment]
Would it be preferred if it was passed through both `MRFBackend` and `MRFDongle`? I thought it wouldn't be the cleanest solution, especially as there are other parameters like `MRF_CHANNEL`, `MRF_SYMBOL_RATE`, `MRF_PAN` that could potentially (although very unlikely to be used) that can be exposed to the command line in the future.

I was also experimenting with having the dongle switch configurations without having to restart it, so having it as part of the parameter server was part of that experimentation. It turns out that that resulted in something that was cleaner (well, so I thought), so that's also why I left it in.

**Comment by MathewMacDougall** [comment]
Gonna leave Gareth to comment on the cli argument. I definitely don't think we need to expose the `MRF_CHANNEL`, `MRF_SYMBOL_RATE` and `MRF_PAN` options. I also don't think being able to change radio configs on the fly is needed right now, since we only really do that once or twice a year at competition, and restarting the code isn't that bad.

**Comment by garethellis0** [comment]
I think I would prefer that for a few reasons:
- it makes the flow of data easier to follow. Using the parameter server like this is a bit like a `goto` statement (in terms of tracking data flow)
- it provides isolation from ROS, in case we ever wish to switch off of it.

**Review by garethellis0 — APPROVED** [review]
LGTM :+1: :tada:

**Pull request merged**
