### PR TITLE
Add python code formatting

### PR DESCRIPTION
**Pull request by MathewMacDougall**
### Description

Added [black](https://github.com/psf/black) to our formatting scripts to format Python code.

### Testing Done

Tested locally, should pass CI.

### Resolved Issues

#1335 

### Review Checklist

**_It is the reviewers responsibility to also make sure every item here has been covered_**

- [x] **Function & Class comments**: All function definitions (usually in the `.h` file) should have a javadoc style comment at the start of them. For examples, see the functions defined in `thunderbots/software/geom`. Similarly, all classes should have an associated Javadoc comment explaining the purpose of the class.
- [x] **Remove all commented out code**
- [x] **Remove extra print statements**: for example, those just used for testing
- [x] **Resolve all TODO's**: All `TODO` (or similar) statements should either be completed or associated with a github issue
- [x] **Justify drops in code coverage**: If this PR results in a non-trivial drop in code coverage (a bot should post a coverage diagram as a comment), please justify why we can't test the code that's not covered.

### CODE REVIEW

**Review by akhilveeraghanta — APPROVED** [review]
LGTM, looks like black just picked up all the changes autopep8 doesn't bother with lol

**Review by jonathanlew — CHANGES_REQUESTED** [review]
~Can you confirm that the black formatting will be buildified like clang formatting is?~

Edit: I misunderstood how this works my bad

**Comment by MathewMacDougall** [comment]
@jonathanlew What do you mean buildified? Run and checked as part of the CI build? (If so, yes because the CI formatting script runs the formatting script)

**Review by jonathanlew — APPROVED** [review]

**Review by kelvinkoon — APPROVED** [review]

**Review by LiCody — APPROVED** [review]

**Review by garethellis0 — APPROVED** [review]
LGTM :+1: :tada:

**Pull request merged**
