### PR TITLE
upgrade clang format 7 -> 10

### PR DESCRIPTION
**Pull request by akhilveeraghanta**
### Description
PR #1502 is failing formatting checks because of this weird error where clang format will get stuck in an infinite look escaping a comment around a macro.

Upgrading clang format versions fixes this problem.

### Testing Done
Ran clang format locally

### Resolved Issues
N/A

### Length Justification
N/A

### Review Checklist

**_It is the reviewers responsibility to also make sure every item here has been covered_**

- [x] **Function & Class comments**: All function definitions (usually in the `.h` file) should have a javadoc style comment at the start of them. For examples, see the functions defined in `thunderbots/software/geom`. Similarly, all classes should have an associated Javadoc comment explaining the purpose of the class.
- [x] **Remove all commented out code**
- [x] **Remove extra print statements**: for example, those just used for testing
- [x] **Resolve all TODO's**: All `TODO` (or similar) statements should either be completed or associated with a github issue
- [x] **Justify drops in code coverage**: If this PR results in a non-trivial drop in code coverage (a bot should post a coverage diagram as a comment), please justify why we can't test the code that's not covered.

### CODE REVIEW

**Review by MathewMacDougall — DISMISSED** [review]
LGTM :+1:

**Review by jonathanlew — CHANGES_REQUESTED** [review]
Great find. Can we fix `firmware_new/boards/frankie_v1/stm32h7xx_hal_conf.h:109`?

**Comment by akhilveeraghanta** [comment]
> Great find. Can we fix `firmware_new/boards/frankie_v1/stm32h7xx_hal_conf.h:109`?

good call, ran regen and ran formatting again

**Review by jonathanlew — APPROVED** [review]
:100:

**Review by MathewMacDougall — APPROVED** [review]

**Review by kelvinkoon — APPROVED** [review]

**Pull request merged**
