### PR TITLE
Fix cross-compile for Jetson Nano and PI Builds

### PR DESCRIPTION
**Pull request by itsarune**
### Description

#3316 broke cross-compilation on Jetson Nano and Pi builds. It was using the host gcc compiler instead of the jetson nano compiler. This enables the required toolchain resolution flag that allows bazel to use the correct compiler.

### Review Checklist

**_It is the reviewers responsibility to also make sure every item here has been covered_**

- [ ] **Function & Class comments**: All function definitions (usually in the `.h` file) should have a javadoc style comment at the start of them. For examples, see the functions defined in `thunderbots/software/geom`. Similarly, all classes should have an associated Javadoc comment explaining the purpose of the class.
- [ ] **Remove all commented out code**
- [ ] **Remove extra print statements**: for example, those just used for testing
- [ ] **Resolve all TODO's**: All `TODO` (or similar) statements should either be completed or associated with a github issue

### CODE REVIEW

**Review by Andrewyx — APPROVED** [review]

**Review by Mr-Anyone — APPROVED** [review]

**Comment by Mr-Anyone** [comment]
FYI: I think the cross compiler worked as I checked the binary with the command `file`.

**Comment by Mr-Anyone** [comment]
However, when I ran `bazel run //software/embedded/ansible:run_ansible --platforms=//cc_toolchain:robot --//software/embedded:host_platform=PI -- --playbook setup_raspberry_pi.yml --hosts random.local --ssh_pass gg` 

I got this error message and I am not sure where that came from: 

`/home/vhe/vscode/Software/src/software/power/BUILD:86:8: Executing genrule //software/power:powerloop_tar failed: (Exit 1): bash failed: error executing command /bin/bash -c ... (remaining 1 argument skipped)`


It could be I have not restart my laptop?

**Comment by itsarune** [comment]
Sometimes I see this if bazel isn't connected to the internet. Are you?

**Comment by Andrewyx** [comment]
> --playbook setup_raspberry_pi.yml

Why are you running this?

**Review by williamckha — APPROVED** [review]

**Comment by Mr-Anyone** [comment]
I just merged the two branch: this one, and Andrew's. Ansible seem to be able to flash.

**Comment by Mr-Anyone** [comment]
> > --playbook setup_raspberry_pi.yml
> 
> Why are you running this?

lmao. just realized I ran the wrong thing. This is what I ran: `bazel run //software/embedded/ansible:run_ansible --platforms=//cc_toolchain:robot --//software/embedded:host_platform=PI -- --playbook deploy_robot_software.yml --hosts random.local --ssh_pass gg`

**Comment by Mr-Anyone** [comment]
should we figure out why `setup_raspberry_pi.yml` does not work on my end or let this be a skill issues on my end? 

This playbook seems to be only ran once from the look of things.

**Comment by Mr-Anyone** [comment]
Forgot to mention, I flashed a robot successfully

**Pull request merged**
