### PR TITLE
Renamed tick functions to app_[primitive_name]_primitive_tick

### LINKED ISSUE #1631: Rename tick functions to app_[primitive_name]_primitive_tick
### Description of the task
For example, rename `spinning_move_tick` to  app_spinning_move_primitive_tick

### Acceptance criteria

- [ ] Rename all such instances in firwmare/app/primitives folder

### PR DESCRIPTION
**Pull request by Resocram**
### Description

Renamed all the tick functions located in the firmware/app/primitive folder to follow app_[primitive_name]_primitive_tick
### Resolved Issues

Resolves #1631 

### Review Checklist

**_It is the reviewers responsibility to also make sure every item here has been covered_**

- [x] **Function & Class comments**: All function definitions (usually in the `.h` file) should have a javadoc style comment at the start of them. For examples, see the functions defined in `thunderbots/software/geom`. Similarly, all classes should have an associated Javadoc comment explaining the purpose of the class.
- [x] **Remove all commented out code**
- [x] **Remove extra print statements**: for example, those just used for testing
- [x] **Resolve all TODO's**: All `TODO` (or similar) statements should either be completed or associated with a github issue
- [x] **Justify drops in code coverage**: If this PR results in a non-trivial drop in code coverage (a bot should post a coverage diagram as a comment), please justify why we can't test the code that's not covered.

### CODE REVIEW

**Review by akhilveeraghanta — COMMENTED** [review]
LGTM! Nice work :100:

**Review by jonathanlew — COMMENTED** [review]
Looks good, please update the `Resolved Issues` section of the PR description

**Review by jared-paul — APPROVED** [review]
LGTM pending Jon's comment (hyperlink tickets by doing #ticketnumber)

**Comment by Resocram** [comment]
Added issue # to resolved issues!

**Comment by HaomiaoZ** [comment]
Looks good to me 👍  @jonathanlew there seem to be tick functions in `chick_motion.c` and `move_helper.c`, I guess we don't need to rename them since they are not primitive?

**Comment by jonathanlew** [comment]
> Looks good to me +1 @jonathanlew there seem to be tick functions in `chick_motion.c` and `move_helper.c`, I guess we don't need to rename them since they are not primitive?

I think they are already named correctly

**Review by jonathanlew — APPROVED** [review]
LGTM!

**Pull request merged**
