### PR TITLE
Removed unused ROBOT-STATUS log filter

### LINKED ISSUE #2785: Remove unused `ROBOT_STATUS` log filter
### Description of the task
We have a `ROBOT_STATUS` log filter which is unused and not implemented, as a result, it should be removed:
https://github.com/UBC-Thunderbots/Software/blob/2330f76f64c53b1a23c58fb60b72d47482ba3da5/src/software/logger/custom_logging_levels.h#L11
https://github.com/UBC-Thunderbots/Software/blob/2330f76f64c53b1a23c58fb60b72d47482ba3da5/src/software/logger/logger.h#L113-L115

### Acceptance criteria

- [ ] Remove the `ROBOT_STATUS` log filter and its tests

### PR DESCRIPTION
**Pull request by GrayHoang**
### Description
Removed unused ROBOT_STATUS log filter in logger.h and custom_logging_levels.h #2785

### Testing Done

Compiled without any issues
### Resolved Issues

Resolves #2785 

### Review Checklist

**_It is the reviewers responsibility to also make sure every item here has been covered_**

- [x] **Function & Class comments**: All function definitions (usually in the `.h` file) should have a javadoc style comment at the start of them. For examples, see the functions defined in `thunderbots/software/geom`. Similarly, all classes should have an associated Javadoc comment explaining the purpose of the class.
- [x] **Remove all commented out code**
- [x] **Remove extra print statements**: for example, those just used for testing
- [x] **Resolve all TODO's**: All `TODO` (or similar) statements should either be completed or associated with a github issue

### CODE REVIEW

**Comment by Mr-Anyone** [comment]
I found another two other places that uses `ROBOT_STATUS`:

https://github.com/UBC-Thunderbots/Software/blob/c219e83dec6199b2d841a2f4f0712b6853ccaef8/src/software/logger/coloured_cout_sink_test.cpp#L79

https://github.com/UBC-Thunderbots/Software/blob/master/src/software/logger/csv_sink_test.cpp#L57

It would be great if you remove these two lines.

**Comment by GrayHoang** [comment]
In the future how can I look through the repo to find these other uses?

**Comment by williamckha** [comment]
> In the future how can I look through the repo to find these other uses?

Most IDEs have a "find in all files" feature (ctrl+shift+f in CLion and VS Code). Or you can use `grep` or `ag` in the terminal

**Comment by williamckha** [comment]
I'd also suggest reopening this PR using the `Grayson/Remove-Robot-Status` branch on your fork as the head ref and not the `master` branch on your fork. You don't have to merge your `Grayson/Remove-Robot-Status` changes into `master` on your fork! Ideally your fork's `master` should stay in sync with upstream's `master`.

Reset the last two commits on your fork's master with 
```
git checkout master
git reset --hard HEAD~2
git push origin master --force
```

**Comment by GrayHoang** [comment]
Yeah it was a mistake made when I was trying to figure out the git stuff. I think I've got it now. 
To be clear, if I push an update on a branch on my machine to github, it pushes it to a branch on the github repo on my account. Then, if I do a pull request to the shared repo, and it gets accepted, that change is integrated into the shared repo and therefore to the master branch on my account right?
What do I do with the branch I made? Does it just get left as like an unmerged branch?

By reopen, do you mean close this request and open a new one from the other branch?

**Comment by williamckha** [comment]
> To be clear, if I push an update on a branch on my machine to github, it pushes it to a branch on the github repo on my account.

Yes

> Then, if I do a pull request to the shared repo, and it gets accepted, that change is integrated into the shared repo and therefore to the master branch on my account right? What do I do with the branch I made? Does it just get left as like an unmerged branch?

Yes, once your PR is accepted then the change will be merged into upstream (the shared repo) master. Then you need to manually pull changes from upstream master into your local copy of master on your computer so that your master is up to date. You can push your local master to `origin/master` which is master on your GitHub fork, but you don't have to do that.   

Once you've merged your feature branch into upstream master, you can delete the branch from your fork and on your computer.

> By reopen, do you mean close this request and open a new one from the other branch?

Yes

**Pull request closed without merging**
