### PR TITLE
Replace usages of North, East, South, and West in Repository

### LINKED ISSUE #782: Remove all Usages Of "North", "South", "East" and "West" in our repo.
### Description of the task
Currently we use North,South,East, and West in the codebase to represent +y, -y, +x, -x respectively. We should remove ALL usages of these words and replace them with more descriptive ones like `posX`, `negX`, `posY`, `negY`.

### Acceptance criteria

- [ ] Replace all usages of North,South,East, and West in the codebase with more appropriate names

### PR DESCRIPTION
**Pull request by jsn0716**
### Description

Removed all usages of North, East, South, and West, replaced by x, y coordinate system. Files in src/software/gui were not changed.

### Testing Done

Ran all existing tests. The only changes were to names and comments, so no additional tests are required.

### Resolved Issues

resolves #782 

### Length Justification

N/A

### Review Checklist

**_It is the reviewers responsibility to also make sure every item here has been covered_**

- [x] **Function & Class comments**: All function definitions (usually in the `.h` file) should have a javadoc style comment at the start of them. For examples, see the functions defined in `thunderbots/software/geom`. Similarly, all classes should have an associated Javadoc comment explaining the purpose of the class.
- [x] **Remove all commented out code**
- [x] **Remove extra print statements**: for example, those just used for testing
- [x] **Resolve all TODO's**: All `TODO` (or similar) statements should either be completed or associated with a github issue
- [x] **Justify drops in code coverage**: If this PR results in a non-trivial drop in code coverage (a bot should post a coverage diagram as a comment), please justify why we can't test the code that's not covered.

### CODE REVIEW

**Review by MathewMacDougall — APPROVED** [review]
LGTM :+1:

**Review by jonathanlew — APPROVED** [review]
LGTM!

**Comment by garethellis0** [comment]
@jsn0716 - just a note for the future, please try to fill out the PR template. Otherwise LGTM :+1: :tada:

**Review by garethellis0 — APPROVED** [review]

**Comment by jsn0716** [comment]
@garethellis0 Thanks for the review! I thought I did fill out the PR template, are you talking about a specific part of the template? Or is there some other template I should have filled out?

**Comment by garethellis0** [comment]
Just the checkboxes at the bottom (to check them, change `[ ]` -> `[x]`)

**Pull request merged**
