### PR TITLE
Clamp dynamic radius in HRVO

### PR DESCRIPTION
**Pull request by nimazareian**
### Description
Clamping the velocity used by HRVO to dynamically change its radius. This is to avoid the possibility of a significantly high velocity causing the radius to be negative. Here's a [graph](https://www.desmos.com/calculator/fk7xnpcqqb) of the quartic function used.

#2941 provides more context behind this change.

### Resolved Issues
Related to #2941

### Review Checklist

**_It is the reviewers responsibility to also make sure every item here has been covered_**

- [ ] **Function & Class comments**: All function definitions (usually in the `.h` file) should have a javadoc style comment at the start of them. For examples, see the functions defined in `thunderbots/software/geom`. Similarly, all classes should have an associated Javadoc comment explaining the purpose of the class.
- [ ] **Remove all commented out code**
- [ ] **Remove extra print statements**: for example, those just used for testing
- [ ] **Resolve all TODO's**: All `TODO` (or similar) statements should either be completed or associated with a github issue

### CODE REVIEW

**Review by LiCody — APPROVED** [review]
LGTM

**Review by itsarune — APPROVED** [review]
LGTM

**Comment by raymond212** [comment]
LGTM too. Could we get this merged soon? I'm regularly running into the SIGABRT mentioned in #2941 while running thunderscope.

**Comment by nimazareian** [comment]
> LGTM too. Could we get this merged soon? I'm regularly running into the SIGABRT mentioned in #2941 while running thunderscope. 

With it merged now, could you see if it still happens to you? Since I can very rarely get it to happen on my end. So it's hard to verify it.

**Comment by raymond212** [comment]
It seems good for now. I'll let you know if I run into the SIGABRT again.

**Pull request merged**
