### PR TITLE
Start and Stop for Simulated Tests

### LINKED ISSUE #1832: Add ability to start/stop SimulatedTest
### Description of the task
We should be able to pause and continue SimulatedTests using the `Start AI` and `Stop AI` buttons. These are connected to `AIControlConfig`'s `RunAI` dynamic parameter

### Acceptance criteria

- [ ] pause and continue SimulatedTests using the `Start AI` and `Stop AI` buttons

### PR DESCRIPTION
**Pull request by jonathanlew**
### Description
* Minor refactor of AIWrapper
* Connect start and stop buttons to starting and stopping the simulated test

### Testing Done
manual testing

### Resolved Issues
resolves #1832 

### Review Checklist

**_It is the reviewers responsibility to also make sure every item here has been covered_**

- [ ] **Function & Class comments**: All function definitions (usually in the `.h` file) should have a javadoc style comment at the start of them. For examples, see the functions defined in `thunderbots/software/geom`. Similarly, all classes should have an associated Javadoc comment explaining the purpose of the class.
- [ ] **Remove all commented out code**
- [ ] **Remove extra print statements**: for example, those just used for testing
- [ ] **Resolve all TODO's**: All `TODO` (or similar) statements should either be completed or associated with a github issue
- [ ] **Justify drops in code coverage**: If this PR results in a non-trivial drop in code coverage (a bot should post a coverage diagram as a comment), please justify why we can't test the code that's not covered.

### CODE REVIEW

**Review by nimazareian — COMMENTED** [review]
When I run the simulated tests using WSL2 with (eg.) `bazel run //software/simulated_tests:kickoff_enemy_play_test -- --enable_visualizer`, after setting up the environment, the visualizer opens and then closes after a few seconds of running the test. It then outputs `QObject::~QObject: Timers cannot be stopped from another thread`. Is this normal behavior or am I making a mistake? 
In the few seconds the visualizer is open, the `Stop AI` button does seem to pause the simulation.

**Comment by jonathanlew** [comment]
> When I run the simulated tests using WSL2 with (eg.) `bazel run //software/simulated_tests:kickoff_enemy_play_test -- --enable_visualizer`, after setting up the environment, the visualizer opens and then closes after a few seconds of running the test. It then outputs `QObject::~QObject: Timers cannot be stopped from another thread`. Is this normal behavior or am I making a mistake?
> In the few seconds the visualizer is open, the `Stop AI` button does seem to pause the simulation.

There is a timeout for that simulated test so after a few seconds, it ends. The `QObject::~QObject: Timers cannot be stopped from another thread` message is because we create a gui on a different thread, even though qt doesn't recommend it

**Review by akhilveeraghanta — CHANGES_REQUESTED** [review]
Stopping the AI doesn't really pause the test for me, it kills the test early

start-stop-ai-behaviour

**Comment by jonathanlew** [comment]
> Stopping the AI doesn't really pause the test for me, it kills the test early

fixed

**Review by akhilveeraghanta — APPROVED** [review]
works well!

**Review by nimazareian — APPROVED** [review]
LGTM!

**Pull request merged**
