### PR TITLE
Geom: Integrate `intersection`

### LINKED ISSUE #1183: Geom: Integrate ...Intersection(...) methods from
### Description of the task
We now have ...Intersection(...) methods in the new_geom `intersection.h`, `intersection.cpp`.

Let's integrate these with the rest of the codebase and remove their old_geom counterparts.

### Acceptance criteria
- [ ] Old geom counterparts in `util.h` and `util.cpp` cleared
- [ ] Usages replaced with that of new_geom methods
- [ ] All existing tests still pass

### PR DESCRIPTION
**Pull request by scveloso**
### Description
 Integrates the new `intersection.h` and `intersection.cpp` with the rest of the codebase.

### Testing Done
All existing tests that passed still pass

### Resolved Issues
resolves #1183 

### Length Justification
Length is mostly removal of old geom intersection stuff from util. 

### Review Checklist

**_It is the reviewers responsibility to also make sure every item here has been covered_**

- [x] **Function & Class comments**: All function definitions (usually in the `.h` file) should have a javadoc style comment at the start of them. For examples, see the functions defined in `thunderbots/software/geom`. Similarly, all classes should have an associated Javadoc comment explaining the purpose of the class.
- [x] **Remove all commented out code**
- [x] **Remove extra print statements**: for example, those just used for testing
- [x] **Resolve all TODO's**: All `TODO` (or similar) statements should either be completed or associated with a github issue
- [x] **Justify drops in code coverage**: If this PR results in a non-trivial drop in code coverage (a bot should post a coverage diagram as a comment), please justify why we can't test the code that's not covered.

### CODE REVIEW

**Review by MathewMacDougall — DISMISSED** [review]
LGTM :fire:

**Review by garethellis0 — DISMISSED** [review]
LGTM :+1: :tada:

**Review by jsn0716 — DISMISSED** [review]
LGTM!

**Review by MathewMacDougall — DISMISSED** [review]
LGTM pending CI

**Comment by scveloso** [comment]
`FAIL: //software/ai/evaluation:calc_best_shot_test (see /home/travis/.cache/bazel/_bazel_travis/67b2d6795270482d31c70da9ab361aa0/execroot/__main__/bazel-out/k8-fastbuild/testlogs/software/ai/evaluation/calc_best_shot_test/test.log)`

Do we expect this test to fail? I don't think I changed anything related to this test

**Comment by jsn0716** [comment]
> `FAIL: //software/ai/evaluation:calc_best_shot_test (see /home/travis/.cache/bazel/_bazel_travis/67b2d6795270482d31c70da9ab361aa0/execroot/__main__/bazel-out/k8-fastbuild/testlogs/software/ai/evaluation/calc_best_shot_test/test.log)`
> 
> Do we expect this test to fail? I don't think I changed anything related to this test

The test is passing in master and I tried running it on this PR with the latest changes and it still fails. Might need some digging into what's causing the failure

**Comment by scveloso** [comment]
Waiting on #1235. CI should pass afterward.

**Review by jonathanlew — COMMENTED** [review]
Looks much cleaner. I would slightly prefer keeping `unordered_sets` and using the `begin` iterator to get an intersection, since intersections afaik don't have order.

**Comment by scveloso** [comment]
> Looks much cleaner. I would slightly prefer keeping unordered_sets and using the begin iterator to get an intersection, since intersections afaik don't have order.

@jonathanlew I thought about this but I'm was wary of doing so because for some situations that used old geom, intersection methods returned a pair of points. So some existing or future situations may explicitly want the first one but there's no guarantee that unordered_set `begin` iterator will point to that first one.

**Comment by jonathanlew** [comment]
> > Looks much cleaner. I would slightly prefer keeping unordered_sets and using the begin iterator to get an intersection, since intersections afaik don't have order.
> 
> @jonathanlew I thought about this but I'm was wary of doing so because for some situations that used old geom, intersection methods returned a pair of points. So some existing or future situations may explicitly want the first one but there's no guarantee that unordered_set `begin` iterator will point to that first one.

Hm so using `unordered_set`s would actually break some tests? I'd be curious to know what the situation is, since tests should rely on the order of intersections returned. Could you give it a go?

**Comment by scveloso** [comment]
> > > Looks much cleaner. I would slightly prefer keeping unordered_sets and using the begin iterator to get an intersection, since intersections afaik don't have order.
> > 
> > 
> > @jonathanlew I thought about this but I'm was wary of doing so because for some situations that used old geom, intersection methods returned a pair of points. So some existing or future situations may explicitly want the first one but there's no guarantee that unordered_set `begin` iterator will point to that first one.
> 
> Hm so using `unordered_set`s would actually break some tests? I'd be curious to know what the situation is, since tests should rely on the order of intersections returned. Could you give it a go?

No tests fail, I'll change it to `unordered_set`

**Review by MathewMacDougall — DISMISSED** [review]
LGTM :+1:

**Review by jonathanlew — APPROVED** [review]
LGTM! Thanks for looking into unordered_sets :+1:

**Review by jsn0716 — APPROVED** [review]
LGTM!

**Comment by garethellis0** [comment]
Hmm, github didn't seem to get the message that Travis CI passed. I've restarted the Travis CI build which hopfully should fix it.

**Comment by scveloso** [comment]
I think I need a reapproval from @garethellis0 or @MathewMacDougall since fixing formatting dismissed the approval

**Review by MathewMacDougall — APPROVED** [review]
Ask and you shall receive

**Pull request merged**
