### PR TITLE
Added Play headers and updated tests

### LINKED ISSUE #421: Change Tactic tests to use the test tactics
### Description of the task

Change the Tactic tests to use the test tactics instead of the MoveTactic

### Outline the task in more detail

Currently the unit tests for the generic functionality of our `Tactic` class use the `MoveTactic`. Since this is an actual "gameplay" tactic it is subject to change which might break the unit tests (although it shouldn't since it's only testing generic functionality). We now have "test tactics" defined in `test/ai/hl/stp/test_tactics`. We should use these for the generic tests instead.

### Acceptance criteria

- [ ] Replace the `MoveTactic` in the Tactic tests with `MoveTestTactic`

### PR DESCRIPTION
**Pull request by MathewMacDougall**
### Description

Added `.h` files to the concrete `Play` classes, and added static member variables with the Play name. 

I also updated the tests while I was there to use the member variable names wherever possible over raw strings, and updated the Tactic and PlayFactory tests to use the TestTactics and TestPlays. Also resolved some `TODOs` in the tests.

### Testing Done

All current unit tests pass.

### Resolved Issues

The test updates resolve #421 

### Review Checklist

**_It is the reviewers responsibility to also make sure every item here has been covered_**

- [x] **Start of document comments**: each `.cpp` and `.h` file should have a comment at the start of it. See files in the `thunderbots/software/geom` folder for examples.
- [x] **Function comments**: All function definitions (usually in the `.h` file) should have a javadoc style comment at the start of them. For examples, see the classes defined in `thunderbots/software/geom`
- [x] **Remove all commented out code**
- [x] **Remove extra print statements**: for example, those just used for testing
- [x] **Resolve all TODO's**: All `TODO` (or similar) statements should either be completed or associated with a github issue
- [x] **Justify drops in code coverage**: If this PR results in a non-trivial drop in code coverage (a bot should post a coverage diagram as a comment), please justify why we can't test the code that's not covered.

### CODE REVIEW

**Comment by MathewMacDougall** [comment]
@garethellis0 PR updated and rebased

**Review by garethellis0 — DISMISSED** [review]
LGTM :+1: :tada:

**Comment by MathewMacDougall** [comment]
@garethellis0 I should have fixed the CI errors. Will need re-approval

**Review by garethellis0 — APPROVED** [review]
LGTM :+1: :tada:

**Pull request merged**
