### PR TITLE
Reduce clutter from CI logs

### PR DESCRIPTION
**Pull request by akhilveeraghanta**
### Description
Its really hard to figure out what went wrong because the build logs for travis are incredibly long
Travis doesn't support ANSI escape characters so every time bazel does a carriage return and rewrites the same line, it shows up as a new line causing the logs to flood

We can suppress the loading progress, and the progress, which makes it significantly less cluttered

Removes ~120 thousand lines before the test output

### Testing Done
Testing w/ this PR

### Resolved Issues
pet peeve

### Review Checklist

**_It is the reviewers responsibility to also make sure every item here has been covered_**

- [x] **Function & Class comments**: All function definitions (usually in the `.h` file) should have a javadoc style comment at the start of them. For examples, see the functions defined in `thunderbots/software/geom`. Similarly, all classes should have an associated Javadoc comment explaining the purpose of the class.
- [x] **Remove all commented out code**
- [x] **Remove extra print statements**: for example, those just used for testing
- [x] **Resolve all TODO's**: All `TODO` (or similar) statements should either be completed or associated with a github issue
- [x] **Justify drops in code coverage**: If this PR results in a non-trivial drop in code coverage (a bot should post a coverage diagram as a comment), please justify why we can't test the code that's not covered.

### CODE REVIEW

**Review by kelvinkoon — APPROVED** [review]
LGTM (pending if CI works as intended)

**Review by jonathanlew — COMMENTED** [review]
This saves 100 lines off the log file. It doesn't fix how half the log is warnings on 3rd party/legacy code

**Comment by MathewMacDougall** [comment]
> It doesn't fix how half the log is warnings on 3rd party/legacy code

Wouldn't that be an issue with `Werror` and our warning flags?

**Comment by akhilveeraghanta** [comment]
It felt like def more than 100 lines, and it still enough clutter gone that software errors are more visible. You don't need to scroll as far down to look at software failures.

 FW will need to be handled separately

**Comment by akhilveeraghanta** [comment]
> This saves 100 lines off the log file. It doesn't fix how half the log is warnings on 3rd party/legacy code

Went to check the difference between this PR and another one

it reduces `120000` lines from the beginning of the log

**Comment by jonathanlew** [comment]
I was comparing to this build https://travis-ci.org/github/UBC-Thunderbots/Software/jobs/703612278

**Comment by akhilveeraghanta** [comment]
Do we have cache enabled? That didn't seem to download anything at the start
I was looking at this one: https://travis-ci.org/github/UBC-Thunderbots/Software/jobs/703647222

**Review by jonathanlew — APPROVED** [review]
:+1:

**Comment by MathewMacDougall** [comment]
No cache I'm aware of, these should all be fresh docker containers :shrug:

**Review by MathewMacDougall — APPROVED** [review]

**Pull request merged**
