### PR TITLE
Redis timing fix

### PR DESCRIPTION
**Pull request by Bvasilchikov**
The current set key method on redis client is synchronous and is delaying thunderloop. now set commands are committed asynchronously to the redis-server.

### Review Checklist

**_It is the reviewers responsibility to also make sure every item here has been covered_**

- [ ] **Function & Class comments**: All function definitions (usually in the `.h` file) should have a javadoc style comment at the start of them. For examples, see the functions defined in `thunderbots/software/geom`. Similarly, all classes should have an associated Javadoc comment explaining the purpose of the class.
- [ ] **Remove all commented out code**
- [ ] **Remove extra print statements**: for example, those just used for testing
- [ ] **Resolve all TODO's**: All `TODO` (or similar) statements should either be completed or associated with a github issue

### CODE REVIEW

**Review by nimazareian — COMMENTED** [review]
LGTM. Though I think we should first test it out and see if it actually fixes our issue in Thunderloop. Mainly to see how the runtime improves between `sync_commit` and `commit`, and how fast we can run Thunderloop now compared to before.

**Comment by nimazareian** [comment]
It seems like the `get` method which we call multiple times in Thunderloop is also synchronous. Should see how slow that is as well, and whether it is problematic.
https://github.com/UBC-Thunderbots/Software/blob/2330f76f64c53b1a23c58fb60b72d47482ba3da5/src/software/jetson_nano/redis/redis_client.cpp#L48-L53

**Review by itsarune — APPROVED** [review]
looks good

bit confused about where we use `getAsync`, `setAsync`?

**Comment by itsarune** [comment]
closed via #2786

**Pull request closed without merging**
