### PR TITLE
Moved glob recurse for cmake SHARED_UTIL_SRC to top level CMakeLists.txt

### PR DESCRIPTION
**Pull request by MathewMacDougall**
### Description
*Give a high-level description of the changes in this PR*
Proposal to move the GLOB_RECURSE for SHARED_UTIL_SRC to the top level CMakeLists.txt under thunderbots/ since these files will be used in firmware and software. This removes the need for hard-coding paths with ".." in them, since they are not full proof if we move stuff around.

This is a new version of #42 since I can't push to Daniel's branch.

### Testing Done
*Outline any testing that was done for these changes. This could be unit tests, integration tests, etc.*
Verified the code builds when opened from either the `src/CMakeLists.txt` file or the `src/thunderbots/CMakeLists.txt` file.

### Resolved Issues
*Link any issues that this PR resolved. Eg `resolves #1, #2, and #5` (note that they MUST be specified like this so Github can automatically close them then this PR merges)*

NA

### Review Checklist
*(Please check every item to indicate your code complies with it (by changing `[ ]`->`[x]`). This will hopefully save both you and the reviewer(s) a lot of time!)*
***It is the reviewers responsibility to also make sure every item here has been covered***
- [x] **Start of document comments**: each `.cpp` and `.h` file should have a comment at the start of it. See files in the `thunderbots/software/geom` folder for examples.
- [x] **Function comments**: All function definitions (usually in the `.h` file) should have a javadoc style comment at the start of them. For examples, see the classes defined in `thunderbots/software/geom` 
- [x] **Remove all commented out code**
- [x] **Remove extra print statements**: for example, those just used for testing
- [x] **Resolve all TODO's**: All `TODO` (or similar) statements should either be completed or associated with a github issue

***Feel free to make additions of things that we should be checking to this file if you think there's something missing!!!!***

### CODE REVIEW

**Review by EvanMorcom — APPROVED** [review]
LGTM

**Review by garethellis0 — APPROVED** [review]
LGTM :+1: :tada:

**Review by henryymliu — APPROVED** [review]
LGTM

**Comment by garethellis0** [comment]
@henrymliu - just a note, I think we should try to avoid merging other peoples PR's if at all possible. It's a fairly common scenario that on a last read-through before merging, the author catches one or two last things to change (at least I certainly do). This also gives people a greater sense of ownership and responsibility for the code they're merging.

We should really document this all somewhere..... I'm gonna go take a look at the wiki

**Pull request merged**
