### PR TITLE
Add Support For Ubuntu 20.04

### PR DESCRIPTION
**Pull request by LiCody**
### Description

- add support for 20.04 in the setup scripts

### Testing Done
- pending AkhilCI ™️ 

### Review Checklist

**_It is the reviewers responsibility to also make sure every item here has been covered_**

- [x] **Function & Class comments**: All function definitions (usually in the `.h` file) should have a javadoc style comment at the start of them. For examples, see the functions defined in `thunderbots/software/geom`. Similarly, all classes should have an associated Javadoc comment explaining the purpose of the class.
- [x] **Remove all commented out code**
- [x] **Remove extra print statements**: for example, those just used for testing
- [x] **Resolve all TODO's**: All `TODO` (or similar) statements should either be completed or associated with a github issue
- [x] **Justify drops in code coverage**: If this PR results in a non-trivial drop in code coverage (a bot should post a coverage diagram as a comment), please justify why we can't test the code that's not covered.

### CODE REVIEW

**Review by akhilveeraghanta — COMMENTED** [review]
AkhilCI :tm: report (edit: on Ubuntu 20.04)

`full_system` :heavy_check_mark: 
`simulator` :heavy_check_mark:
`robot_diagnostics` :heavy_check_mark:  
`clion` :heavy_check_mark:
`flashing and debugging firmware_new` :heavy_check_mark: 
`STM32H7 CubeMX` :heavy_check_mark: 

Just one comment from me

**Review by jonathanlew — COMMENTED** [review]
LGTM pending Akhil's comments

**Review by akhilveeraghanta — APPROVED** [review]
💯

**Review by jonathanlew — APPROVED** [review]
👍

**Pull request merged**
