### PR TITLE
Delete setRadius and setOrigin and rename getRadius and getOrigin

### LINKED ISSUE #1801: Delete Circle::setOrigin and Circle::setRadius
### Description of the task
Delete `Circle::setOrigin` and `Circle::setRadius` because we don't use it outside of `circle_test.cpp`. We can also rename `getOrigin` and `getRadius` to just `origin` and `radius`

### Acceptance criteria

- [ ] Delete Circle::setOrigin and Circle::setRadius
- [ ] rename `getOrigin` and `getRadius` to just `origin` and `radius`

### PR DESCRIPTION
**Pull request by BrianS99**
### Description
Removed the functions ```Circle::getRadius()``` and  ```Circle::getOrigin()``` from the Circle class and interface. Also removed the test cases for those functions. Renamed  `getOrigin` and `getRadius` to just `origin` and `radius`

### Testing Done
Remaining tests in `circle_test.cpp` all pass

### Resolved Issues
Resolves #1801 

### Review Checklist

**_It is the reviewers responsibility to also make sure every item here has been covered_**

- [x] **Function & Class comments**: All function definitions (usually in the `.h` file) should have a javadoc style comment at the start of them. For examples, see the functions defined in `thunderbots/software/geom`. Similarly, all classes should have an associated Javadoc comment explaining the purpose of the class.
- [x] **Remove all commented out code**
- [x] **Remove extra print statements**: for example, those just used for testing
- [x] **Resolve all TODO's**: All `TODO` (or similar) statements should either be completed or associated with a github issue
- [x] **Justify drops in code coverage**: If this PR results in a non-trivial drop in code coverage (a bot should post a coverage diagram as a comment), please justify why we can't test the code that's not covered.

### CODE REVIEW

**Comment by BrianS99** [comment]
I have one comment about this PR: now the custom constructor does not check for invalid radius sizes, will we just have to add that to the precondition of the circle class?

**Review by kelvinkoon — COMMENTED** [review]
LGTM overall! I would add the check back into the constructor IMO.

**Review by jonathanlew — CHANGES_REQUESTED** [review]
I agree with Kelvin that we should add the check to the constructor. In that case we should add an `@throws` to the javadoc

**Review by jonathanlew — COMMENTED** [review]
LGTM pending CI

**Review by akhilveeraghanta — CHANGES_REQUESTED** [review]
`software/geom/algorithms/intersects.cpp` is still using the old circle functions which is why CI is failing

**Review by jonathanlew — COMMENTED** [review]
LGTM except for fix formatting

**Review by jonathanlew — APPROVED** [review]

**Review by kelvinkoon — APPROVED** [review]
LGTM pending CI

**Review by akhilveeraghanta — APPROVED** [review]

**Pull request merged**
