### PR TITLE
Port latest ssl vision protos

### LINKED ISSUE #1339: Port latest protos from ssl-vision
### Description of the task
Port latest protos from ssl-vision that fix a typo: https://github.com/RoboCup-SSL/ssl-vision

### Acceptance criteria

- [ ] Port and format
- [ ] Check that it doesn't break CI

### PR DESCRIPTION
**Pull request by MathewMacDougall**
### Description

Ported the latest SSL Vision protos that fixed some typos

### Testing Done

CI

### Resolved Issues

resolves #1339 

### Review Checklist

**_It is the reviewers responsibility to also make sure every item here has been covered_**

- [x] **Function & Class comments**: All function definitions (usually in the `.h` file) should have a javadoc style comment at the start of them. For examples, see the functions defined in `thunderbots/software/geom`. Similarly, all classes should have an associated Javadoc comment explaining the purpose of the class.
- [x] **Remove all commented out code**
- [x] **Remove extra print statements**: for example, those just used for testing
- [x] **Resolve all TODO's**: All `TODO` (or similar) statements should either be completed or associated with a github issue
- [x] **Justify drops in code coverage**: If this PR results in a non-trivial drop in code coverage (a bot should post a coverage diagram as a comment), please justify why we can't test the code that's not covered.

### CODE REVIEW

**Review by jonathanlew — DISMISSED** [review]
LGTM pending CI. Happy to see these typos go away

**Review by kelvinkoon — COMMENTED** [review]
Seeing `SSL_FieldCicularArc` become `SSL_FieldCircularArc` is satisfying.
CI is failing the check formatting. Will approve after it passes.

**Comment by MathewMacDougall** [comment]
Whoops. Formatting is now fixed :tm:

**Review by kelvinkoon — APPROVED** [review]
LGTM :tada:

**Review by jonathanlew — APPROVED** [review]

**Review by akhilveeraghanta — APPROVED** [review]

**Pull request merged**
