### PR TITLE
WIP: (2/4) Added visitor for radio primitives

### LINKED ISSUE #235: Create a visitor to create radio packets from Primitives
**Is your feature request or enhancement related to a problem? What specifically could be better? Please describe.**
We should use a visitor to create radio packets from the `Primitive` classes to remove the responsibility from the `Primitive` classes.

**Describe the solution you'd like**
Create a new `RadioSerializerPrimitiveVisitor` that extends from the `PrimitiveVisitor` interface. This visitor should be responsible for creating a radio packet from the information in each Primitive. This includes packing the parameters into the parameters and bits, as well as the `Primitive Type` id (this will be handled by the visitor instead of #221 )

**Describe alternatives you've considered**
Leaving things as they are. This means that the `Primitive` classes are partially aware and in-control of the radio encoding, because they must return the parameters and "extra bits" in the correct order from the `getParameters` and `getExtraBits` functions. This is not ideal.

**Additional context**
A similar approach is being taken to use a Visitor to encode the `Primitives` to ROS messages. See #226

### PR DESCRIPTION
**Pull request by henryymliu**
### Description
*Give a high-level description of the changes in this PR*
Adds a visitor that will convert primitives into a format that is easier for conversion into radio packets.

Still need some field testing to verify if the visiting has been done correctly.

### Testing Done
Testing TBD

### Resolved Issues
resolves #235 

### Review Checklist
*(Please check every item to indicate your code complies with it (by changing `[ ]`->`[x]`). This will hopefully save both you and the reviewer(s) a lot of time!)*
***It is the reviewers responsibility to also make sure every item here has been covered***
- [x] **Start of document comments**: each `.cpp` and `.h` file should have a comment at the start of it. See files in the `thunderbots/software/geom` folder for examples.
- [x] **Function comments**: All function definitions (usually in the `.h` file) should have a javadoc style comment at the start of them. For examples, see the classes defined in `thunderbots/software/geom` 
- [x] **Remove all commented out code**
- [x] **Remove extra print statements**: for example, those just used for testing
- [ ] **Resolve all TODO's**: All `TODO` (or similar) statements should either be completed or associated with a github issue
- [ ] **Justify drops in code coverage**: If this PR results in a non-trivial drop in code coverage (a bot should post a coverage diagram as a comment), please justify why we can't test the code that's not covered.

***Feel free to make additions of things that we should be checking to this file if you think there's something missing!!!!***

### CODE REVIEW

**Comment by henryymliu** [comment]
See #333

**Comment by garethellis0** [comment]
#333 is a PR that isn't merged? Why did we close this?

**Comment by henryymliu** [comment]
I prematurely removed the primitive array and extra bits array from the primitive class in this PR; @MathewMacDougall wanted to leave those in until another visitor (can't remember which one) is completed.

Figured it would be easier to create a new PR rather than modifying all the files in this one.

**Comment by garethellis0** [comment]
Ok, that's fine, but I'm still confused why this issue was closed before the PR is merged?

**Comment by henryymliu** [comment]
#235? It was never closed? All I've done is replaced one PR with another.

**Comment by garethellis0** [comment]
Ohhh sorry, I misunderstood. All good

**Pull request closed without merging**
