### PR TITLE
Make Travis CI Use Our `fix_formatting.sh` Script

### PR DESCRIPTION
**Pull request by garethellis0**
### Description
Changed `travis_ci.sh` to use our `fix_formtting.sh` script instead of calling `git-clang-format` directly. This will make it more consistent with what we see on our machines, and will also allow #110 to pass CI (as we will be able to tell CI not to look at javascript or typescript files).

### Testing Done
~Still doing some testing in CI itself (should **not** be merged until this is completed).~
**Edit:** Testing is complete, should be good to go.
- [x] CI does not detect any changed files (and passes) if no files need to be formatted
- [x] CI does detect changed files (and fails) if files had to be formatted.

### Resolved Issues
NA

### Review Checklist
*(Please check every item to indicate your code complies with it (by changing `[ ]`->`[x]`). This will hopefully save both you and the reviewer(s) a lot of time!)*
***It is the reviewers responsibility to also make sure every item here has been covered***
- [x] **Start of document comments**: each `.cpp` and `.h` file should have a comment at the start of it. See files in the `thunderbots/software/geom` folder for examples.
- [x] **Function comments**: All function definitions (usually in the `.h` file) should have a javadoc style comment at the start of them. For examples, see the classes defined in `thunderbots/software/geom` 
- [x] **Remove all commented out code**
- [x] **Remove extra print statements**: for example, those just used for testing
- [x] **Resolve all TODO's**: All `TODO` (or similar) statements should either be completed or associated with a github issue

***Feel free to make additions of things that we should be checking to this file if you think there's something missing!!!!***

### CODE REVIEW

**Comment by garethellis0** [comment]
@qgolsteyn @MathewMacDougall - this should be good to go once CI passes, requesting reviews now.

**Review by qgolsteyn — DISMISSED** [review]
Looks good to me. I see you have not removed typescript or javascript support in this PR. I imagine this will be accomplished by #110

**Comment by garethellis0** [comment]
@qgolsteyn - fixed grammar, should be good to go

**Review by qgolsteyn — APPROVED** [review]

**Comment by qgolsteyn** [comment]
PR is good. However, build seems to be flaky.

When downloading the docker image: `received unexpected HTTP status: 503 Service Unavailable`

**Comment by garethellis0** [comment]
Ok, I just re-ran the build and it worked. It's mildly worrying that it failed in the first place, but seeing as it was just a one-time thing on an external server being inaccessible, I'm not too worried.

**Pull request merged**
