### PR TITLE
Added Documentation On Getters And Setters To code-style-guide.md

### LINKED ISSUE #1024: Document Convention for Use of Getters with or without get
### Description of the task
Some classes have getters prefixed by get, i.e. getName() and some don't, i.e. x(), y(), name(). 

### Acceptance criteria

- [ ] Document convention
- [ ] Refactor code to follow convention

### PR DESCRIPTION
**Pull request by garethellis0**
### Resolved Issues
resolves #1024

### Review Checklist

**_It is the reviewers responsibility to also make sure every item here has been covered_**

- [x] **Function & Class comments**: All function definitions (usually in the `.h` file) should have a javadoc style comment at the start of them. For examples, see the functions defined in `thunderbots/software/geom`. Similarly, all classes should have an associated Javadoc comment explaining the purpose of the class.
- [x] **Remove all commented out code**
- [x] **Remove extra print statements**: for example, those just used for testing
- [x] **Resolve all TODO's**: All `TODO` (or similar) statements should either be completed or associated with a github issue
- [x] **Justify drops in code coverage**: If this PR results in a non-trivial drop in code coverage (a bot should post a coverage diagram as a comment), please justify why we can't test the code that's not covered.

### CODE REVIEW

**Review by jsn0716 — APPROVED** [review]
LGTM!

**Review by MathewMacDougall — APPROVED** [review]

**Comment by garethellis0** [comment]
Gonna wait for @jonathanlew's review on this since he was pretty heavily involved in the discussions for it.

**Review by jonathanlew — APPROVED** [review]
Looks good, but are there parts of the code base that are inconsistent with that guideline?

**Comment by garethellis0** [comment]
The intent with this was to set the guideline so we don't waste time on debates in the future. Feel free to go through and change functions that are inconsistent, but I'm gonna say that's out-of-scope for this PR?

**Pull request merged**
