### PR TITLE
WIP: Modified Pivot Primitive

### PR DESCRIPTION
**Pull request by henryymliu**
### Description

Pivot primitive now pivots at a fixed radius around the ball (roughly ball radius + robot radius), with the angular now a parameter. This work was started at competition and is still in development.
End goal is a CMU-style pivot where we can pivot with the ball in the dribbler.

### Testing Done

still fixing the unit tests help

### Review Checklist

**_It is the reviewers responsibility to also make sure every item here has been covered_**

- [ ] **Start of document comments**: each `.cpp` and `.h` file should have a comment at the start of it. See files in the `thunderbots/software/geom` folder for examples.
- [ ] **Function comments**: All function definitions (usually in the `.h` file) should have a javadoc style comment at the start of them. For examples, see the classes defined in `thunderbots/software/geom`
- [ ] **Remove all commented out code**
- [ ] **Remove extra print statements**: for example, those just used for testing
- [ ] **Resolve all TODO's**: All `TODO` (or similar) statements should either be completed or associated with a github issue
- [ ] **Justify drops in code coverage**: If this PR results in a non-trivial drop in code coverage (a bot should post a coverage diagram as a comment), please justify why we can't test the code that's not covered.

### CODE REVIEW

**Review by MathewMacDougall — COMMENTED** [review]
CI still failing.

I took a quick look over this and it seems reasonable, I just want to check that this is the approach you will continue to take developing on this?

I'm asking just because this was experimental code and isn't really a "feature", so I don't really want to put code in that technically breaks the pivot primitive / action (even though it's generally not used atm).

Do you really want to keep this code and continue working on it, or would we rethink the approach now that we have more time and less stress.

**Comment by henryymliu** [comment]
CI is failing because I haven't fixed the grsim communication tests yet, going to be busy with work ramp-up for the next few weeks unfortunately.

I think what we have right now can definitely be continued to be work on. Because of radio limitations, the pivot radius as a parameter is removed and hardcoded to be something like BALL_RADIUS + ROBOT_RADIUS and replaced with angular velocity; thus the function signatures in this PR on AI side should pretty much be finalized.

All that's needed is some firmware tuning and this should be good to go.

**Comment by MathewMacDougall** [comment]
Alright, I'm fine merging this then. Maybe @akhilveeraghanta can fix the tests?

**Comment by MathewMacDougall** [comment]
@henryymliu 	@akhilveeraghanta 	any updates?

**Comment by henryymliu** [comment]
Nope, might have time this weekend to fix tests

**Comment by MathewMacDougall** [comment]
Looks like the action tests are missing / failing. Missing test results usually means one of the tests is segfaulting and breaking that entire suite. I think you can run the tests locally and pipe the `catkin_make run_tests` output into a file, then it's easier to search for "missing" or other failures from some tests exiting prematurely. Once you know for sure roughly which test suite it is, you need to run each test individually to find the one that segfaults. Running the whole suite at once generally masks the segfault for whatever reason. I can help debug this later if need be but am currently pretty busy. LMK if that makes sense.

**Comment by henryymliu** [comment]
Turns out a bad dynamic_cast after a test failure was the reason for the segfault.

**Comment by MathewMacDougall** [comment]
Ah yup that would do it. Take this out of WIP and I'll approve once CI passes.

**Comment by henryymliu** [comment]
Opened #741 to track the rest of the work on this, assigned to @akhilveeraghanta for now

**Review by MathewMacDougall — APPROVED** [review]

**Pull request merged**
