### PR TITLE
CI Fixes

### PR DESCRIPTION
**Pull request by Andrewyx**
### Description

Fixes some recent ci fails due to: 
1) primitive tests
2) outdated build files

### Review Checklist
thunderscope runs, project compiles

**_It is the reviewers responsibility to also make sure every item here has been covered_**

- [x] **Function & Class comments**: All function definitions (usually in the `.h` file) should have a javadoc style comment at the start of them. For examples, see the functions defined in `thunderbots/software/geom`. Similarly, all classes should have an associated Javadoc comment explaining the purpose of the class.
- [x] **Remove all commented out code**
- [x] **Remove extra print statements**: for example, those just used for testing
- [x] **Resolve all TODO's**: All `TODO` (or similar) statements should either be completed or associated with a github issue

### CODE REVIEW

**Comment by itsarune** [comment]
I'm a bit concerned that these tests are failing:
//software/ai/evaluation:intercept_test
    The `findBestInterceptForBall`function isn't able to return interception points as easily

//software/ai/evaluation:possession_test
    We seem to have regressed in detecting which robot has the ball

//software/ai/passing:cost_function_test
    Some of the `ratePass` calls are giving us lower scores than before

**Comment by Andrewyx** [comment]
> I'm a bit concerned that these tests are failing:
> //software/ai/evaluation:intercept_test
>     The `findBestInterceptForBall`function isn't able to return interception points as easily
> 
> //software/ai/evaluation:possession_test
>     We seem to have regressed in detecting which robot has the ball
> 
> //software/ai/passing:cost_function_test
>     Some of the `ratePass` calls are giving us lower scores than before

Thanks for the reply, I will share this with Nima and see if this could be a reason our gameplay is being a bit wonky.

**Comment by nimazareian** [comment]
> I'm a bit concerned that these tests are failing:
> //software/ai/evaluation:intercept_test
>     The `findBestInterceptForBall`function isn't able to return interception points as easily
> 
> //software/ai/evaluation:possession_test
>     We seem to have regressed in detecting which robot has the ball
> 
> //software/ai/passing:cost_function_test
>     Some of the `ratePass` calls are giving us lower scores than before

I haven't looked into this at all, but could be related to us changing the robot constants for motion planning

**Review by itsarune — APPROVED** [review]

**Comment by itsarune** [comment]
If I understand this correctly, we don't need this for master @Andrewyx. Please, re-open it if we do.

**Pull request closed without merging**
