### PR TITLE
Add most recent timestamp to world

### LINKED ISSUE #423: Add a "most_recent_update" Timestamp To World
### Description of the task
We should have a `Timestamp` on the `World` class that represents the last time anything in the world was updated.

### Outline the task in more detail
Add a `Timestamp` to world that represents the last time anything in the world was updated, and then in the `network_input` node (probably in `backend.cpp`), update this when anything in the world is changed.

One potentially clean way to do this is whenever we update something in the `World` (`Team`, `Ball`, etc.), if the timestamp on the updated version of that thing is greater then the current `World` timestamp, then update it.

Note the the refbox runs on a different timestamping system, so we should just ignore the `game_state_`.

### Acceptance criteria

- [ ] Add a `Timestamp` as a member variable to the `World` class and a getter function for that `Timestamp`
- [ ] Update the `World` class so that whenever of a compnent of it is updated (`Ball`, `Field`, `Team`, etc.) we update the `World` timestamp to match that objects timestamp *if* that object has a greater timestamp then the world
- [ ] Unit tests for all functionality!
- [ ] Find and resolve any `TODO`'s in the code that are associated with this issue (there are several)

### PR DESCRIPTION
**Pull request by EvanMorcom**
### Description
Added Timestamp history to the World object.

World Timestamps are dependent on the Timestamps of the member objects.

Included minor change to Team timestamp updating. 
### Testing Done

Unit tests for all new functions

### Resolved Issues

Resolved #423 

### Review Checklist
- [X] **Start of document comments**: each `.cpp` and `.h` file should have a comment at the start of it. See files in the `thunderbots/software/geom` folder for examples.
- [X] **Function comments**: All function definitions (usually in the `.h` file) should have a javadoc style comment at the start of them. For examples, see the classes defined in `thunderbots/software/geom`
- [X] **Remove all commented out code**
- [X] **Remove extra print statements**: for example, those just used for testing
- [X] **Resolve all TODO's**: All `TODO` (or similar) statements should either be completed or associated with a github issue
- [X] **Justify drops in code coverage**: If this PR results in a non-trivial drop in code coverage (a bot should post a coverage diagram as a comment), please justify why we can't test the code that's not covered.

### CODE REVIEW

**Comment by EvanMorcom** [comment]
Build failed due to pass generator getting a 5.2 vs 5 (see logs)

I don't think this is related to my code but I'll investigate.

**Comment by MathewMacDougall** [comment]
No that shouldn't be related (@garethellis0 	FYI). @EvanMorcom 	make sure you have pulled from `upstream master` since these tests _should_ be fixed.

**Review by MathewMacDougall — COMMENTED** [review]
LGTM pending the CI tests.

**Comment by garethellis0** [comment]
Ah, we should make sure that we go through and find every instance of `#423` in the codebase, because I've made notes in several places that we should be using the world timestamp instead of others.
It's worth nothing that one of those instances is in a PR that will probably go in Wednesday or Thursday (https://github.com/UBC-Thunderbots/Software/pull/639).

If it's not too much hassle I'd like to do that in this PR, but let me know if it's a pain and I can do it after.

**Comment by EvanMorcom** [comment]
@garethellis0 I can let it sit for a couple days until you're done with #639. Did you mark every instance with #423?

**Comment by garethellis0** [comment]
Yup, I believe I did. Thanks!

**Comment by EvanMorcom** [comment]
@MathewMacDougall @garethellis0 

Updated to remove TODO #423's

**Review by MathewMacDougall — APPROVED** [review]
LGTM :+1:

**Pull request merged**
