### PR TITLE
Move equalWithinTolerance to Separate File

### LINKED ISSUE #1425: Move all equalWithinTolerance functions to their own file and remove all default tolerance values
### Description of the task

as titled

### Acceptance criteria

- [ ] as titled

### PR DESCRIPTION
**Pull request by kelvinkoon**
### Description

Removed `equalWithinTolerance` to its own file.
Removed default tolerances.

### Testing Done

Unit tests still pass.

### Resolved Issues

Resolves #1425 

### Length Justification

`equalWithinTolerance` is used in a lot of tests, but they're mostly single line replacements. You can find all files by doing `grep -rl "equalWithinTolerance"`.

### Review Checklist

**_It is the reviewers responsibility to also make sure every item here has been covered_**

- [x] **Function & Class comments**: All function definitions (usually in the `.h` file) should have a javadoc style comment at the start of them. For examples, see the functions defined in `thunderbots/software/geom`. Similarly, all classes should have an associated Javadoc comment explaining the purpose of the class.
- [x] **Remove all commented out code**
- [x] **Remove extra print statements**: for example, those just used for testing
- [x] **Resolve all TODO's**: All `TODO` (or similar) statements should either be completed or associated with a github issue
- [x] **Justify drops in code coverage**: If this PR results in a non-trivial drop in code coverage (a bot should post a coverage diagram as a comment), please justify why we can't test the code that's not covered.

### CODE REVIEW

**Comment by kelvinkoon** [comment]
In `ssl_geometry_test.cpp`, there is a mock class that has its own `equalWithinTolerance` functions. Should those be moved as well? (I think they're only used within that file for testing)

**Review by jonathanlew — CHANGES_REQUESTED** [review]
Please put `equalWithinTolerance` in `namespace TestUtil` and include `equal_within_tolerance.h` in `test_util.h` and `equal_within_tolerance.h/cpp` in the `test_util` target, so that we don't need to include it in all the usages. However, equal_within_tolerance_test should be its own test target

**Comment by jonathanlew** [comment]
> 
> 
> In `ssl_geometry_test.cpp`, there is a mock class that has its own `equalWithinTolerance` functions. Should those be moved as well? (I think they're only used within that file for testing)

Those can stay where they are

**Review by jonathanlew — APPROVED** [review]

**Review by MathewMacDougall — APPROVED** [review]
LGTM :+1:

**Review by garethellis0 — APPROVED** [review]
LGTM :+1: :tada:

**Review by EvanMorcom — APPROVED** [review]
LGTM
🐶 🐕 🦮 🐩

**Pull request merged**
