### PR TITLE
WIP:  Implement Communication to ROS Param Server w/ Visualizer to Start AI Logic #392 

### LINKED ISSUE #392: Implement Communication to ROS Param Server w/ Visualizer to Start AI Logic
### Description of the task

Implement a way to communicate between the Visualizer and the ROS Param Server's information using ROSLib.js to start AI Logic.

### Outline the task in more detail

We should base it on getting and setting values in the ROS Param Server. New ROS actions will be created for getting and setting the values. The reducer will be used to manage state of these values from the ROS Param Server. 

The saga will be used to retrieve all parameters from the ROS Param server upon starting the application. Then, it will listen for updates from the ROS param server. 

The communication between both is going to be using rosbridge. 

### Acceptance criteria

- [ ] Create a sort of UI to set configurations
- [ ] Create action to retrieve information from ROS Param Server
- [ ] Create action to set information in the ROS Param Server
- [ ] Implement actions to communicate with ROS Param Server
- [ ] Have UI send actions (For instance, button click sends action to get ROS Params)

### PR DESCRIPTION
**Pull request by kelvinkoon**
### Description
This ticket will be used for adding communication between the ROS Param Server and the Visualizer.

### Testing Done
Unit tests have been written for the actions (sans getROSParam) and reducers. Working on sagas.
To fully run the application, run `yarn test` to start the Visualizer, `roslaunch rosbridge_server rosbridge_websocket.launch` to start RosBridge, and `roslaunch launch.ai` to start the ROS Param Server.

### Resolved Issues

Resolves #392 

### Review Checklist

**_It is the reviewers responsibility to also make sure every item here has been covered_**

- [ ] **Start of document comments**: each `.cpp` and `.h` file should have a comment at the start of it. See files in the `thunderbots/software/geom` folder for examples.
- [ ] **Function comments**: All function definitions (usually in the `.h` file) should have a javadoc style comment at the start of them. For examples, see the classes defined in `thunderbots/software/geom`
- [ ] **Remove all commented out code**
- [ ] **Remove extra print statements**: for example, those just used for testing
- [ ] **Resolve all TODO's**: All `TODO` (or similar) statements should either be completed or associated with a github issue
- [ ] **Justify drops in code coverage**: If this PR results in a non-trivial drop in code coverage (a bot should post a coverage diagram as a comment), please justify why we can't test the code that's not covered.

### CODE REVIEW

**Comment by MathewMacDougall** [comment]
Jumping on this early. @kelvinkoon I may have misspoke last time we talked, since `ROS Dynamic Parameters` are technically different from `Dynamic Reconfigure`, which is the system we actually use.

@akhilveeraghanta based on the latest developments with parameters and DynamicReconf, what is the best way for the Visualizer to set DynamicParameters. It can't set them like a "normal" rosparam right? It will need to call the service? Or do we need to implement the entire `DynamicReconfigureClient` like you mentioned?

**Comment by akhilveeraghanta** [comment]
Yeah it can't set them manually, we wont see the updates if it does. The best way to do it would be through the `DynamicReconfigureClient` or you can just call the service directly, which is probably lighter and works just as well. 

I will make sure that the client aspect of things are also working as part of the upcoming PR.

**Comment by MathewMacDougall** [comment]
@kelvinkoon Any progress on this?

**Comment by MathewMacDougall** [comment]
@kelvinkoon 	I'm assuming we can close this?

**Comment by kelvinkoon** [comment]
> @kelvinkoon I'm assuming we can close this?

Yes, this can be closed now.

**Pull request closed without merging**
