### PR TITLE
Apparently we need vartypes to build grsim

### PR DESCRIPTION
**Pull request by jonathanlew**
### Description
I tried to build grsim and didn't work until I added vartypes. See: https://github.com/RoboCup-SSL/grSim

### Review Checklist

**_It is the reviewers responsibility to also make sure every item here has been covered_**

- [ ] **Function & Class comments**: All function definitions (usually in the `.h` file) should have a javadoc style comment at the start of them. For examples, see the functions defined in `thunderbots/software/geom`. Similarly, all classes should have an associated Javadoc comment explaining the purpose of the class.
- [ ] **Remove all commented out code**
- [ ] **Remove extra print statements**: for example, those just used for testing
- [ ] **Resolve all TODO's**: All `TODO` (or similar) statements should either be completed or associated with a github issue
- [ ] **Justify drops in code coverage**: If this PR results in a non-trivial drop in code coverage (a bot should post a coverage diagram as a comment), please justify why we can't test the code that's not covered.

### CODE REVIEW

**Comment by henryymliu** [comment]
nani??? I built grSim on a fresh Arch Linux system (using a modified version of the existing script, see #920 ) and it ran perfectly fine, how mysterious...
Did it work for new members? Interesting how this was noticed so late, though

**Comment by jonathanlew** [comment]
> nani??? I built grSim on a fresh Arch Linux system (using a modified version of the existing script, see #920 ) and it ran perfectly fine, how mysterious...
> Did it work for new members? Interesting how this was noticed so late, though

yeah I assumed why it worked for in the past was that I already had vartypes installed, but maybe that's not it. I'm not sure we forced new members to install grsim
More investigation needed.

**Comment by MathewMacDougall** [comment]
I thought the newest grsim bundled vartypes on it's own? @matthewberends ?

**Comment by henryymliu** [comment]
@jonathanlew what were the errors? It might be possible that the grsim build detected your old vartypes instead, although AFAIK vartypes hasn't been updated for years

**Comment by jonathanlew** [comment]
CMakeFiles/grSim.dir/src/configwidget.cpp.o: In function `ConfigWidget::ConfigWidget()':
configwidget.cpp:(.text+0x5704): undefined reference to `VarTypes::VarXML::read(std::vector<std::shared_ptr<VarTypes::VarType>, std::allocator<std::shared_ptr<VarTypes::VarType> > >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)'
configwidget.cpp:(.text+0x6278): undefined reference to `VarTypes::VarTreeModel::setRootItems(std::vector<std::shared_ptr<VarTypes::VarType>, std::allocator<std::shared_ptr<VarTypes::VarType> > >)'

**Comment by jonathanlew** [comment]
I tried `sudo rm -rf /local/include/vartypes` but that didn't fix it

**Comment by henryymliu** [comment]
grSim does install vartypes if it's not found: https://github.com/RoboCup-SSL/grSim/blob/415b286dac2b2395d60f60c760622e5b283b238c/CMakeLists.txt#L97

And I do remember a returning member (@HaomiaoZ ?) getting the same error, which was fixed by removing `/usr/local/include/vartypes` (or whatever include directory it used) but clearly that didn't work for you

Looking at https://github.com/RoboCup-SSL/grSim/blob/master/cmake/modules/FindVarTypes.cmake, can you also try finding and removing the old libs, possibly in `/usr/local/lib`?

**Comment by garethellis0** [comment]
Yeah, I'm fairly sure I looked at this a while back and grsim installed vartypes.

**Comment by jonathanlew** [comment]
> grSim does install vartypes if it's not found: https://github.com/RoboCup-SSL/grSim/blob/415b286dac2b2395d60f60c760622e5b283b238c/CMakeLists.txt#L97
> 
> And I do remember a returning member (@HaomiaoZ ?) getting the same error, which was fixed by removing `/usr/local/include/vartypes` (or whatever include directory it used) but clearly that didn't work for you
> 
> Looking at https://github.com/RoboCup-SSL/grSim/blob/master/cmake/modules/FindVarTypes.cmake, can you also try finding and removing the old libs, possibly in `/usr/local/lib`?

That did it

**Pull request closed without merging**
