### PR TITLE
Bring balance to UBC Thunderbots

### PR DESCRIPTION
**Pull request by qgolsteyn**
### Description

Perfectly balanced, as all things should be.

### Resolved Issues

50% of them.

### CODE REVIEW

**Comment by qgolsteyn** [comment]
Brought to you by [thanos-js](https://www.npmjs.com/package/thanos-js)

**Comment by garethellis0** [comment]
I mean, good to see CI failed at least.........

**Comment by MathewMacDougall** [comment]
What did it cost?

**Comment by qgolsteyn** [comment]
Everything

**Comment by EvanMorcom** [comment]
LGTM, those extra 200k lines are probably just useless stuff like comments

**Comment by qgolsteyn** [comment]
Upon further though, I have decided that maybe those 200,000 lines are useful and maybe should be kept.

**Pull request closed without merging**
