### PR TITLE
(please ignore) debugging pre-commit.ci lite

### PR DESCRIPTION
**Pull request by asottile**
debugging this: https://github.com/pre-commit-ci/issues/issues/179

### CODE REVIEW

**Comment by asottile** [comment]
wellp, turns out I can't even run GHA so shrugs -- can someone click the button for me, cc @itsarune

**Comment by itsarune** [comment]
Yup just ran it

**Comment by asottile** [comment]
@itsarune can you click it again? I'm going to see if it reproduces in a separate workflow (I suspect github might not finalize artifacts in a job with other things(?))

**Comment by itsarune** [comment]
I triggered only the pre-commit action to see if it does anything different

**Comment by itsarune** [comment]
I see that in the original PR, it did create some kind of a pre-commit artifact here, although 722 bytes seems small 
Screen Shot 2023-04-24 at 6 40 32 PM

**Comment by itsarune** [comment]
oh wow looks like that worked

**Comment by asottile** [comment]
cool, looks like it just needs to be a separate workflow -- I'll document that

**Pull request closed without merging**
