### PR TITLE
Removed unnecessary if/else statements

### LINKED ISSUE #1821: Refactor Logic in BuildMotionConstraintSetFromGameState
### Description of the task

The current flow of the if and else statements in the BuildMotionConstraintSetFromGameState function from MotionConstraintSetBuilder is messy and includes additional statements that are not needed.
### Acceptance criteria

- [ ] Workflow for building motion constraint set is easier to follow

### Blocked By

#1791

### PR DESCRIPTION
**Pull request by Resocram**
### Description

Removed unnecessary if and else statements in the workflow for building motion_constraints

### Testing Done

Existing tests still pass

### Resolved Issues

Resolves #1821 

### Review Checklist

**_It is the reviewers responsibility to also make sure every item here has been covered_**

- [ ] **Function & Class comments**: All function definitions (usually in the `.h` file) should have a javadoc style comment at the start of them. For examples, see the functions defined in `thunderbots/software/geom`. Similarly, all classes should have an associated Javadoc comment explaining the purpose of the class.
- [ ] **Remove all commented out code**
- [ ] **Remove extra print statements**: for example, those just used for testing
- [ ] **Resolve all TODO's**: All `TODO` (or similar) statements should either be completed or associated with a github issue
- [ ] **Justify drops in code coverage**: If this PR results in a non-trivial drop in code coverage (a bot should post a coverage diagram as a comment), please justify why we can't test the code that's not covered.

### CODE REVIEW

**Review by akhilveeraghanta — COMMENTED** [review]
lgtm, but just making sure, is there test coverage for this part of the code (specifically this else block)?

**Comment by jsn0716** [comment]
Code change looks good, but would like to see a bit more explanation on how/why the if else statement isn't necessary

**Comment by Resocram** [comment]
> lgtm, but just making sure, is there test coverage for this part of the code (specifically this else block)?

Yes, I believe anything that is not a penalty or a kickoff will go in the else block, in which the CycleStoppageOrThemGameStatesTest tests will test for that. 

    game_state.updateRefereeCommand(RefereeCommand::HALT);
    EXPECT_EQ(correct_motion_constraints,
              buildMotionConstraintSet(game_state, *GetParam().first));

    game_state.updateRefereeCommand(RefereeCommand::STOP);
    EXPECT_EQ(correct_motion_constraints,
              buildMotionConstraintSet(game_state, *GetParam().first));

    game_state.updateRefereeCommand(RefereeCommand::NORMAL_START);
    EXPECT_EQ(correct_motion_constraints,
              buildMotionConstraintSet(game_state, *GetParam().first));

    game_state.updateRefereeCommand(RefereeCommand::DIRECT_FREE_THEM);
    EXPECT_EQ(correct_motion_constraints,
              buildMotionConstraintSet(game_state, *GetParam().first));

    game_state.updateRefereeCommand(RefereeCommand::INDIRECT_FREE_THEM);
    EXPECT_EQ(correct_motion_constraints,
              buildMotionConstraintSet(game_state, *GetParam().first));

    game_state.updateRefereeCommand(RefereeCommand::TIMEOUT_US);
    EXPECT_EQ(correct_motion_constraints,
              buildMotionConstraintSet(game_state, *GetParam().first));

    game_state.updateRefereeCommand(RefereeCommand::TIMEOUT_THEM);
    EXPECT_EQ(correct_motion_constraints,
              buildMotionConstraintSet(game_state, *GetParam().first));

    game_state.updateRefereeCommand(RefereeCommand::GOAL_US);
    EXPECT_EQ(correct_motion_constraints,
              buildMotionConstraintSet(game_state, *GetParam().first));

    game_state.updateRefereeCommand(RefereeCommand::GOAL_THEM);
    EXPECT_EQ(correct_motion_constraints,
              buildMotionConstraintSet(game_state, *GetParam().first));

    game_state.updateRefereeCommand(RefereeCommand::BALL_PLACEMENT_THEM);
    EXPECT_EQ(correct_motion_constraints,
              buildMotionConstraintSet(game_state, *GetParam().first));

**Comment by Resocram** [comment]
> Code change looks good, but would like to see a bit more explanation on how/why the if else statement isn't necessary

So in our else statement before, we had this:


    if (game_state.stayAwayFromBall()) //#1
    {
        motion_constraints.insert(MotionConstraint::HALF_METER_AROUND_BALL);
    }

    if (game_state.isPenalty()) //#2
    {
        if (game_state.isOurPenalty()) //#3
        {
            motion_constraints.insert(MotionConstraint::ENEMY_HALF);
        }
        else
        {
            // Is their penalty
            motion_constraints.insert(MotionConstraint::FRIENDLY_HALF);
        }
    }
    else if (game_state.isKickoff()) //#4
    {
        motion_constraints.insert({MotionConstraint::HALF_METER_AROUND_BALL,
                                   MotionConstraint::CENTER_CIRCLE,
                                   MotionConstraint::ENEMY_HALF});
    }
    else
    {
        if (game_state.stayAwayFromBall() || game_state.isOurKickoff()) //#5
        {
            motion_constraints.insert(MotionConstraint::HALF_METER_AROUND_BALL);
        }

        if (game_state.isOurPenalty()) //#6
        {
            motion_constraints.insert(MotionConstraint::ENEMY_DEFENSE_AREA);
        }
        else //#7
        {
            motion_constraints.insert(MotionConstraint::INFLATED_ENEMY_DEFENSE_AREA);
        }
        motion_constraints.insert(MotionConstraint::INFLATED_ENEMY_DEFENSE_AREA);

    }`

I have numbered the if/else branches for ease of reference.

In if statement 5, we already check game_state.stayAwayFromBall() in if statement 1 and game_state.isOurKickoff() is already checked in if statement 4 which means this branch is unnecessary since the motion constraint will already be added in the previous branches.

In if statement 6, we already check game_state.isOurPenalty() in if statement 2 and 3, which means this branch will never get executed. Although I am not sure why we add the ENEMY_DEFENSE_AREA motion_constraint in the 6 but not in 3.

This leaves the last else statement left.

Sorry for the formatting, I wasn't sure how to link my code to this comment.  Please lmk if I have any misunderstandings or if there are any other questions

**Review by jsn0716 — APPROVED** [review]
Thanks for the explanation, LGTM 💯

**Review by jonathanlew — APPROVED** [review]
LGTM!

**Pull request merged**
