### PR TITLE
Preallocate max replay file size when writing to file

### PR DESCRIPTION
**Pull request by Andrewyx**
### Description

Preallocates 1MB (REPLAY_MAX_CHUNK_SIZE_BYTES) per replay file upon file creation to reduce file write overheads. 

### Testing Done
Thunderscope replay runs without issue. Tested performance with timers comparing time taken to fill up max chunk size (not per write times), roughly 1s more efficient in overall logging per file. 

### Resolved Issues
Resolves [#2985]

### Review Checklist

**_It is the reviewers responsibility to also make sure every item here has been covered_**

- [x] **Function & Class comments**: All function definitions (usually in the `.h` file) should have a javadoc style comment at the start of them. For examples, see the functions defined in `thunderbots/software/geom`. Similarly, all classes should have an associated Javadoc comment explaining the purpose of the class.
- [x] **Remove all commented out code**
- [x] **Remove extra print statements**: for example, those just used for testing
- [x] **Resolve all TODO's**: All `TODO` (or similar) statements should either be completed or associated with a github issue

### CODE REVIEW

**Comment by Andrewyx** [comment]
It seems I goofed up my git branches and I combined this PR with the updates that I made in [#2987]. I would appreciate some advice on how to fix this

**Comment by itsarune** [comment]
try: 
`git revert a8b7671c5d12f7f6015bcf1c4c5649b050b9e4df`
`git revert 6e1e14c854d0a6dfd448bcfc29cff4a1f29fd346` (you may not need this one)

**Comment by itsarune** [comment]
I reverted the commits based on the commit ids of the commits associated in the PR

**Comment by Andrewyx** [comment]
Alright thanks, fixed it!

**Comment by aviwad** [comment]
Looks good but why did the simulated gameplay test fail?

**Review by JoshuaWu7 — COMMENTED** [review]
@Andrewyx It seems like CI is failing. Try doing a `git fetch upstream master`, then `git merge upstream/master`

**Comment by Andrewyx** [comment]
> @Andrewyx It seems like CI is failing. Try doing a `git fetch upstream master`, then `git merge upstream/master`

Yeah I saw the post on Discord regarding the CI issues but I did a pull and I believe that my branch is up to date.

**Comment by nimazareian** [comment]
> > @Andrewyx It seems like CI is failing. Try doing a `git fetch upstream master`, then `git merge upstream/master`
> 
> Yeah I saw the post on Discord regarding the CI issues but I did a pull and I believe that my branch is up to date.

After you pull upstream master, you need to push your changes again. The latest commits showing up on GitHub is from 2 weeks ago, where is the last commit on upstream master is from 2 days ago

**Review by JoshuaWu7 — APPROVED** [review]
Lgtm

**Review by aviwad — APPROVED** [review]
lgtm

**Review by nimazareian — APPROVED** [review]
:100:

**Pull request merged**
