### PR TITLE
removed debug print statements from geom/util_test

### LINKED ISSUE #787: Remove `#define DEBUG` In `geom/util_test.cpp`
### Description of the task
In `geom/util_test.cpp` there is a `#define DEBUG` that when set to 1 enables from debug output. Remove it and clean up places where it's used.

### Acceptance criteria

- [ ] Remove the `#define DEBUG` in `geom/utils_test.cpp`
- [ ] Clean up all locations where it was being used. In many cases it will just be removing some print statements, and maybe adding some comments.

### PR DESCRIPTION
**Pull request by amrm3lm**
### Description

Removed the definition of `DEBUG` and all instances of `dbgout`, which was used to print statements if `DEBUG` was 1. 

### Testing Done
No need to create new tests since I didnt change any of the functionality. I built and tested `util_test` again. All tests passed. 

### Resolved Issues

resolves #787 
### Review Checklist

**_It is the reviewers responsibility to also make sure every item here has been covered_**

- [x] **Function & Class comments**: All function definitions (usually in the `.h` file) should have a javadoc style comment at the start of them. For examples, see the functions defined in `thunderbots/software/geom`. Similarly, all classes should have an associated Javadoc comment explaining the purpose of the class.
- [x] **Remove all commented out code**
- [x] **Remove extra print statements**: for example, those just used for testing
- [x] **Resolve all TODO's**: All `TODO` (or similar) statements should either be completed or associated with a github issue
- [ ] **Justify drops in code coverage**: If this PR results in a non-trivial drop in code coverage (a bot should post a coverage diagram as a comment), please justify why we can't test the code that's not covered.

### CODE REVIEW

**Review by jonathanlew — DISMISSED** [review]
LGTM!

**Review by garethellis0 — DISMISSED** [review]
LGTM :+1: :tada:

**Review by MathewMacDougall — DISMISSED** [review]
LGTM :+1:

**Comment by akhilveeraghanta** [comment]
@amrm3lm there is a script in a folder called `clang_format` called `fix_formatting.sh` if you run that with `./fix_formatting.sh -a` CI will pass the formatting check and you should be able to get this in

**Comment by MathewMacDougall** [comment]
@amrm3lm looks like the build failed. Make sure to update from master to get Sam's latest change and you'll need to fix a couple things.

**Review by MathewMacDougall — APPROVED** [review]
LGTM :+1: :tada:

**Review by jonathanlew — APPROVED** [review]

**Pull request merged**
