### PR TITLE
ASCII Art added to field.h

### LINKED ISSUE #885: Add ASCII art to field.h to show how x/y corresponds to field dimensions
### Description of the task
Add ASCII art to field.h to show how x/y corresponds to long side and short side of the field

### Acceptance criteria

- [ ] ASCII art
- [ ] Item B
- [ ] Item C

### PR DESCRIPTION
**Pull request by phelanm20**
### Description

ASCII art added to field.h to illustrate the coordinate representation of the field and the location of the enemy and friendly sides.

### Testing Done

No testing was done, ascii art displayed in comments

### Resolved Issues

Resolves #885 

### Length Justification

n/a

### Review Checklist

**_It is the reviewers responsibility to also make sure every item here has been covered_**

- [x] **Function & Class comments**: All function definitions (usually in the `.h` file) should have a javadoc style comment at the start of them. For examples, see the functions defined in `thunderbots/software/geom`. Similarly, all classes should have an associated Javadoc comment explaining the purpose of the class.
- [x] **Remove all commented out code**
- [x] **Remove extra print statements**: for example, those just used for testing
- [x] **Resolve all TODO's**: All `TODO` (or similar) statements should either be completed or associated with a github issue
- [x] **Justify drops in code coverage**: If this PR results in a non-trivial drop in code coverage (a bot should post a coverage diagram as a comment), please justify why we can't test the code that's not covered.

### CODE REVIEW

**Review by garethellis0 — COMMENTED** [review]
LGTM, looks like there are all the changes from #1004 here as well, but no worries, as long as that merges first this should be fine. Not quite sure what happened, but just as a note for the future, make sure that when you're calling `git checkout -b MY-BRANCH-NAME` (for whatever your branch name is), you're on the `master` branch. If you're on branch `A` and create branch `B`, then `B` will have all the changes from `A` (again, totally no worries here though).

**Comment by garethellis0** [comment]
(just ping reviewers again once #1004 is merged and that should cut down the changes to just the Ascii art here)

**Comment by phelanm20** [comment]
Merge conflicts from issue #1004 were resolved! Waiting on Travis

**Comment by garethellis0** [comment]
Looks like we've still a conflict here :grimacing: - but it's not too bad!

**Comment by phelanm20** [comment]
All the conflicts are resolved now :)

**Comment by garethellis0** [comment]
Looks like github is still a bit confused, still seeing the print operator changes here as well. Could you:
- update your local `master` branch:
```
git checkout master
git pull upstream master
git push origin master # This is optional, just updates master on your fork while we're here
```
- merge in `master` to your `asciiArt` branch:
```
git checkout asciiArt
git merge master
git push
```

This should _hopefully_ force github to recognize that all the print operator changes were already merged (so the diff should just show the new ascii art in `field.h`). Sorry for the hassle on this!

**Comment by MathewMacDougall** [comment]
Yea I'm surprised github isn't warning about conflicts :thinking:

**Comment by phelanm20** [comment]
Passed the Travis check; only change showing up now is the ascii art. :)
Glad I learned how to fix merge conflicts on something this simple!

**Comment by MathewMacDougall** [comment]
@HaomiaoZ @hardik-ddod please review

**Review by hardik-ddod — APPROVED** [review]
Illustrates the coordinates convention well! Looks good!

**Review by garethellis0 — APPROVED** [review]
LGTM :+1: :tada:

**Review by HaomiaoZ — APPROVED** [review]
LGTM 👍

**Pull request merged**
