### PR TITLE
Implemented MoveSpinPrimitive for grsim backend

### LINKED ISSUE #95: grSim backend - Implement MoveSpin Primitive
[grSim](https://github.com/RoboCup-SSL/grSim) is the "standard" simulator for the SSL Division, and is the simulator we use.

Because we currently don't/can't simulate our robot's firmware, we need to re-create how we move and control the robots for the simulator. Rather than sending a Primitive command to a robot over radio, which will then be executed by the robot firmware in order to do whatever the command asks, we need to send different commands to the simulator to move the robots.

We already have the ability to send commands to the simulator with #12 . The ability to control a robot's movement is further abstracted by the motion controller developed in #9 . This imitates the bang-bang motion controller on our robots, so that robot's will speed up and slow down more realistically as the move in the simulator.

** Currently blocked by #9  **

The task here is to create a function/routine to implement our MoveSpin Primitive using this motion-controller abstraction, so this Primitive can be simulated. We need these primitive to work in the simulator so we can actually use the simulator for testing.

The spec for the MoveSpin Primitive can be found in #86 , and also in the MoveSpinPrimitive class from #89 

The MoveSpinPrimitive class will be the input. The exact place this code will go will be revised once #9 is merged, and we will update the ticket.

### PR DESCRIPTION
**Pull request by roark-z**
### Description

*Implemented visit function for move spin primitive in grsim_command_primitive_visitor.cpp*

### Resolved Issues

`resolves #95`

### Review Checklist

**_It is the reviewers responsibility to also make sure every item here has been covered_**

- [x] **Start of document comments**: each `.cpp` and `.h` file should have a comment at the start of it. See files in the `thunderbots/software/geom` folder for examples.
- [x] **Function comments**: All function definitions (usually in the `.h` file) should have a javadoc style comment at the start of them. For examples, see the classes defined in `thunderbots/software/geom`
- [x] **Remove all commented out code**
- [x] **Remove extra print statements**: for example, those just used for testing
- [x] **Resolve all TODO's**: All `TODO` (or similar) statements should either be completed or associated with a github issue
- [x] **Justify drops in code coverage**: If this PR results in a non-trivial drop in code coverage (a bot should post a coverage diagram as a comment), please justify why we can't test the code that's not covered.

### CODE REVIEW

**Comment by roark-z** [comment]
Is there a way to test the code using grsim?

**Comment by MathewMacDougall** [comment]
Have you run the primitive directly in grSim? We aren't currently set up to do any automatic integration tests, so you'll need to verify the behavior manually.

You should also write a few unit tests that check the returned `MotionControllerCommand`
Eg. Make a new test file like `test/grsim_command_primitive_visitor/move_spin_primitive.cpp`. An example test could look like:
* Create a `MoveSpinPrimitive` with some parameters
* Create a robot with some known state
* Create a `GrSimCommandPrimitiveVisitor` object using the Robot you created
* Call the `accept` function on the `MoveSpinPrimitive` and provide the `GrSimCommandPrimitiveVisitor`. This is what calls the `visit` function you implemented and generates a `MotionControllerCommand`
* Get the resultant `MotionControllerCommand` from the `GrsimCommandPrimitiveVisitor`
* Compare the `MotionControllerCommand` against an expected value for what you expect the `visit` function to return given that robot state
* Add unit tests that construct a robot to set its state, create a new GrSimCommandPrimitiveVisitor

**Comment by roark-z** [comment]
Okay, I've created the file, but upon trying to run it I get the following error:
```
Cannot specify link libraries for target
  "grsim_command_primitive_visitor_test," which is not built by this project.
```
I've done catkin_add_gtest and target_link_libraries in cmakelists.txt, so I'm not quite sure what the problem is. How can I fix this?

**Comment by MathewMacDougall** [comment]
Just guessing, is there a typo in the `grsim_command_primitive_visitor_test` where you add the test? Based on the error, it seems it's trying to link an executable that doesn't exist. Check the name used with `catkin_add_gtest` matches.

If that doesn't work, push your changes and I can take a better look.

**Comment by MathewMacDougall** [comment]
Let's take this to Slack.

**Comment by MathewMacDougall** [comment]
The issue with the `assignGoalie` function in the `Team` class throwing exceptions has been temporarily fixed in #288. Make sure to update your branch.

**Review by MathewMacDougall — DISMISSED** [review]
LGTM :+1:. How's it working in grsim?

**Review by MathewMacDougall — APPROVED** [review]

**Pull request merged**
