### PR TITLE
Old Firmware Robot Folder Structure Changes And Formatting

### PR DESCRIPTION
**Pull request by garethellis0**
### Description
There will likely be many more folder changes as this progresses, but this is intended to get the bulk of them in to ease the burden for future reviews.

### Testing Done
Need to test on the robot **DO NOT MERGE** until this is completed.

### Review Checklist

**_It is the reviewers responsibility to also make sure every item here has been covered_**

- [ ] **Function & Class comments**: All function definitions (usually in the `.h` file) should have a javadoc style comment at the start of them. For examples, see the functions defined in `thunderbots/software/geom`. Similarly, all classes should have an associated Javadoc comment explaining the purpose of the class.
- [ ] **Remove all commented out code**
- [ ] **Remove extra print statements**: for example, those just used for testing
- [ ] **Resolve all TODO's**: All `TODO` (or similar) statements should either be completed or associated with a github issue
- [ ] **Justify drops in code coverage**: If this PR results in a non-trivial drop in code coverage (a bot should post a coverage diagram as a comment), please justify why we can't test the code that's not covered.

### CODE REVIEW

**Comment by garethellis0** [comment]
Sorry for all the hassle with this one, we really should've done formatting in a separate PR, but it got somewhat intertwined. To see the renamed files you can use `git diff` and search for `rename`

**Comment by henryymliu** [comment]
If I'm not mistaken, the structure changes are adding util, control, io, and math subfolders? 

Probably not in the scope of this review, but it seems like it would also be a good opportunity to nuke all the `camera/*` files; they seem unused

**Comment by garethellis0** [comment]
Yeah that's well out of scope. Many PR's to come to update the old firmware to work with bazel / to build an abstraction layer that will be shared with new firmware.

**Review by MathewMacDougall — DISMISSED** [review]
:shipit: (after testing)

**Review by akhilveeraghanta — DISMISSED** [review]
My browser almost crashed loading this PR, LGTM

**Review by henryymliu — DISMISSED** [review]

**Review by jonathanlew — DISMISSED** [review]
LGTM!

**Comment by MathewMacDougall** [comment]
@garethellis0 need to fix formatting

**Comment by MathewMacDougall** [comment]
Tested successfully on a robot. :shipit:

**Review by MathewMacDougall — APPROVED** [review]

**Review by jonathanlew — APPROVED** [review]

**Review by henryymliu — APPROVED** [review]

**Pull request merged**
