### PR TITLE
Removed legacy protos

### PR DESCRIPTION
**Pull request by jonathanlew**
### Description
Removing legacy protos since they don't seem to do anything

### Testing Done
Regression Tests

### Review Checklist

**_It is the reviewers responsibility to also make sure every item here has been covered_**

- [x] **Function & Class comments**: All function definitions (usually in the `.h` file) should have a javadoc style comment at the start of them. For examples, see the functions defined in `thunderbots/software/geom`. Similarly, all classes should have an associated Javadoc comment explaining the purpose of the class.
- [x] **Remove all commented out code**
- [x] **Remove extra print statements**: for example, those just used for testing
- [x] **Resolve all TODO's**: All `TODO` (or similar) statements should either be completed or associated with a github issue
- [x] **Justify drops in code coverage**: If this PR results in a non-trivial drop in code coverage (a bot should post a coverage diagram as a comment), please justify why we can't test the code that's not covered.

### CODE REVIEW

**Review by garethellis0 — APPROVED** [review]
Seems fine to me, but @MathewMacDougall would know much better then me what these were for.

**Review by MathewMacDougall — APPROVED** [review]

**Comment by MathewMacDougall** [comment]
They were from before we moved from the refboxes to the full "gamecontroller", as well as some SSL vision changes that happened I think around 2017. I don't have much more context for _why_ these changes happened and generated entirely new protos, but I am pretty confident we don't need to support them now. As long as we can successfully talk to the most recent versions of SSL Vision and SSL Gamecontroller we should be fine.

2017-ish was when I think the transition was happening and so was more relevant to support the older ones then.

**Review by MathewMacDougall — CHANGES_REQUESTED** [review]
Actually if I remember right the new versions are very similar to the legacy ones, but with more information. However they are **not** backwards compatible. SSL Vision and the Gamecontroller did/do output the legacy versions still for comparability reasons.

Before this merges @jonathanlew can you double check we can talk to the Gamecontroller (just clone it and run it)? Or verify that we were unpacking the new protos not the old ones.

**Comment by jonathanlew** [comment]
> Actually if I remember right the new versions are very similar to the legacy ones, but with more information. However they are **not** backwards compatible. SSL Vision and the Gamecontroller did/do output the legacy versions still for comparability reasons.
> 
> Before this merges @jonathanlew can you double check we can talk to the Gamecontroller (just clone it and run it)? Or verify that we were unpacking the new protos not the old ones.

So I looked this up. Legacy protos are sent over port 10001 and non-legacy protos are sent over port 10003. We currently only listen to 10003 and we only look at the non-legacy GameController protos.
Confirmed that it works with ssl-refbox.

**Review by MathewMacDougall — APPROVED** [review]
Perfect, thanks for checking :+1:

**Pull request merged**
