### PR TITLE
Powerloop Auto Flashing

### PR DESCRIPTION
**Pull request by LiCody**
### Review Checklist

**_It is the reviewers responsibility to also make sure every item here has been covered_**

- [ ] **Function & Class comments**: All function definitions (usually in the `.h` file) should have a javadoc style comment at the start of them. For examples, see the functions defined in `thunderbots/software/geom`. Similarly, all classes should have an associated Javadoc comment explaining the purpose of the class.
- [ ] **Remove all commented out code**
- [ ] **Remove extra print statements**: for example, those just used for testing
- [ ] **Resolve all TODO's**: All `TODO` (or similar) statements should either be completed or associated with a github issue

### CODE REVIEW

**Comment by itsarune** [comment]
are we still putting effort into powerboard flashing through UI board? We can close this, if this is a 2023 project

**Comment by LiCody** [comment]
> are we still putting effort into powerboard flashing through UI board? We can close this, if this is a 2023 project

Mostly dont want to sit on the code any longer. current issue seems to be elec related (random resetting) so should be done on the software side.

**Comment by itsarune** [comment]
Okay sounds good, we can get this in so you don't have to worry about it when you graduate

**Comment by itsarune** [comment]
Closing because `elec` is too stretched to debug these electrical issues. Not a priority...

**Pull request closed without merging**
