### PR TITLE
Update documentation

### PR DESCRIPTION
**Pull request by matthewberends**
### Description
Update the docs to use the specify the correct directories.

### Review Checklist

**_It is the reviewers responsibility to also make sure every item here has been covered_**

- [x] **Function & Class comments**: All function definitions (usually in the `.h` file) should have a javadoc style comment at the start of them. For examples, see the functions defined in `thunderbots/software/geom`. Similarly, all classes should have an associated Javadoc comment explaining the purpose of the class.
- [x] **Remove all commented out code**
- [x] **Remove extra print statements**: for example, those just used for testing
- [x] **Resolve all TODO's**: All `TODO` (or similar) statements should either be completed or associated with a github issue
- [x] **Justify drops in code coverage**: If this PR results in a non-trivial drop in code coverage (a bot should post a coverage diagram as a comment), please justify why we can't test the code that's not covered.

### CODE REVIEW

**Comment by EvanMorcom** [comment]
:+1:

**Review by MathewMacDougall — APPROVED** [review]
:+1: Nice work remembering this

**Comment by MathewMacDougall** [comment]
@EvanMorcom you have to actually approve the PR

**Review by garethellis0 — APPROVED** [review]
:raised_hands: :pray: LGTM :+1: :tada:

**Pull request merged**
