### PR TITLE
Update Github Actions to Ubuntu 20

### LINKED ISSUE #2264: Switch CI to Use an Ubuntu 20 image
### Description of the task
Currently CI is checking Ubuntu 18, but we want to support Ubuntu 20 going forward

### Acceptance criteria

- [ ] as titled

### PR DESCRIPTION
**Pull request by jonathanlew**
### Description
Update Github Actions to Ubuntu 20
speed up CI by removing legacy firmware

### Testing Done
CI passes

### Resolved Issues
resolves #2264 

### Review Checklist

**_It is the reviewers responsibility to also make sure every item here has been covered_**

- [ ] **Function & Class comments**: All function definitions (usually in the `.h` file) should have a javadoc style comment at the start of them. For examples, see the functions defined in `thunderbots/software/geom`. Similarly, all classes should have an associated Javadoc comment explaining the purpose of the class.
- [ ] **Remove all commented out code**
- [ ] **Remove extra print statements**: for example, those just used for testing
- [ ] **Resolve all TODO's**: All `TODO` (or similar) statements should either be completed or associated with a github issue
- [ ] **Justify drops in code coverage**: If this PR results in a non-trivial drop in code coverage (a bot should post a coverage diagram as a comment), please justify why we can't test the code that's not covered.

### CODE REVIEW

**Review by Joshuayellowley — APPROVED** [review]
The changes look good to me!

**Review by akhilveeraghanta — COMMENTED** [review]
since we support both, should we run on both 18 and 20? it probably won't take up extra time if they run in parallel?

**Comment by jonathanlew** [comment]
There's a limit to the number of parallel jobs so it will become a problem when we have multiple PRs up

**Review by akhilveeraghanta — APPROVED** [review]
makes sense, should be fine then

**Pull request merged**
