### PR TITLE
[SSL Simulation Protocol]: Update networking libraries and add proto translation functions

### PR DESCRIPTION
**Pull request by akhilveeraghanta**
### Description
See title

### Testing Done
Unit tests, manual test
loading_grsim

### Resolved Issues
#2024 

### Length Justification

N/A
### Review Checklist

**_It is the reviewers responsibility to also make sure every item here has been covered_**

- [x] **Function & Class comments**: All function definitions (usually in the `.h` file) should have a javadoc style comment at the start of them. For examples, see the functions defined in `thunderbots/software/geom`. Similarly, all classes should have an associated Javadoc comment explaining the purpose of the class.
- [x] **Remove all commented out code**
- [x] **Remove extra print statements**: for example, those just used for testing
- [x] **Resolve all TODO's**: All `TODO` (or similar) statements should either be completed or associated with a github issue
- [x] **Justify drops in code coverage**: If this PR results in a non-trivial drop in code coverage (a bot should post a coverage diagram as a comment), please justify why we can't test the code that's not covered.

### CODE REVIEW

**Review by jonathanlew — COMMENTED** [review]
Looks pretty clean. Are things complete enough that we can document how to get things set up with grsim?

**Review by jsn0716 — APPROVED** [review]
LGTM 👍

**Comment by akhilveeraghanta** [comment]
> Looks pretty clean. Are things complete enough that we can document how to get things set up with grsim?

Unfortunately nope, it would have to come with a future update to adding full support

This just updates the networking lib and adds some translation stuff

**Review by kelvinkoon — APPROVED** [review]
:100:

**Review by jonathanlew — APPROVED** [review]

**Comment by jonathanlew** [comment]
looks like you need to merge in upstream/master to get the fw tests to pass

**Pull request merged**
