### PR TITLE
Report alternate build status

### PR DESCRIPTION
**Pull request by itsarune**
### Description

When #3316 went in, I didn't realize the multi-platform builds couldn't be set as a required status check. This will force it to be reported as a status check so that it can be set as a required passing check.

### Review Checklist

**_It is the reviewers responsibility to also make sure every item here has been covered_**

- [ ] **Function & Class comments**: All function definitions (usually in the `.h` file) should have a javadoc style comment at the start of them. For examples, see the functions defined in `thunderbots/software/geom`. Similarly, all classes should have an associated Javadoc comment explaining the purpose of the class.
- [ ] **Remove all commented out code**
- [ ] **Remove extra print statements**: for example, those just used for testing
- [ ] **Resolve all TODO's**: All `TODO` (or similar) statements should either be completed or associated with a github issue

### CODE REVIEW

**Comment by williamckha** [comment]
Is this necessary? I just added the alternate builds as required status checks for master:

image

**Comment by williamckha** [comment]
Also, is there any reason why we still have separate "Software Tests" and "Robot Software Tests" jobs that build on ubuntu 20.04? Can't we just add ubuntu 20.04 to the multiplatform-build job?

**Comment by itsarune** [comment]
Oh I didn't see those options earlier for some reason, thanks for checking

**Comment by itsarune** [comment]
The alternate builds only check for compilation but the software tests run all of the c++ and python tests.

When I first joined tbots, our CI pipelines would take ~3 hours so the decision to not run bazel test on 22.04 was just to save time.

Nowadays, our pipelines are way faster, so we could afford to run tests on all three OSes. I don't have any preference either way, so what do you think?

**Comment by williamckha** [comment]
> The alternate builds only check for compilation but the software tests run all of the c++ and python tests.
> 
> When I first joined tbots, our CI pipelines would take ~3 hours so the decision to not run bazel test on 22.04 was just to save time.
> 
> Nowadays, our pipelines are way faster, so we could afford to run tests on all three OSes. I don't have any preference either way, so what do you think?

Thinking about it more, I'd rather keep what we have currently so that we can keep the jobs smaller and parallelize them. It looks like building + testing both Software and Robot Software in the same job would take 45-60 mins, compared to our CI now which takes ~30 mins.

**Pull request closed without merging**
