### PR TITLE
Removed extra robot capabilities file

### PR DESCRIPTION
**Pull request by MathewMacDougall**
### Description

Found an extra file and removed it.

### Testing Done

Code builds

### Resolved Issues

None

### Review Checklist

**_It is the reviewers responsibility to also make sure every item here has been covered_**

- [x] **Function & Class comments**: All function definitions (usually in the `.h` file) should have a javadoc style comment at the start of them. For examples, see the functions defined in `thunderbots/software/geom`. Similarly, all classes should have an associated Javadoc comment explaining the purpose of the class.
- [x] **Remove all commented out code**
- [x] **Remove extra print statements**: for example, those just used for testing
- [x] **Resolve all TODO's**: All `TODO` (or similar) statements should either be completed or associated with a github issue
- [x] **Justify drops in code coverage**: If this PR results in a non-trivial drop in code coverage (a bot should post a coverage diagram as a comment), please justify why we can't test the code that's not covered.

### CODE REVIEW

**Review by EvanMorcom — APPROVED** [review]
👍

**Review by amrm3lm — APPROVED** [review]
lgtm

**Review by jonathanlew — APPROVED** [review]

**Review by garethellis0 — APPROVED** [review]
LGTM :+1: :tada:

**Comment by jordanzliu** [comment]
yep looks like this is a duplicate file of `software/world/robot_capabilities.h`, LGTM 💯

**Review by jordanzliu — APPROVED** [review]
Looks like this a duplicate of `software/world/robot_capabilities.h`, LGTM 💯

**Pull request merged**
