### PR TITLE
Bazel Support For STM32 MCU's

### PR DESCRIPTION
**Pull request by garethellis0**
### Description
Opening this PR because I'm pretty sure I totally broke codecov with https://github.com/UBC-Thunderbots/Software/pull/937.
- created a bazel toolchain with both `clang` and `arm-none-eabi-gcc`
- created a demo project for compiling firmware for `frankie_v1` (naming and restructuring of firmware can wait for another PR I think)
- added a script for writing the built firmware to the demo board and debugging it with gdb
- added a script to convert clangs code coverage results into something codecov can understand

### Description
Opening this PR because I'm pretty sure I totally broke codecov with https://github.com/UBC-Thunderbots/Software/pull/937.
- created a bazel toolchain with both `clang` and `arm-none-eabi-gcc`
- created a demo project for compiling firmware for `frankie_v1` (naming and restructuring of firmware can wait for another PR I think)
- added a script for writing the built firmware to the demo board and debugging it with gdb
- added a script to convert clangs code coverage results into something codecov can understand

### Testing Done
Code can build, and be flash and debugged on the stm23h7 demo board

### Length Justification
Toolchain is massive, demo project is pretty massive (but should require minimal review).

### Review Checklist

**_It is the reviewers responsibility to also make sure every item here has been covered_**

- [x] **Function & Class comments**: All function definitions (usually in the `.h` file) should have a javadoc style comment at the start of them. For examples, see the functions defined in `thunderbots/software/geom`. Similarly, all classes should have an associated Javadoc comment explaining the purpose of the class.
- [x] **Remove all commented out code**
- [x] **Remove extra print statements**: for example, those just used for testing

### CODE REVIEW

**Comment by garethellis0** [comment]
@MathewMacDougall @jonathanlew - the main thing to review here is the `convert_profdata_to_lcov.sh` script, everything else is basically the same (though I would appreciate a quick overall sanity check to make sure I didn't totally bugger anything else).

**Review by jonathanlew — COMMENTED** [review]
Is this the codecov? https://codecov.io/gh/UBC-Thunderbots/Software/tree/3767f2fbf361ef41438b4f3db2ada6e06350b719/src/software Why isn't it showing up in the PR?

**Comment by garethellis0** [comment]
I was waiting to see if it showed up, gonna open one more totally clean PR which should get it..........

**Comment by garethellis0** [comment]
*sigh* looks like codecov got knackered somehow. I've seen similar issues before when there is odd stuff happening between `master` and a branch. Currently I'm inclined to merge, and that _should_ fix it...........

**Comment by garethellis0** [comment]
Other things to note about coverage:
- we're now counting tests in the line count
- we seem to be counting some comments in the line count

Both of these are definitely regressions, and I am ***extremely*** unhappy about that. However I really don't think we can do much better, and code coverage should still serve as a good indicator where we need to improve. 

We're waiting for bazel to get their stuff together, there are several tickets open right now, and the resolution of any of them should clear things up.

**Comment by garethellis0** [comment]
After offline discussion with Mat, we've agreed that the ideal would be to redo the toolchain for a version of gcc that bazel supports for coverage (see this issue: https://github.com/bazelbuild/bazel/issues/7719), but we need to get this in ASAP to unblock elec, and it's functional, so it will have to do for now.

**Review by MathewMacDougall — APPROVED** [review]

**Review by jonathanlew — APPROVED** [review]

**Pull request merged**
