### PR TITLE
Fix visualizer not drawing world

### PR DESCRIPTION
**Pull request by MathewMacDougall**
### Description

This PR fixes the long-standing issue of the Visualizer not drawing the World at all. The issue was with the buffers we use to pass data between our `VisualizerWrapper` and `Visualizer`, which run on different threads.

The buffer sizes were `const` member variables of the class, and initialized directly in the header where they were declared. Because the buffers are created in the initializer list of the class constructor, those buffer size values were not actually initialized by the time the buffers were getting created (since the class didn't exist yet), and so the buffers all were created with a size of 0. This resulted in no data getting passed to the Visualizer so it didn't draw anything.

It seems like the change in compilers was still what exposed this issue, because this technically shouldn't have worked before. I solved the issue by making the buffer size variables `static constexpr` so they are initialized well before the class is created.

This pattern of assigning values to private const member variables in classes in used elsewhere in the code and should be fixed as well. We need to decide what solution we prefer, and should see if we can add compiler flags to prevent this again.

**Solution 1**
Declare variables as `static constexpr` in the class

**Solution 2**
Initialize the variables in the initializer list (before they are used)

Please leave feedback as to which is preferred. I think solution 1 is slightly more correct since the variables are the same for all instances of the class and don't belong to a particular instance.

### Testing Done

Manually verified drawing works as expected

### Resolved Issues

None

### Review Checklist

**_It is the reviewers responsibility to also make sure every item here has been covered_**

- [x] **Function & Class comments**: All function definitions (usually in the `.h` file) should have a javadoc style comment at the start of them. For examples, see the functions defined in `thunderbots/software/geom`. Similarly, all classes should have an associated Javadoc comment explaining the purpose of the class.
- [x] **Remove all commented out code**
- [x] **Remove extra print statements**: for example, those just used for testing
- [x] **Resolve all TODO's**: All `TODO` (or similar) statements should either be completed or associated with a github issue
- [x] **Justify drops in code coverage**: If this PR results in a non-trivial drop in code coverage (a bot should post a coverage diagram as a comment), please justify why we can't test the code that's not covered.

### CODE REVIEW

**Review by garethellis0 — APPROVED** [review]
Agree with first solution. LGTM :+1: :tada:

**Review by akhilveeraghanta — APPROVED** [review]
LGTM

**Review by LiCody — APPROVED** [review]
LGTM

**Review by jonathanlew — APPROVED** [review]
So happy you fixed this! :100: :fire: :rocket: 
(I agree with the first solution)

**Comment by MathewMacDougall** [comment]
Fixed CI :tm: will need re-approval

**Pull request merged**
