### PR TITLE
Assigned 'ball_steal_speed' in 'shadow_enemy_tactic.cpp' and fixed related bug

### LINKED ISSUE #886: Assign `ball_steal_speed` in `ShadowEnemyTactic` and fix `ShadowEnemyTacticTest`
### Description of the task

In `ShadowEnemyTactic`, the parameter `ball_steal_speed` is passed into the constructor but not assigned. Changing it to be assigned to the class member `ball_steal_speed` causes the `ShadowEnemyTacticTest` to fail.

Change the constructor to assign `ball_steal_speed`, then figure out and correct the cause of the test failure.

### Acceptance criteria

- [ ] Assign `ball_steal_speed`
- [ ] Figure out why `ShadowEnemyTacticTest` is failing

### PR DESCRIPTION
**Pull request by hardik-ddod**
### Description
- Assigned `ball_steal_speed` in the constructor
- Fixed bug causing failing test after assignment in constructor.  The inequality on line 114 was strict, causing the friendly robot to not steal when the `ball_steal_speed` and the speed of the ball were equal.  Modified it so it is no longer strict.

### Testing Done
- Made sure all tests pass after modification.  Nothing other than that as the change wasn't that monumental.

### Resolved Issues
Resolves #886 

### Review Checklist

**_It is the reviewers responsibility to also make sure every item here has been covered_**

- [x] **Function & Class comments**: All function definitions (usually in the `.h` file) should have a javadoc style comment at the start of them. For examples, see the functions defined in `thunderbots/software/geom`. Similarly, all classes should have an associated Javadoc comment explaining the purpose of the class.
- [x] **Remove all commented out code**
- [x] **Remove extra print statements**: for example, those just used for testing
- [x] **Resolve all TODO's**: All `TODO` (or similar) statements should either be completed or associated with a github issue
- [x] **Justify drops in code coverage**: If this PR results in a non-trivial drop in code coverage (a bot should post a coverage diagram as a comment), please justify why we can't test the code that's not covered.

### CODE REVIEW

**Comment by hardik-ddod** [comment]
@jsn0716 please have a look!

**Review by MathewMacDougall — APPROVED** [review]
LGTM :+1: Nice work finding this.

**Comment by MathewMacDougall** [comment]
Hopefully @amrm3lm 's fixes for compiler warnings will help prevent uninitialized variables in the future?

**Comment by hardik-ddod** [comment]
@akhilveeraghanta

**Review by jsn0716 — APPROVED** [review]
LGTM! 👍

**Pull request merged**
