### PR TITLE
Modify point functions to be valid constexpr functions

### LINKED ISSUE #961: Fix Invalid Const Expressions In The Point Class
### Description of the task
Currently we have functions in the `Point` class that are declared `constexpr`, but use non-constexpr expressions in them. This causes compilation failures when using clang:
```
./software/geom/point.h:470:30: error: constexpr function never produces a constant expression [-Winvalid-constexpr]
inline constexpr bool Point::isnan() const
                             ^
./software/geom/point.h:472:12: note: non-constexpr function 'isnan' cannot be used in a constant expression
    return std::isnan(_x) || std::isnan(_y);
           ^
external/llvm_clang/bin/../include/c++/v1/math.h:539:1: note: declared here
isnan(double __lcpp_x) _NOEXCEPT { return __libcpp_isnan(__lcpp_x); }
^
In file included from software/geom/polygon.cpp:1:
In file included from ./software/geom/polygon.h:5:
In file included from ./software/geom/ray.h:5:
In file included from ./software/geom/line.h:3:
./software/geom/point.h:480:30: error: constexpr function never produces a constant expression [-Winvalid-constexpr]
inline constexpr bool Point::isClose(const Point &other, double dist) const
                             ^
./software/geom/point.h:482:12: note: non-constexpr function 'pow<double, int>' cannot be used in a constant expression
    return std::pow(_x - other.x(), 2) + std::pow(_y - other.y(), 2) < dist * dist;
           ^
external/llvm_clang/bin/../include/c++/v1/math.h:1039:1: note: declared here
pow(_A1 __lcpp_x, _A2 __lcpp_y) _NOEXCEPT
```

### Acceptance criteria

- [ ] Remove the `-Wno-invalid-constexpr` flag in `cc_toolchain_config.bzl`
- [ ] Compile `//...` and fix all resulting errors

### PR DESCRIPTION
**Pull request by matthewberends**
### Description

Some constexpr function in Point used std functions which make them invalid constexpr. This PR modifies the implementations to make them valid

### Testing Done

Ran tests.

### Resolved Issues

resolves #961 

### Review Checklist

**_It is the reviewers responsibility to also make sure every item here has been covered_**

- [x] **Function & Class comments**: All function definitions (usually in the `.h` file) should have a javadoc style comment at the start of them. For examples, see the functions defined in `thunderbots/software/geom`. Similarly, all classes should have an associated Javadoc comment explaining the purpose of the class.
- [x] **Remove all commented out code**
- [x] **Remove extra print statements**: for example, those just used for testing
- [x] **Resolve all TODO's**: All `TODO` (or similar) statements should either be completed or associated with a github issue
- [x] **Justify drops in code coverage**: If this PR results in a non-trivial drop in code coverage (a bot should post a coverage diagram as a comment), please justify why we can't test the code that's not covered.

### CODE REVIEW

**Review by jsn0716 — DISMISSED** [review]
LGTM 👍 Note that `Point` is currently being moved / modified to `new_geom` in #970, so this fix would need to be reapplied (`isnan` was removed in `new geom`)

**Review by MathewMacDougall — DISMISSED** [review]
LGTM, but yea we'll need to wait for #970 to merge first

**Review by garethellis0 — COMMENTED** [review]
@scveloso - FYI

**Comment by MathewMacDougall** [comment]
If we're removing `constexpr` in #970 do we still want/need these changes?

**Comment by garethellis0** [comment]
Great point. I think that specifying things this way will allow the compiler to be more aggressive in it's optimizations, so I think it's still worth it, but I don't have any sources to support this.

**Review by garethellis0 — APPROVED** [review]
LGTM :+1: :tada:

**Review by MathewMacDougall — APPROVED** [review]

**Pull request merged**
