### PR TITLE
Rename backend nodes

### LINKED ISSUE #156: Rename backend_input node to network_input
**Is your feature request or enhancement related to a problem? What specifically could be better? Please describe.**
After discussion today, the `backend_input` node should be renamed to the `network_input` node as it will be only responsible for handling data received over the network (vision data and refbox commands).

**Describe the solution you'd like**
Rename the `backend_input` node to `network_input`

**Describe alternatives you've considered**
N/A

**Additional context**
`backend_input was originally planned to handle _ALL_ data input to the system, but it makes more sense (and is easier) for radio communication to be handles by a separate node. So this name change reflects the new responsibilities of the network node.

### PR DESCRIPTION
**Pull request by MathewMacDougall**
### Description
*Give a high-level description of the changes in this PR*
Renamed `backend_input` node to `network_input` to more accurately reflect its role in the system.
Renamed `backend_output` node to `robot_communication` to more accurately reflect its role in the system.

I'm aware these diffs might appear quite large, but I decided to do the renaming for both nodes in the same PR since the changes are non-technical so review should be quick.

### Testing Done
*Outline any testing that was done for these changes. This could be unit tests, integration tests, etc.*
N/A

### Resolved Issues
*Link any issues that this PR resolved. Eg `resolves #1, #2, and #5` (note that they MUST be specified like this so Github can automatically close them then this PR merges)*
resolves #156 and #157 

### Review Checklist
*(Please check every item to indicate your code complies with it (by changing `[ ]`->`[x]`). This will hopefully save both you and the reviewer(s) a lot of time!)*
***It is the reviewers responsibility to also make sure every item here has been covered***
- [x] **Start of document comments**: each `.cpp` and `.h` file should have a comment at the start of it. See files in the `thunderbots/software/geom` folder for examples.
- [x] **Function comments**: All function definitions (usually in the `.h` file) should have a javadoc style comment at the start of them. For examples, see the classes defined in `thunderbots/software/geom` 
- [x] **Remove all commented out code**
- [x] **Remove extra print statements**: for example, those just used for testing
- [x] **Resolve all TODO's**: All `TODO` (or similar) statements should either be completed or associated with a github issue
- [x] **Justify drops in code coverage**: If this PR results in a non-trivial drop in code coverage (a bot should post a coverage diagram as a comment), please justify why we can't test the code that's not covered.

***Feel free to make additions of things that we should be checking to this file if you think there's something missing!!!!***

### CODE REVIEW

**Review by garethellis0 — DISMISSED** [review]
LGTM :+1: :tada: - but looks like formatting checks are failing in CI

**Comment by MathewMacDougall** [comment]
Formatting should be fixed

**Review by b-a-l — APPROVED** [review]
As far as I can tell, looks good!

**Review by garethellis0 — APPROVED** [review]

**Review by henryymliu — APPROVED** [review]
...this is going to be fun to merge into my branch

**Comment by MathewMacDougall** [comment]
RIP @henrymliu :skull:

**Pull request merged**
