### PR TITLE
Removed unused BlockShotPathTactic and GrabBallTactic

### LINKED ISSUE #785: Remove any unused Tactics
### Description of the task

After the flurry of strategy changes at RoboCup this year, there may be tactics that are no longer used and are unlikely to be useful in the future. We should identify any such tactics and remove them.

### Acceptance criteria

- [ ] Remove any tactics that are unused and not likely to be used in the future

### Blocked By

This may need to be completed in tandem with #786

### PR DESCRIPTION
**Pull request by MathewMacDougall**
* Removed BlockShotPathTactic
* Removed GrabBallTactic

### Description

Removed unused tactics in our AI

### Testing Done

All tests pass

### Resolved Issues

resolves #785 

### Length Justification

3 tactics is a lot of code (including the tests and visitors).

### Review Checklist

**_It is the reviewers responsibility to also make sure every item here has been covered_**

- [x] **Function & Class comments**: All function definitions (usually in the `.h` file) should have a javadoc style comment at the start of them. For examples, see the functions defined in `thunderbots/software/geom`. Similarly, all classes should have an associated Javadoc comment explaining the purpose of the class.
- [x] **Remove all commented out code**
- [x] **Remove extra print statements**: for example, those just used for testing
- [x] **Resolve all TODO's**: All `TODO` (or similar) statements should either be completed or associated with a github issue
- [x] **Justify drops in code coverage**: If this PR results in a non-trivial drop in code coverage (a bot should post a coverage diagram as a comment), please justify why we can't test the code that's not covered.

### CODE REVIEW

**Review by EvanMorcom — DISMISSED** [review]
LGTM :100:

**Review by garethellis0 — DISMISSED** [review]
LGTM :+1: :tada:

**Review by jonathanlew — CHANGES_REQUESTED** [review]
In https://github.com/UBC-Thunderbots/Software/compare/robocup_2019 ShootOrChipPlay uses the PatrolTactic. Do we plan to port that over?

**Comment by jonathanlew** [comment]
Are we arguing that:
1. The cost of maintaining this code > cost of rewriting
2. We don't plan to re-implement/integrate any of the tactics this year
3. The code has so little value that it would not be useful as a starting point
4. It is useful, so we will tag the commit before removal so we can reference it if we need it
or some combination?

**Comment by garethellis0** [comment]
We're really just saying that we're not using these currently, have really minimal test coverage / faith in them, and they're always there in the git history if anyone really needs them. 

@MathewMacDougall - can you make the title of this PR more explicit (`Removed TacticA, TacticB, TacticC Because They Are Unused`)? That should make it easy enough to find this commit in the future.

**Comment by MathewMacDougall** [comment]
> 1. The cost of maintaining this code > cost of rewriting

Yes. YAGNI

> 2. We don't plan to re-implement/integrate any of the tactics this year

No, just they're not very useful right now. Some form of GrabBall will likely be re-written with a significantly different approach since interception is a big goal this year.
> 3. The code has so little value that it would not be useful as a starting point

Somewhat. It's in the history if people really want to look, and I expect the approaches to change somewhat (as well as the STP refactor will make things different). I've also never personally seen a case where I've dug through history to find old tactics to base new logic off of.
> 4. It is useful, so we will tag the commit before removal so we can reference it if we need it

I generally don't think people will be looking back, and don't think tags make things much easier in that case. I'd rather reserve tags for _really_ big milestones like robocup code.

**Comment by jonathanlew** [comment]
> > 1. The cost of maintaining this code > cost of rewriting
> 
> Yes. YAGNI
> 
> > 1. We don't plan to re-implement/integrate any of the tactics this year
> 
> No, just they're not very useful right now. Some form of GrabBall will likely be re-written with a significantly different approach since interception is a big goal this year.
> 
> > 1. The code has so little value that it would not be useful as a starting point
> 
> Somewhat. It's in the history if people really want to look, and I expect the approaches to change somewhat (as well as the STP refactor will make things different). I've also never personally seen a case where I've dug through history to find old tactics to base new logic off of.
> 
> > 1. It is useful, so we will tag the commit before removal so we can reference it if we need it
> 
> I generally don't think people will be looking back, and don't think tags make things much easier in that case. I'd rather reserve tags for _really_ big milestones like robocup code.

That clears things up for me. Makes sense!

**Review by amrm3lm — DISMISSED** [review]
lgtm

**Review by garethellis0 — COMMENTED** [review]
Are we still  getting rid of `PatrolTactic` here?

**Comment by MathewMacDougall** [comment]
No I need to update this PR still to keep PatrolTactic and update the ShootorChip play

**Comment by MathewMacDougall** [comment]
Restored the PatrolTactic and updated ShootOrChipPlay to use the PatrolTactic so it always returns 6 robots (previously could return 4 if no good open areas were found on the field).

**Review by garethellis0 — APPROVED** [review]
LGTM :+1: :tada:

**Review by jonathanlew — APPROVED** [review]
Just make sure the commit message for this PR doesn't include removing the PatrolTactic. :+1:

**Pull request merged**
