### PR TITLE
add firewall exception instructions for VcXsrv

### LINKED ISSUE #1781: WSL2 install - X server needs firewall exception to be configured during setup
### Description of the task

Guide needs to be changed to add firewall exception instructions

### Acceptance criteria

- [ ] Guide needs to be changed to add firewall exception instructions

### PR DESCRIPTION
**Pull request by jordanzliu**
### Description

Add instructions to create a firewall exception to WSL setup guide.

### Testing Done

Copied from a guide @nimazareian sent me which he said worked for him.

### Resolved Issues

Resolves #1781 

### Review Checklist

**_It is the reviewers responsibility to also make sure every item here has been covered_**

- [x] **Function & Class comments**: All function definitions (usually in the `.h` file) should have a javadoc style comment at the start of them. For examples, see the functions defined in `thunderbots/software/geom`. Similarly, all classes should have an associated Javadoc comment explaining the purpose of the class.
- [x] **Remove all commented out code**
- [x] **Remove extra print statements**: for example, those just used for testing
- [x] **Resolve all TODO's**: All `TODO` (or similar) statements should either be completed or associated with a github issue
- [x] **Justify drops in code coverage**: If this PR results in a non-trivial drop in code coverage (a bot should post a coverage diagram as a comment), please justify why we can't test the code that's not covered.

### CODE REVIEW

**Review by jonathanlew — COMMENTED** [review]
maybe add a bit of context, otherwise looks good

**Review by jonathanlew — COMMENTED** [review]
LGTM pending review from @nimazareian and/or @JoshuaWu7

**Review by nimazareian — COMMENTED** [review]
LGTM, I believe the main trick is to allow access to both public and private network. Though when I was faced with this issue I allowed access by going to "Windows Defender Firewall with Advanced Security", then in the bar on the left I clicked on "Inbound Rules". After a few seconds once all of the Inbound Rules had loaded, I found "VcXsrv windows xserver" in the list. There will be multiple rules (two for private and two for public) and I double clicked on the ones that had a red stop sign next to the rules and "Allow the connection". At the end all 4 "VcXsrv windows xserver" rules in the list should have a green check mark next to them showing that it now has access to public and private network. 
Those are the steps I followed, but I believe that the steps Jordan has written will also achieve the same result (allowing network access through firewall).

**Comment by jonathanlew** [comment]
still waiting for an approval by @nimazareian and/or @JoshuaWu7

**Review by nimazareian — APPROVED** [review]

**Review by jonathanlew — APPROVED** [review]

**Pull request merged**
