### PR TITLE
Fix team not responding after transitioning out of penalty kick

### LINKED ISSUE #2932: [Gameplay] Team stops responding after transitioning out of penalty kick
### Description of the task

After a penalty kick for the yellow team fails (timeout after 10 seconds), the yellow robots stop responding and stop receiving protos. I got the following SIGABRT:

```
2023/06/10 18:06:17 Engine: Process change '{"origin":"UI","revertible":true,"newCommand":{"command":{"type":"PENALTY","forTeam":"YELLOW"}}}'
2023/06/10 18:06:17 Processing change '{"origin":"UI","revertible":true,"newCommand":{"command":{"type":"PENALTY","forTeam":"YELLOW"}}}'
2023/06/10 18:06:17 Change '{"origin":"UI","revertible":true,"newCommand":{"command":{"type":"PENALTY","forTeam":"YELLOW"}}}' processed:
from: {"stage":"NORMAL_FIRST_HALF","command":{"type":"FORCE_START","forTeam":"UNKNOWN"},"gameState":{"type":"RUNNING"},"stageTimeElapsed":"116.023724221s","stageTimeLeft":"183.976275779s","matchTimeStart":"2023-06-11T00:10:17.887160822Z","teamState":{"BLUE":{"name":"Unknown","goals":0,"goalkeeper":0,"timeoutsLeft":4,"timeoutTimeLeft":"300s","onPositiveHalf":false,"ballPlacementFailures":0,"ballPlacementFailuresReached":false,"canPlaceBall":true,"maxAllowedBots":11,"challengeFlags":3},"YELLOW":{"name":"Unknown","goals":0,"goalkeeper":0,"timeoutsLeft":4,"timeoutTimeLeft":"300s","onPositiveHalf":true,"ballPlacementFailures":0,"ballPlacementFailuresReached":false,"canPlaceBall":true,"maxAllowedBots":11,"challengeFlags":3}},"currentActionTimeRemaining":"-4.132607370s","division":"DIV_A","autoContinue":true,"firstKickoffTeam":"YELLOW","matchType":"UNKNOWN_MATCH"}
  to: {"stage":"NORMAL_FIRST_HALF","command":{"type":"PENALTY","forTeam":"YELLOW"},"gameState":{"type":"PENALTY","forTeam":"YELLOW"},"stageTimeElapsed":"116.023724221s","stageTimeLeft":"183.976275779s","matchTimeStart":"2023-06-11T00:10:17.887160822Z","teamState":{"BLUE":{"name":"Unknown","goals":0,"goalkeeper":0,"timeoutsLeft":4,"timeoutTimeLeft":"300s","onPositiveHalf":false,"ballPlacementFailures":0,"ballPlacementFailuresReached":false,"canPlaceBall":true,"maxAllowedBots":11,"challengeFlags":3},"YELLOW":{"name":"Unknown","goals":0,"goalkeeper":0,"timeoutsLeft":4,"timeoutTimeLeft":"300s","onPositiveHalf":true,"ballPlacementFailures":0,"ballPlacementFailuresReached":false,"canPlaceBall":true,"maxAllowedBots":11,"challengeFlags":3}},"nextCommand":{"type":"NORMAL_START","forTeam":"UNKNOWN"},"currentActionTimeRemaining":"10s","division":"DIV_A","autoContinue":true,"firstKickoffTeam":"YELLOW","matchType":"UNKNOWN_MATCH"}
2023/06/10 18:06:17 Add entry to state store
2023/06/10 18:06:17 Notify hook  messageGen
2023/06/10 18:06:17 Notify hook  apiServer-4f0f3a77-016c-419b-a77c-0446e9e16024
2023/06/10 18:06:17 Change produced 0 new changes
2023/06/10 18:06:17 Change '{"origin":"UI","revertible":true,"newCommand":{"command":{"type":"PENALTY","forTeam":"YELLOW"}}}' processed
2023/06/10 18:06:21 Engine: Process change '{"origin":"UI","revertible":true,"newCommand":{"command":{"type":"NORMAL_START","forTeam":"UNKNOWN"}}}'
2023/06/10 18:06:21 Processing change '{"origin":"UI","revertible":true,"newCommand":{"command":{"type":"NORMAL_START","forTeam":"UNKNOWN"}}}'
2023/06/10 18:06:21 Change '{"origin":"UI","revertible":true,"newCommand":{"command":{"type":"NORMAL_START","forTeam":"UNKNOWN"}}}' processed:
from: {"stage":"NORMAL_FIRST_HALF","command":{"type":"PENALTY","forTeam":"YELLOW"},"gameState":{"type":"PENALTY","forTeam":"YELLOW"},"stageTimeElapsed":"116.023724221s","stageTimeLeft":"183.976275779s","matchTimeStart":"2023-06-11T00:10:17.887160822Z","teamState":{"BLUE":{"name":"Unknown","goals":0,"goalkeeper":0,"timeoutsLeft":4,"timeoutTimeLeft":"300s","onPositiveHalf":false,"ballPlacementFailures":0,"ballPlacementFailuresReached":false,"canPlaceBall":true,"maxAllowedBots":11,"challengeFlags":3},"YELLOW":{"name":"Unknown","goals":0,"goalkeeper":0,"timeoutsLeft":4,"timeoutTimeLeft":"300s","onPositiveHalf":true,"ballPlacementFailures":0,"ballPlacementFailuresReached":false,"canPlaceBall":true,"maxAllowedBots":11,"challengeFlags":3}},"nextCommand":{"type":"NORMAL_START","forTeam":"UNKNOWN"},"currentActionTimeRemaining":"10s","division":"DIV_A","autoContinue":true,"firstKickoffTeam":"YELLOW","matchType":"UNKNOWN_MATCH"}
  to: {"stage":"NORMAL_FIRST_HALF","command":{"type":"NORMAL_START","forTeam":"UNKNOWN"},"gameState":{"type":"PENALTY","forTeam":"YELLOW"},"stageTimeElapsed":"116.023724221s","stageTimeLeft":"183.976275779s","matchTimeStart":"2023-06-11T00:10:17.887160822Z","teamState":{"BLUE":{"name":"Unknown","goals":0,"goalkeeper":0,"timeoutsLeft":4,"timeoutTimeLeft":"300s","onPositiveHalf":false,"ballPlacementFailures":0,"ballPlacementFailuresReached":false,"canPlaceBall":true,"maxAllowedBots":11,"challengeFlags":3},"YELLOW":{"name":"Unknown","goals":0,"goalkeeper":0,"timeoutsLeft":4,"timeoutTimeLeft":"300s","onPositiveHalf":true,"ballPlacementFailures":0,"ballPlacementFailuresReached":false,"canPlaceBall":true,"maxAllowedBots":11,"challengeFlags":3}},"currentActionTimeRemaining":"10s","division":"DIV_A","autoContinue":true,"firstKickoffTeam":"YELLOW","matchType":"UNKNOWN_MATCH"}
2023/06/10 18:06:21 Add entry to state store
2023/06/10 18:06:21 Notify hook  messageGen
2023/06/10 18:06:21 Notify hook  apiServer-4f0f3a77-016c-419b-a77c-0446e9e16024
2023/06/10 18:06:21 Change produced 0 new changes
2023/06/10 18:06:21 Change '{"origin":"UI","revertible":true,"newCommand":{"command":{"type":"NORMAL_START","forTeam":"UNKNOWN"}}}' processed
2023/06/10 18:06:25 594793     CONTRACT [tactic.cpp->get:42]
        *******  EXIT trigger caused by broken Contract: CHECK(static_cast<bool>(primitive))
        "Primitive for PenaltyKickTactic in state KickFSM.GetBehindBallFSM.GetBehindBallState was not set

******* STACKDUMP *******
        stack dump [1]  software/unix_full_system+0x81f0cf [0x55a9c6b0f0cf]
        stack dump [2]  software/unix_full_system+0x2da811 [0x55a9c65ca811]
        stack dump [3]  software/unix_full_system+0x1b2db4 [0x55a9c64a2db4]
        stack dump [4]  software/unix_full_system+0x1b3116 [0x55a9c64a3116]
        stack dump [5]  software/unix_full_system+0x1b1e36 [0x55a9c64a1e36]
        stack dump [6]  software/unix_full_system+0xd275f [0x55a9c63c275f]
        stack dump [7]  software/unix_full_system+0xb5ced [0x55a9c63a5ced]
        stack dump [8]  software/unix_full_system+0xb5b53 [0x55a9c63a5b53]
        stack dump [9]  software/unix_full_system+0xbf304 [0x55a9c63af304]
        stack dump [10]  software/unix_full_system+0xd0c43 [0x55a9c63c0c43]
        stack dump [11]  software/unix_full_system+0xd0207 [0x55a9c63c0207]
        stack dump [12]  software/unix_full_system+0xcf9d2 [0x55a9c63bf9d2]
        stack dump [13]  software/unix_full_system+0xcec9c [0x55a9c63bec9c]
        stack dump [14]  software/unix_full_system+0xcd5fc [0x55a9c63bd5fc]
        stack dump [15]  software/unix_full_system+0xcc73a [0x55a9c63bc73a]
        stack dump [16]  software/unix_full_system+0xcbba0 [0x55a9c63bbba0]
        stack dump [17]  software/unix_full_system+0xcb242 [0x55a9c63bb242]
        stack dump [18]  software/unix_full_system+0x9012d4 [0x55a9c6bf12d4]
        stack dump [19]  /lib/x86_64-linux-gnu/libpthread.so.0+0x8609 [0x7f58f0ff8609]
        stack dump [20]  /lib/x86_64-linux-gnu/libc.so.6clone+0x43 [0x7f58f0dbe133]

Exiting after fatal event  (CONTRACT). Fatal type:  SIGABRT
Log content flushed sucessfully to sink

"2023/06/10 18:06:25 594793     CONTRACT [tactic.cpp->get:42]
        *******  EXIT trigger caused by broken Contract: CHECK(static_cast<bool>(primitive))
        "Primitive for PenaltyKickTactic in state KickFSM.GetBehindBallFSM.GetBehindBallState was not set

******* STACKDUMP *******
        stack dump [1]  software/unix_full_system+0x81f0cf [0x55a9c6b0f0cf]
        stack dump [2]  software/unix_full_system+0x2da811 [0x55a9c65ca811]
        stack dump [3]  software/unix_full_system+0x1b2db4 [0x55a9c64a2db4]
        stack dump [4]  software/unix_full_system+0x1b3116 [0x55a9c64a3116]
        stack dump [5]  software/unix_full_system+0x1b1e36 [0x55a9c64a1e36]
        stack dump [6]  software/unix_full_system+0xd275f [0x55a9c63c275f]
        stack dump [7]  software/unix_full_system+0xb5ced [0x55a9c63a5ced]
        stack dump [8]  software/unix_full_system+0xb5b53 [0x55a9c63a5b53]
        stack dump [9]  software/unix_full_system+0xbf304 [0x55a9c63af304]
        stack dump [10]  software/unix_full_system+0xd0c43 [0x55a9c63c0c43]
        stack dump [11]  software/unix_full_system+0xd0207 [0x55a9c63c0207]
        stack dump [12]  software/unix_full_system+0xcf9d2 [0x55a9c63bf9d2]
        stack dump [13]  software/unix_full_system+0xcec9c [0x55a9c63bec9c]
        stack dump [14]  software/unix_full_system+0xcd5fc [0x55a9c63bd5fc]
        stack dump [15]  software/unix_full_system+0xcc73a [0x55a9c63bc73a]
        stack dump [16]  software/unix_full_system+0xcbba0 [0x55a9c63bbba0]
        stack dump [17]  software/unix_full_system+0xcb242 [0x55a9c63bb242]
        stack dump [18]  software/unix_full_system+0x9012d4 [0x55a9c6bf12d4]
        stack dump [19]  /lib/x86_64-linux-gnu/libpthread.so.0+0x8609 [0x7f58f0ff8609]
        stack dump [20]  /lib/x86_64-linux-gnu/libc.so.6clone+0x43 [0x7f58f0dbe133]

Exiting after fatal event  (CONTRACT). Fatal type:  SIGABRT
Log content flushed sucessfully to sink

" 
Exiting, log location: /tmp/tbots/yellow/thunderbots.log

Exiting, log location: /tmp/tbots/yellow/thunderbots_filtered.log

Exiting, log location: /tmp/tbots/yellow/thunderbots_text.log


exitWithDefaultSignalHandler:229. Exiting due to CONTRACT, 6   

2023-06-10 18:06:27,332 - [WARNING] - [Thread-49] - root - (threaded_unix_sender.py).__send_protobuf(63) - Failed to send on /tmp/tbots/yellow/ssl_wrapper, make sure the receiver is running
2023-06-10 18:06:27,334 - [WARNING] - [Thread-48] - root - (threaded_unix_sender.py).__send_protobuf(63) - Failed to send on /tmp/tbots/yellow/robot_status, make sure the receiver is running
2023-06-10 18:06:28,173 - [WARNING] - [Thread-50] - root - (threaded_unix_sender.py).__send_protobuf(63) - Failed to send on /tmp/tbots/yellow/ssl_referee, make sure the receiver is running
2023-06-10 18:06:30,741 - [WARNING] - [Thread-48] - root - (threaded_unix_sender.py).__send_protobuf(63) - Failed to send on /tmp/tbots/yellow/robot_status, make sure the receiver is running
2023-06-10 18:06:30,743 - [WARNING] - [Thread-49] - root - (threaded_unix_sender.py).__send_protobuf(63) - Failed to send on /tmp/tbots/yellow/ssl_wrapper, make sure the receiver is running
2023-06-10 18:06:30,771 - [WARNING] - [Thread-50] - root - (threaded_unix_sender.py).__send_protobuf(63) - Failed to send on /tmp/tbots/yellow/ssl_referee, make sure the receiver is running
```

### Acceptance criteria

- [ ]

### PR DESCRIPTION
**Pull request by williamckha**
### Description

Fixes issue with team not responding after transitioning out of penalty kick

If we run into another SIGABRT or similar at robocup, just comment out these lines:

https://github.com/UBC-Thunderbots/Software/blob/d33056744b445243cfe7dc759677ff8e93eea984/src/software/ai/hl/stp/tactic/tactic.cpp#L32

https://github.com/UBC-Thunderbots/Software/blob/d33056744b445243cfe7dc759677ff8e93eea984/src/software/ai/hl/stp/tactic/tactic.cpp#L42-L44
 

### Testing Done

Ran thunderscope and transitioning out of penalty kick no longer causes any problems 

### Resolved Issues

Resolves #2932 

### Review Checklist

**_It is the reviewers responsibility to also make sure every item here has been covered_**

- [ ] **Function & Class comments**: All function definitions (usually in the `.h` file) should have a javadoc style comment at the start of them. For examples, see the functions defined in `thunderbots/software/geom`. Similarly, all classes should have an associated Javadoc comment explaining the purpose of the class.
- [ ] **Remove all commented out code**
- [ ] **Remove extra print statements**: for example, those just used for testing
- [ ] **Resolve all TODO's**: All `TODO` (or similar) statements should either be completed or associated with a github issue

### CODE REVIEW

**Comment by nimazareian** [comment]
Just to clarify my understanding, the SIGABRT that you were seeing and robots hanging at the end of penalty kick were the same issue? 

And is the note that you've added to the description of the PR about commenting out the `CHECK`, in case we get more SIGABRTs, or have you actually observed other SIGABRTs from that failing check after your fix as well?

**Review by nimazareian — APPROVED** [review]
LGTM. Just pending @itsarune 's review since he's more familiar with this than me

**Comment by williamckha** [comment]
> Just to clarify my understanding, the SIGABRT that you were seeing and robots hanging at the end of penalty kick were the same issue?

Yes

> And is the note that you've added to the description of the PR about commenting out the `CHECK`, in case we get more SIGABRTs, or have you actually observed other SIGABRTs from that failing check after your fix as well?

It's in case I missed something and we get more SIGABRTs. I believe the CHECK is just a safeguard to protect ourselves from introducing bugs, since we want to make sure tactics always set primitives. I've combed through all the tactic FSMs to make sure all our transitions trigger an primitive-setting action (PenaltyKickFSM had a transition with a missing action, which I've fixed in this pr), but I might have glossed over a missing action somewhere.

If a tactic ends up not setting primitives, I think we can just default to using the last set primitive, which is what I proposed in the note (skip resetting the primitive pointer before calling `updatePrimitive`)

**Review by germchow — APPROVED** [review]

**Comment by nimazareian** [comment]
> If a tactic ends up not setting primitives, I think we can just default to using the last set primitive, which is what I proposed in the note (skip resetting the primitive pointer before calling updatePrimitive)

This is an interesting idea! Though the CHECK is also nice since its a very explicit way of knowing that something's missing. But I guess we did still kind of miss it for Penalty Kick FSM

**Comment by itsarune** [comment]
Oh strange, I'd have thought that the kickfsm state machine would've spit out the primitives.

good catch!

**Comment by itsarune** [comment]
oh I see KickFSM doesn't get control params to operate on without that shoot action

**Pull request merged**
