### PR TITLE
fix spellings

### PR DESCRIPTION
**Pull request by akhilveeraghanta**
### Description
ran `codespell -w` on the repo to fix typos

### Testing Done
N/A

### Resolved Issues

N/A
### Length Justification

N/A
### Review Checklist

**_It is the reviewers responsibility to also make sure every item here has been covered_**

- [x] **Function & Class comments**: All function definitions (usually in the `.h` file) should have a javadoc style comment at the start of them. For examples, see the functions defined in `thunderbots/software/geom`. Similarly, all classes should have an associated Javadoc comment explaining the purpose of the class.
- [x] **Remove all commented out code**
- [x] **Remove extra print statements**: for example, those just used for testing
- [x] **Resolve all TODO's**: All `TODO` (or similar) statements should either be completed or associated with a github issue
- [x] **Justify drops in code coverage**: If this PR results in a non-trivial drop in code coverage (a bot should post a coverage diagram as a comment), please justify why we can't test the code that's not covered.

### CODE REVIEW

**Comment by akhilveeraghanta** [comment]
Should we run `codespell` as part of CI to catch typos?

**Review by MathewMacDougall — APPROVED** [review]
Oh that's neat! TIL this exists. I'd be fine with it in CI, and we can have a "fix-typos.sh` script.

**Review by kelvinkoon — APPROVED** [review]
I'd like to see `codespell` run in CI as well. Maybe make a separate ticket for it or include it in this PR?

**Review by jonathanlew — COMMENTED** [review]
That's neat. I think it can be part of fix formatting

**Comment by garethellis0** [comment]
> That's neat. I think it can be part of fix formatting

Having it as part of fix formatting would be awesome! Just need to figure out if it's going to correct things that we "misspell" intentionally. @akhilveeraghanta - did you have to revert any of the changes that it made?

**Review by garethellis0 — APPROVED** [review]

**Review by LiCody — APPROVED** [review]
this is pretty cool 👍

**Review by jonathanlew — APPROVED** [review]
Can you open an issue for adding codespell to CI?

**Pull request merged**
