### PR TITLE
parameter_options: drop down menu for string input

### PR DESCRIPTION
**Pull request by akhilveeraghanta**
## WIP Parameter option support
- parameter options tested for strings (so far only strings known to work)
- not finalized

@garethellis0 and @MathewMacDougall please let me know if these changes run on your machines and are reasonable, then I can clean up this PR and untouch the yaml files

Some things to note: 
- if the wrong type of options are provided (int options for str param) then the code doesn't catch that and gracefully print a message, the build just fails and its up to the user to look through the stacktrace
- we can support the same parameter option for multiple parameters, except it will identify with the fully qualified namespace (can check the options on the reconfigure window to see what I mean)
- the default option provided must be in the options given, otherwise even though the build succeeds, the reconfigure window will crash during run time (we can add a quick check for this)

### Review Checklist

**_It is the reviewers responsibility to also make sure every item here has been covered_**

- [ ] **Start of document comments**: each `.cpp` and `.h` file should have a comment at the start of it. See files in the `thunderbots/software/geom` folder for examples.
- [ ] **Function comments**: All function definitions (usually in the `.h` file) should have a javadoc style comment at the start of them. For examples, see the classes defined in `thunderbots/software/geom`
- [ ] **Remove all commented out code**
- [ ] **Remove extra print statements**: for example, those just used for testing
- [ ] **Resolve all TODO's**: All `TODO` (or similar) statements should either be completed or associated with a github issue
- [ ] **Justify drops in code coverage**: If this PR results in a non-trivial drop in code coverage (a bot should post a coverage diagram as a comment), please justify why we can't test the code that's not covered.

### CODE REVIEW

**Review by garethellis0 — DISMISSED** [review]
Confirmed works on my machine. LGTM :+1: :tada: (once the place names in `ai_control.yaml` are changed to match the actual available plays).

**Review by MathewMacDougall — DISMISSED** [review]
LGTM, ready for the full version

**Comment by akhilveeraghanta** [comment]
@MathewMacDougall @garethellis0 updated ai yaml file

**Comment by garethellis0** [comment]
Can we add a quick check for the "no default value" case? I actually already ran into it here and it was not immediately obvious what happened.

**Review by MathewMacDougall — COMMENTED** [review]
Nothing to add beyond Gareth's comments

**Review by MathewMacDougall — APPROVED** [review]
LGTM :+1:

**Review by garethellis0 — APPROVED** [review]
LGTM :+1: :tada:

**Pull request merged**
