### PR TITLE
Implementing Stop Primitive with Grsim

### LINKED ISSUE #96: grSim backend - Implement Stop Primitive
[grSim](https://github.com/RoboCup-SSL/grSim) is the "standard" simulator for the SSL Division, and is the simulator we use.

Because we currently don't/can't simulate our robot's firmware, we need to re-create how we move and control the robots for the simulator. Rather than sending a Primitive command to a robot over radio, which will then be executed by the robot firmware in order to do whatever the command asks, we need to send different commands to the simulator to move the robots.

We already have the ability to send commands to the simulator with #12 . The ability to control a robot's movement is further abstracted by the motion controller developed in #9 . This imitates the bang-bang motion controller on our robots, so that robot's will speed up and slow down more realistically as the move in the simulator.

** Currently blocked by #9  **

The task here is to create a function/routine to implement our Stop Primitive using this motion-controller abstraction, so this Primitive can be simulated. We need these primitive to work in the simulator so we can actually use the simulator for testing.

The spec for the Stop Primitive can be found in #86 , and also in the StopPrimitive class from #90 

The StopPrimitive class will be the input. The exact place this code will go will be revised once #9 is merged, and we will update the ticket.

### PR DESCRIPTION
**Pull request by jared-paul**
### Description

_(Creating this PR a little early so I can get more feedback on the progress and where it's going)_

Implements interaction between the Stop Primitive and Grsim

- Added motion controller commands for Stop Primitive in grsim_command_primitive_visitor.cpp.

- Added stopping at the robots current position and orientation, no option for coasting to a stop yet

### Testing Done

- Manually tested if the robot stops in Grsim with a simple chron timer in main.cpp:

      //the system time at which AI is launched
      auto start = std::chrono::system_clock::now();

      // Main loop
      while (ros::ok())
      {
        // Clear all primitives each tick
        primitives.clear();

        // Spin once to let all necessary callbacks run
        // The callbacks will populate the primitives vector
        ros::spinOnce();

        //the current time of the system
        auto current_time = std::chrono::system_clock::now();

        //getting how much time has passed since Grsim launched
        std::chrono::duration<double> elapsed_seconds = end - start;
        
        //converting to seconds
        double seconds = elapsed_seconds.count();
       
        //wait 10 seconds then stop the robot
        if (seconds < 10)
        {
            primitives.emplace_back(new MovePrimitive(1, Point(0, 0), Angle::zero(), 0.0));
        }
        else
        {
            primitives.emplace_back(new StopPrimitive(1, false));
        }

        grsim_backend.sendPrimitives(primitives, friendly_team);

        tick_rate.sleep();
      }

### Resolved Issues

Resolves #96 

### Length Justification

N/A

### Review Checklist

**_It is the reviewers responsibility to also make sure every item here has been covered_**

- [x] **Start of document comments**: each `.cpp` and `.h` file should have a comment at the start of it. See files in the `thunderbots/software/geom` folder for examples.
- [x] **Function comments**: All function definitions (usually in the `.h` file) should have a javadoc style comment at the start of them. For examples, see the classes defined in `thunderbots/software/geom`
- [x] **Remove all commented out code**
- [x] **Remove extra print statements**: for example, those just used for testing
- [x] **Resolve all TODO's**: All `TODO` (or similar) statements should either be completed or associated with a github issue
- [x] **Justify drops in code coverage**: If this PR results in a non-trivial drop in code coverage (a bot should post a coverage diagram as a comment), please justify why we can't test the code that's not covered.

### CODE REVIEW

**Comment by jared-paul** [comment]
I'm having a little trouble thinking of how to add the option to coast to a stop and what that would look like for a MotionControllerCommand

**Comment by garethellis0** [comment]
Hmm. This is a tricky problem, because we control the velocity of the robot directly. I'll defer to @MathewMacDougall with regards to how neccesary modeling coasting to a stop is, but if it's not super important then I think that it's probably more effort then it's worth. 

It's worth noting that we're at least on par with the old code though. Just dug around a bit and found the equivalent snippet from the old codebase:
```
switch (_prim)
    {
        case Drive::Primitive::MOVE:
            _move_dest      = p.field_point();
            _move_ori       = p.field_angle();
            _move_end_speed = p.params[3] / 1000.0;
            break;

        case Drive::Primitive::DRIBBLE:
            _move_dest = p.field_point();
            _move_ori  = p.field_angle();
            break;

        case Drive::Primitive::SHOOT:
            _move_dest   = p.field_point();
            _move_ori    = p.field_angle();
            _shoot_power = p.params[3] / 1000.0;
            break;

        case Drive::Primitive::CATCH:
            _catch_displacement = p.params[1] / 1000.0;
            _catch_speed        = p.params[2] / 1000.0;
            _move_ori           = Angle::of_radians(p.params[0] / 100.0);
            break;

        case Drive::Primitive::PIVOT:
            _pivot_swing = p.field_angle();
            _move_dest   = p.field_point();
            _move_ori    = Angle::of_radians(p.params[3] / 100.0);
            break;

        case Drive::Primitive::SPIN:
            _move_dest = p.field_point();
            _move_ori  = p.field_angle();
            break;

        case Drive::Primitive::STOP:
            break;
    }
```

**Comment by MathewMacDougall** [comment]
LOL the old code was janky.

The exact behavior of coasting during Stop is really not a big concern, especially in grsim. There's not really cases where we _really_ want to pick coasting vs not coasting in most realistic scenarios I can think of. Right now I think it's more effort than it's worth, so just giving the same behavior regardless of the `coast` boolean is totally fine, just leave a comment in the `visit` function explaining that is intentional.

**Comment by jared-paul** [comment]
I added the comment, but is there a way in high level to stop providing power to the robots wheels?

**Comment by MathewMacDougall** [comment]
No, our High Level / Gameplay logic doesn't control wheel power directly. That's why we abstract things with the Primitives.

There's no way to stop providing power to the robot wheels in grSim because we are only able to directly control the robot's velocity. There's no concept of "wheel power" like how you would expect in real life.

I believe our real robots do simply stop providing power to the wheels when coasting to a stop in real life, but we unfortunately can't perfectly replicate that with grSim.

**Comment by jared-paul** [comment]
oh ok

Is there anything else that needs to be done with this pull request?

**Comment by MathewMacDougall** [comment]
The issue with the `assignGoalie` function in the `Team` class throwing exceptions has been temporarily fixed in #288. Make sure to update your branch.

**Review by MathewMacDougall — APPROVED** [review]
LGTM

**Comment by qgolsteyn** [comment]
@jared-paul Please merge when you get the chance

**Pull request merged**
