### PR TITLE
Move simulator code to new top-level software folder

### PR DESCRIPTION
**Pull request by MathewMacDougall**
### Description

Moved the existing simulator code to a new top-level software folder. The files have not been changed aside from the include paths, so shouldn't really require any review. The new simulator will be developed in this folder until it can replace the old one, at which time the old code will be removed.

### Testing Done

code builds

### Resolved Issues

#1324 

### Length Justification

It's just copying files, not much I can do.

### Review Checklist

**_It is the reviewers responsibility to also make sure every item here has been covered_**

- [x] **Function & Class comments**: All function definitions (usually in the `.h` file) should have a javadoc style comment at the start of them. For examples, see the functions defined in `thunderbots/software/geom`. Similarly, all classes should have an associated Javadoc comment explaining the purpose of the class.
- [x] **Remove all commented out code**
- [x] **Remove extra print statements**: for example, those just used for testing
- [x] **Resolve all TODO's**: All `TODO` (or similar) statements should either be completed or associated with a github issue
- [x] **Justify drops in code coverage**: If this PR results in a non-trivial drop in code coverage (a bot should post a coverage diagram as a comment), please justify why we can't test the code that's not covered.

### CODE REVIEW

**Review by garethellis0 — CHANGES_REQUESTED** [review]
Looks like the files were copied, not moved?

**Comment by MathewMacDougall** [comment]
Correct. I'm leaving the old ones until we replace them with the new Simulator as to not break the existing `SimulatorBackend` and related functionality.

**Review by jonathanlew — COMMENTED** [review]
Suggestion: name the folder new_simulation as we did with new_geom

**Comment by MathewMacDougall** [comment]
I wasn't planning to since they're at different levels so there won't be a naming conflict.

**Comment by MathewMacDougall** [comment]
After some offline talk with Gareth I've now moved the files so this can be a more incremental change and we avoid duplicating code in the repo. @jonathanlew this also addressed your comment about naming, since the folder is just moved now (not copied).

**Review by jonathanlew — APPROVED** [review]
LGTM! :+1:

**Review by garethellis0 — APPROVED** [review]
LGTM :+1: :tada:

**Review by akhilveeraghanta — APPROVED** [review]

**Review by EvanMorcom — APPROVED** [review]
LGTM :fire:

**Pull request merged**
