### PR TITLE
Added .gitattributes File To Enforce Consistent Line Endings

### PR DESCRIPTION
**Pull request by garethellis0**
### Description
Added .gitattributes File To Enforce Consistent Line Endings (see https://help.github.com/articles/dealing-with-line-endings/)

### Testing Done
Confirmed this didn't brick my repo. 

### Resolved Issues
NA

### Review Checklist
*(Please check every item to indicate your code complies with it (by changing `[ ]`->`[x]`). This will hopefully save both you and the reviewer(s) a lot of time!)*
***It is the reviewers responsibility to also make sure every item here has been covered***
- [x] **Start of document comments**: each `.cpp` and `.h` file should have a comment at the start of it. See files in the `thunderbots/software/geom` folder for examples.
- [x] **Function comments**: All function definitions (usually in the `.h` file) should have a javadoc style comment at the start of them. For examples, see the classes defined in `thunderbots/software/geom` 
- [x] **Remove all commented out code**
- [x] **Remove extra print statements**: for example, those just used for testing
- [x] **Resolve all TODO's**: All `TODO` (or similar) statements should either be completed or associated with a github issue

***Feel free to make additions of things that we should be checking to this file if you think there's something missing!!!!***

### CODE REVIEW

**Comment by garethellis0** [comment]
@MathewMacDougall - ~this ought to save you a lot of typing.... :rofl:~

**Edit:** Sadly this doesn't do what I thought it would :cry: (fix all the "missing end-of-file" github warnings). Still good to have though.

**Comment by garethellis0** [comment]
Closing because this isn't super important and it made git think every file in the repo was a

**Review by MathewMacDougall — APPROVED** [review]
LGTM

**Comment by MathewMacDougall** [comment]
Just curious, what exactly were you hoping this would do?

**Comment by garethellis0** [comment]
I was hoping it would fix the end-of-file issues that github complains about (little red arrow at the bottom of the file).

**Comment by MathewMacDougall** [comment]
Oh. Yea as far as I know this only handles end of _line_ stuff. Still definitely good to have.

**Pull request merged**
