### PR TITLE
Updated sizes and size policies so text boxes don't get cutoff in RobotDiagnosticsGUI

### PR DESCRIPTION
**Pull request by MathewMacDougall**
### Description

* Some text boxes had small fixed max sizes. Changed to MAX_INT
* Changed size policies of horizontal spacers and lines to EXPANDING
instead of MINIMUM so they can shrink if needed

### Testing Done

Manual verification

### Review Checklist

**_It is the reviewers responsibility to also make sure every item here has been covered_**

- [x] **Function & Class comments**: All function definitions (usually in the `.h` file) should have a javadoc style comment at the start of them. For examples, see the functions defined in `thunderbots/software/geom`. Similarly, all classes should have an associated Javadoc comment explaining the purpose of the class.
- [x] **Remove all commented out code**
- [x] **Remove extra print statements**: for example, those just used for testing
- [x] **Resolve all TODO's**: All `TODO` (or similar) statements should either be completed or associated with a github issue
- [x] **Justify drops in code coverage**: If this PR results in a non-trivial drop in code coverage (a bot should post a coverage diagram as a comment), please justify why we can't test the code that's not covered.

### CODE REVIEW

**Comment by MathewMacDougall** [comment]
I'd like to trigger
* JonCI :tm: 
* CodyCI :tm: 
* GarethCI :tm:

since I recall you all were able to reproduce the initial issue to varying degrees

@jonathanlew @LiCody @garethellis0

**Review by kelvinkoon — APPROVED** [review]
LGTM pending additional CI :tm:

**Review by jonathanlew — APPROVED** [review]
Passes JonCI:tm:

**Review by garethellis0 — APPROVED** [review]
Passes GarethCI :tm:

**Pull request merged**
