### PR TITLE
Change empty arg to void arg in function definitions in firmware/app …

### PR DESCRIPTION
**Pull request by jonathanlew**
…and firmware/boards/legacy_robot_stm32f4

### Description
Change empty arg to void arg in function definitions in firmware/app and firmware/boards/legacy_robot_stm32f4 according to the new style convention that addresses this issue: https://softwareengineering.stackexchange.com/questions/286490/what-is-the-difference-between-function-and-functionvoid/286494 Although this style convention applies to software as well, it actually makes a difference in firmware since the issue only affect C code. 

### Review Checklist

**_It is the reviewers responsibility to also make sure every item here has been covered_**

- [ ] **Function & Class comments**: All function definitions (usually in the `.h` file) should have a javadoc style comment at the start of them. For examples, see the functions defined in `thunderbots/software/geom`. Similarly, all classes should have an associated Javadoc comment explaining the purpose of the class.
- [ ] **Remove all commented out code**
- [ ] **Remove extra print statements**: for example, those just used for testing
- [ ] **Resolve all TODO's**: All `TODO` (or similar) statements should either be completed or associated with a github issue
- [ ] **Justify drops in code coverage**: If this PR results in a non-trivial drop in code coverage (a bot should post a coverage diagram as a comment), please justify why we can't test the code that's not covered.

### CODE REVIEW

**Review by MathewMacDougall — DISMISSED** [review]
LGTM :+1:

**Review by kelvinkoon — CHANGES_REQUESTED** [review]
Can you check if `dribbler_test.cpp`, `chicker_test.cpp`, and `firmware_world_test.cpp` in `/app` need changes as well? Otherwise, looks good to me.

**Comment by jonathanlew** [comment]
> dribbler_test.cpp

Good catch!

**Review by kelvinkoon — APPROVED** [review]

**Review by garethellis0 — APPROVED** [review]
Whoops, thanks for cleaning up after me, I should have done this in the first place :sweat_smile:.

LGTM :+1: :tada:

**Review by MathewMacDougall — APPROVED** [review]

**Pull request merged**
