### PR TITLE
Pass World by const reference instead of via WorldPtr

### PR DESCRIPTION
**Pull request by williamckha**
### Description

#3129 recently made it so that we pass around `WorldPtr` throughout our codebase. It seems like passing `shared_ptr` when we don't mean to share ownership is unnecessary and not a [best practice](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#f7-for-general-use-take-t-or-t-arguments-rather-than-smart-pointers).
 
> Don’t pass a smart pointer as a function parameter unless you want to use or manipulate the smart pointer itself, such as to share or transfer ownership.

If we don't mean to share ownership, we should just pass a reference to the `World` pointed to by the `shared_ptr`. Dereferencing the pointer and passing it as an argument will not incur a copy and clearly signifies intent (non-ownership).

### Testing Done

AI builds and runs

### Review Checklist

**_It is the reviewers responsibility to also make sure every item here has been covered_**

- [ ] **Function & Class comments**: All function definitions (usually in the `.h` file) should have a javadoc style comment at the start of them. For examples, see the functions defined in `thunderbots/software/geom`. Similarly, all classes should have an associated Javadoc comment explaining the purpose of the class.
- [ ] **Remove all commented out code**
- [ ] **Remove extra print statements**: for example, those just used for testing
- [ ] **Resolve all TODO's**: All `TODO` (or similar) statements should either be completed or associated with a github issue

### CODE REVIEW

**Review by mkhlb — COMMENTED** [review]
Good idea, the change to a pointer was def applied a bit too heavily. Still looking through all the changes. Correct me if i'm wrong, but it doesnt seem that `deflectOffEnemyTarget`  needs ownership of the world, should that be changed too?

**Review by nimazareian — COMMENTED** [review]
The changes overall LGTM. 

Just want to clarify when we should use either of the two options so we're all on the same page going forward. Is the goal to use references in functions/methods that are more for utility or specific algorithms, and pass WorldPtrs if it's more directly AI related (e.g. FSMs)? Since we're never actually modifying the Worlds, so I guess the question would be what would account as "sharing ownership"?

**Comment by williamckha** [comment]
> The changes overall LGTM.
> 
> Just want to clarify when we should use either of the two options so we're all on the same page going forward. Is the goal to use references in functions/methods that are more for utility or specific algorithms, and pass WorldPtrs if it's more directly AI related (e.g. FSMs)? Since we're never actually modifying the Worlds, so I guess the question would be what would account as "sharing ownership"?

An object shares ownership when it retains that smart pointer (e.g. If some object copies a `shared_ptr` and stores it in a member variable, that object now is sharing ownership over the object pointed to by the `shared_ptr`). The owning object now has some authority over the lifetime of the shared object, since the shared object won't be destroyed as long as the owning object is alive.

So if we don't need to copy `WorldPtr` (usually the case in utility/evaluation functions where we just need a reference to the shared object for the scope of the function) we don't need to pass in `WorldPtr`. We need to store `WorldPtr` in the `Update` struct for FSMs which is why some FSM code passes around `WorldPtr`

**Comment by williamckha** [comment]
> Good idea, the change to a pointer was def applied a bit too heavily. Still looking through all the changes. Correct me if i'm wrong, but it doesnt seem that `deflectOffEnemyTarget` needs ownership of the world, should that be changed too?

Good catch, updated

**Comment by itsarune** [comment]
@williamckha good catch. I was thinking of smart pointers as total pointer replacements and wasn't thinking of ownership in that way. If we consider ownership, then the only classes that should share ownership of World are SensorFusion, AI and Strategy (PassStrategy needs to share the World because of its multithreadedness).

In that case, it doesn't really make sense for FSMs to have a shared_ptr since its running as part of AI and doesn't need to take ownership. This may be a case where we actually should be using raw pointers to prevent those copies and fit the intention of C++ shared_ptr use.

**Review by nimazareian — DISMISSED** [review]

**Review by Bvasilchikov — APPROVED** [review]
Awesome work going through the codebase!

**Review by nimazareian — APPROVED** [review]
💯

**Pull request merged**
