### PR TITLE
Use t_capture Instead of now()  for Timestamp

### LINKED ISSUE #150: Change timestamps to use t_capture instead of now()
Vision threading looks like it requires camera capture time instead of when we receive a detection  packet. Creating this ticket to change the timestamping stuff from `now()` (when we receive the packet) to `t_capture` given by the detection packet.

### PR DESCRIPTION
**Pull request by matthewberends**
### Description
Vision threading looks like it requires camera capture time instead of when we receive a detection packet. Creating this ticket to change the timestamping stuff from now() (when we receive the packet) to t_capture given by the detection packet.

### Testing Done
Built the code and ran unit tests successfully.

### Resolved Issues
resolves #150 

### Review Checklist
*(Please check every item to indicate your code complies with it (by changing `[ ]`->`[x]`). This will hopefully save both you and the reviewer(s) a lot of time!)*
***It is the reviewers responsibility to also make sure every item here has been covered***
- [x] **Start of document comments**: each `.cpp` and `.h` file should have a comment at the start of it. See files in the `thunderbots/software/geom` folder for examples.
- [x] **Function comments**: All function definitions (usually in the `.h` file) should have a javadoc style comment at the start of them. For examples, see the classes defined in `thunderbots/software/geom` 
- [x] **Remove all commented out code**
- [x] **Remove extra print statements**: for example, those just used for testing
- [x] **Resolve all TODO's**: All `TODO` (or similar) statements should either be completed or associated with a github issue
- [x] **Justify drops in code coverage**: If this PR results in a non-trivial drop in code coverage (a bot should post a coverage diagram as a comment), please justify why we can't test the code that's not covered.

### CODE REVIEW

**Review by henryymliu — DISMISSED** [review]
LGTM, nice work :+1:

**Review by MathewMacDougall — COMMENTED** [review]
@matthewberends did you figure out what the units of `t_capture` are? Eg. microseconds since the UNIX epoch? We'll need to know the units somehow to get accurate time differentials to do physics calculations.

**Review by garethellis0 — DISMISSED** [review]
LGTM 👍 🎉 - you'll probably need re-review once you update your branch, feel free to just leave a comment whenever you do.

**Comment by matthewberends** [comment]
> @matthewberends did you figure out what the units of `t_capture` are? Eg. microseconds since the UNIX epoch? We'll need to know the units somehow to get accurate time differentials to do physics calculations.

I ran a test with grsim and the units of t_capture appear to be seconds. I will add some comments to make that more clear in the future.

**Review by henryymliu — APPROVED** [review]

**Review by MathewMacDougall — APPROVED** [review]

**Comment by matthewberends** [comment]
:shipit:

**Pull request merged**
